// Exact text modules embedded by runtime/config.capnp, not arbitrary imports.
declare module "r2-facade-source" { const source: string; export default source; }
declare module "kv-facade-source" { const source: string; export default source; }
declare module "d1-facade-source" { const source: string; export default source; }
declare module "do-facade-source" { const source: string; export default source; }
declare module "do-id-codec-source" { const source: string; export default source; }
declare module "do-alarm-shim-source" { const source: string; export default source; }
declare module "do-output-gate-source" { const source: string; export default source; }
declare module "do-facets-source" { const source: string; export default source; }
declare module "queue-facade-source" { const source: string; export default source; }
declare module "serialization-codec-source" { const source: string; export default source; }
declare module "serialization-encode-source" { const source: string; export default source; }
declare module "serialization-decode-source" { const source: string; export default source; }
declare module "serialization-format-source" { const source: string; export default source; }
declare module "workflow-runner-source" { const source: string; export default source; }
declare module "workflow-duration-source" { const source: string; export default source; }
declare module "workflow-codec-source" { const source: string; export default source; }
declare module "workflow-facade-source" { const source: string; export default source; }
declare module "wrapper-runtime-source" { const source: string; export default source; }
declare module "do-wrapper-source" { const source: string; export default source; }
declare module "workflow-wrapper-source" { const source: string; export default source; }
declare module "assets-facade-source" { const source: string; export default source; }
declare module "service-facade-source" { const source: string; export default source; }
declare module "service-scope-source" { const source: string; export default source; }
declare module "socket-tunnel-source" { const source: string; export default source; }
declare module "cache-facade-source" { const source: string; export default source; }
declare module "images-facade-source" { const source: string; export default source; }
