import type { DoPolicy, DoPolicyEnv } from "../durable-objects/protocol.js";
import { assertSnapshot } from "./snapshot.js";
import type { LoaderEnv, RuntimeEnvelope, RuntimeSnapshot } from "./protocol.js";

const SOURCE_PATH = "/internal/runtime/v1/versions/resolve";
/** Generation-authenticated private runtime-source header. */
export const TOKEN_HEADER = "x-open-compute-internal-token";
let startupGeneration: string | undefined;
const assembling = new Map<string, Promise<WorkerLoaderWorkerCode>>();

/** Generation-authenticated private binding header. */
export const BINDING_TOKEN_HEADER = "x-open-compute-binding-token";

/** Generate the canonical UUIDv7 required by trusted private request authority. */
export function systemRequestId(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  let timestamp = Date.now();
  for (let index = 5; index >= 0; index -= 1) {
    bytes[index] = timestamp % 256;
    timestamp = Math.floor(timestamp / 256);
  }
  bytes[6] = (bytes[6]! & 0x0f) | 0x70;
  bytes[8] = (bytes[8]! & 0x3f) | 0x80;
  const hex = Array.from(bytes, byte => byte.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/** Headers which may only be generated by the trusted loader host. */
export const INTERNAL_HEADERS = Object.freeze([
  TOKEN_HEADER,
  "x-open-compute-account-id",
  "x-open-compute-worker-id",
  "x-open-compute-version-id",
  "x-open-compute-loader-key",
  "x-open-compute-execution-started",
  "x-open-compute-asset-representation-length",
  "x-open-compute-worker-code-sha256",
  "x-open-compute-entrypoint",
  "x-open-compute-original-method",
  "x-open-compute-original-url",
  "x-open-compute-route-generation",
  "x-open-compute-request-id",
  "x-open-compute-output-gate",
  "x-open-compute-binding-id",
  "x-open-compute-binding-token",
  "x-open-compute-descriptor-sha256",
  "x-open-compute-namespace-resource-id",
  "x-open-compute-object-id",
  "x-open-compute-object-generation",
  "x-open-compute-class-name",
  "x-open-compute-asset-method",
  "x-open-compute-asset-url",
  "x-open-compute-do-method",
  "x-open-compute-do-url",
  "x-open-compute-do-operation",
  "x-open-compute-startup-generation",
  "forwarded",
  "x-forwarded-for",
  "x-forwarded-host",
  "x-forwarded-proto",
]);

/** Select the one public-only outbound capability for tenant code, or disable it for validation. */
export function tenantGlobalOutbound(env: LoaderEnv, validation: boolean): Fetcher | null {
  if (validation) return null;
  if (env.PUBLIC_NETWORK == null) throw bindingError("VERSION_INVARIANT_VIOLATION");
  return env.PUBLIC_NETWORK;
}

/** Formal-lock date and tenant-required flags from private system bindings. */
export function lockWorkerCode(env: LoaderEnv): {
  compatibilityDate: string;
  compatibilityFlags: string[];
} {
  if (typeof env.COMPATIBILITY_DATE !== "string" || env.COMPATIBILITY_DATE.length === 0
      || !Array.isArray(env.REQUIRED_COMPATIBILITY_FLAGS)
      || !env.REQUIRED_COMPATIBILITY_FLAGS.every((flag): flag is string => typeof flag === "string")) {
    throw bindingError("VERSION_INVARIANT_VIOLATION");
  }
  return {
    compatibilityDate: env.COMPATIBILITY_DATE,
    compatibilityFlags: [...env.REQUIRED_COMPATIBILITY_FLAGS],
  };
}

/** Select compatibility metadata only from the authenticated immutable Version snapshot. */
export function snapshotWorkerCode(snapshot: RuntimeSnapshot): {
  compatibilityDate: string;
  compatibilityFlags: string[];
} {
  if (snapshot.compatibilityDate !== "2026-08-30"
      || !Array.isArray(snapshot.compatibilityFlags)
      || !(snapshot.compatibilityFlags.length === 0
        || (snapshot.compatibilityFlags.length === 1
          && snapshot.compatibilityFlags[0] === "nodejs_compat"))) {
    throw bindingError("VERSION_INVARIANT_VIOLATION");
  }
  return {
    compatibilityDate: snapshot.compatibilityDate,
    compatibilityFlags: [...snapshot.compatibilityFlags],
  };
}

function policyInteger(env: DoPolicyEnv, name: keyof DoPolicyEnv, maximum: number): number {
  const value = Number(env[name]);
  if (!Number.isSafeInteger(value) || value < 1 || value > maximum) {
    throw bindingError("DO_INTERNAL_PROTOCOL_ERROR");
  }
  return value;
}

/** Parse the platform-owned Durable Object policy environment. */
export function doPolicy(env: DoPolicyEnv): Readonly<DoPolicy> {
  return Object.freeze({
    maxObjectNameBytes: policyInteger(env, "DO_MAX_OBJECT_NAME_BYTES", 1024),
    maxFetchBodyBytes: policyInteger(env, "DO_MAX_FETCH_BODY_BYTES", 64 * 1024 * 1024),
    dispatchTimeoutMs: policyInteger(env, "DO_DISPATCH_TIMEOUT_MS", 5 * 60 * 1000),
    maxInFlightDispatches: policyInteger(env, "DO_MAX_IN_FLIGHT_DISPATCHES", 4096),
  });
}

/** Return the immutable startup generation, optionally seeding it from trusted config. */
export function currentStartupGeneration(seed?: string | null): string {
  if (!startupGeneration) startupGeneration = seed || crypto.randomUUID();
  if (seed && startupGeneration !== seed) throw bindingError("BINDING_PROTOCOL_ERROR");
  return startupGeneration;
}

/** Resolve and strictly validate an immutable version snapshot. */
export async function resolveSnapshot(
  env: LoaderEnv,
  envelope: RuntimeEnvelope,
  validation: boolean,
  probe: boolean,
  internalToken: string | null,
): Promise<RuntimeSnapshot> {
  if (internalToken === null) throw bindingError("BINDING_PROTOCOL_ERROR");
  const response = await env.RUNTIME_SOURCE.fetch(`http://runtime-source${SOURCE_PATH}`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      [TOKEN_HEADER]: internalToken,
    },
    body: JSON.stringify({
      startupGeneration: currentStartupGeneration(internalToken),
      key: envelope.loaderKey,
      expectedWorkerCodeSha256: envelope.expected,
      scope: validation ? (probe ? "probe" : "validation") : "runtime",
    }),
  });
  if (!response.ok) {
    const code = response.headers.get("x-open-compute-error-code") || "RUNTIME_INTERNAL";
    throw bindingError(code);
  }
  const snapshot: unknown = await response.json();
  assertSnapshot(snapshot);
  if (snapshot.loaderKey !== envelope.loaderKey || snapshot.workerCodeSha256 !== envelope.expected) {
    throw bindingError("VERSION_INVARIANT_VIOLATION");
  }
  return snapshot;
}

/** Deduplicate one immutable WorkerLoader assembly while it is in flight. */
export function assembleOnce(
  key: string,
  build: () => Promise<WorkerLoaderWorkerCode>,
): Promise<WorkerLoaderWorkerCode> {
  const current = assembling.get(key);
  if (current) return current;
  const pending = build().finally(() => {
    if (assembling.get(key) === pending) assembling.delete(key);
  });
  assembling.set(key, pending);
  return pending;
}

/** Create a sanitized platform binding error with one stable code. */
export function bindingError(code: string): Error & { stableCode: string } {
  const error = Object.assign(new Error(code), { stableCode: code });
  error.stack = `Error: ${code}`;
  return error;
}
