// Generated by scripts/generate.ts from the pinned open-compute OpenAPI authority. Do not edit.
import { toFile, type APIPromise } from "cloudflare";
import type { BaseCloudflare, Cloudflare } from "cloudflare/client";
import { BaseAccounts } from "cloudflare/resources/accounts/accounts";
import { BaseInstances } from "cloudflare/resources/aisearch/namespaces/instances/instances";
import { BaseItems } from "cloudflare/resources/aisearch/namespaces/instances/items";
import { BaseJobs } from "cloudflare/resources/aisearch/namespaces/instances/jobs";
import { BaseNamespaces } from "cloudflare/resources/aisearch/namespaces/namespaces";
import { BaseTokens } from "cloudflare/resources/aisearch/tokens";
import { BaseDatabase } from "cloudflare/resources/d1/database/database";
import { BaseTimeTravel } from "cloudflare/resources/d1/database/time-travel";
import { BaseKeys } from "cloudflare/resources/kv/namespaces/keys";
import { BaseMetadata } from "cloudflare/resources/kv/namespaces/metadata";
import { BaseNamespaces as BaseNamespaces2 } from "cloudflare/resources/kv/namespaces/namespaces";
import { BaseValues } from "cloudflare/resources/kv/namespaces/values";
import { BaseMemberships } from "cloudflare/resources/memberships/memberships";
import { BaseConsumers } from "cloudflare/resources/queues/consumers";
import { BaseMessages } from "cloudflare/resources/queues/messages";
import { BaseQueues } from "cloudflare/resources/queues/queues";
import { BaseBuckets } from "cloudflare/resources/r2/buckets/buckets";
import { BaseObjects } from "cloudflare/resources/r2/buckets/objects";
import { BaseTokens as BaseTokens2 } from "cloudflare/resources/user/tokens/tokens";
import { BaseUser } from "cloudflare/resources/user/user";
import { BaseIndexes } from "cloudflare/resources/vectorize/indexes/indexes";
import { BaseMetadataIndex } from "cloudflare/resources/vectorize/indexes/metadata-index";
import {
  BaseUpload,
  type UploadCreateParams,
} from "cloudflare/resources/workers/assets/upload";
import { BaseVersions } from "cloudflare/resources/workers/beta/workers/versions";
import { BaseWorkers } from "cloudflare/resources/workers/beta/workers/workers";
import { BaseTelemetry } from "cloudflare/resources/workers/observability/telemetry";
import { BaseUpload as BaseUpload2 } from "cloudflare/resources/workers/scripts/assets/upload";
import { BaseDeployments } from "cloudflare/resources/workers/scripts/deployments";
import { BaseSchedules } from "cloudflare/resources/workers/scripts/schedules";
import {
  BaseScriptAndVersionSettings,
  type ScriptAndVersionSettingEditParams,
} from "cloudflare/resources/workers/scripts/script-and-version-settings";
import {
  BaseScripts,
  type ScriptUpdateParams,
  type ScriptUpdateResponse,
} from "cloudflare/resources/workers/scripts/scripts";
import { BaseSecrets } from "cloudflare/resources/workers/scripts/secrets";
import { BaseSettings } from "cloudflare/resources/workers/scripts/settings";
import { BaseSubdomain } from "cloudflare/resources/workers/scripts/subdomain";
import { BaseTail } from "cloudflare/resources/workers/scripts/tail";
import {
  BaseVersions as BaseVersions2,
  type VersionCreateParams,
  type VersionCreateResponse,
} from "cloudflare/resources/workers/scripts/versions";
import { BaseSubdomains } from "cloudflare/resources/workers/subdomains";
import { BaseEvents } from "cloudflare/resources/workflows/instances/events";
import { BaseInstances as BaseInstances2 } from "cloudflare/resources/workflows/instances/instances";
import { BaseStatus } from "cloudflare/resources/workflows/instances/status";
import { BaseVersions as BaseVersions3 } from "cloudflare/resources/workflows/versions";
import { BaseWorkflows } from "cloudflare/resources/workflows/workflows";
import { uploadAiSearchItem } from "./ai-search-upload.ts";
import { Artifacts } from "./artifacts.ts";
import { editWorkerSettings } from "./worker-settings-edit.ts";

/** Official transport request options reused by vendor operations. */
export type OpenComputeRequestOptions = Cloudflare.RequestOptions;

/** Portable binary request body; browser Blob/File values satisfy the structural arm. */
export type OpenComputeBinaryBody =
  | string
  | Uint8Array
  | ArrayBuffer
  | {
      readonly size: number;
      readonly type: string;
      arrayBuffer(): Promise<ArrayBuffer>;
    };

/** Native Dynamic Worker Loader binding accepted by open-compute and Wrangler. */
export type OpenComputeWorkerLoaderBinding = {
  readonly type: "worker_loader";
  readonly name: string;
};

/** Artifacts binding wire supported by Wrangler and open-compute uploads. */
export type OpenComputeArtifactsBinding = {
  readonly type: "artifacts";
  readonly name: string;
  readonly namespace: string;
};

/** JSON values accepted by Service binding props. */
export type OpenComputeJsonValue =
  | null
  | boolean
  | number
  | string
  | readonly OpenComputeJsonValue[]
  | { readonly [key: string]: OpenComputeJsonValue };

type OfficialWorkerVersionBinding = NonNullable<
  VersionCreateParams["metadata"]["bindings"]
>[number];

type OfficialWorkerScriptBinding = NonNullable<
  ScriptUpdateParams["metadata"]["bindings"]
>[number];

type OpenComputeWorkerVersionBinding =
  | Exclude<OfficialWorkerVersionBinding, { type: "service" }>
  | (Extract<OfficialWorkerVersionBinding, { type: "service" }> & {
      readonly props?: { readonly [key: string]: OpenComputeJsonValue };
    })
  | OpenComputeArtifactsBinding
  | OpenComputeWorkerLoaderBinding;

type OpenComputeWorkerScriptBinding =
  | Exclude<OfficialWorkerScriptBinding, { type: "service" }>
  | (Extract<OfficialWorkerScriptBinding, { type: "service" }> & {
      readonly props?: { readonly [key: string]: OpenComputeJsonValue };
    })
  | OpenComputeArtifactsBinding
  | OpenComputeWorkerLoaderBinding;

type OfficialWorkerSettings = NonNullable<
  ScriptAndVersionSettingEditParams["settings"]
>;
type OfficialWorkerSettingsBinding = NonNullable<
  OfficialWorkerSettings["bindings"]
>[number];

/** Native Service props accepted by open-compute's Settings PATCH. */
export type OpenComputeWorkerServiceBinding = Extract<
  OfficialWorkerSettingsBinding,
  { type: "service" }
> & { readonly props?: { readonly [key: string]: OpenComputeJsonValue } };

/** Settings PATCH parameters with open-compute's native binding fields. */
export type OpenComputeWorkerSettingsEditParams = Omit<
  ScriptAndVersionSettingEditParams,
  "settings"
> & {
  readonly settings?: Omit<OfficialWorkerSettings, "bindings"> & {
    readonly bindings?: readonly (
      | Exclude<OfficialWorkerSettingsBinding, { type: "service" }>
      | OpenComputeWorkerLoaderBinding
      | OpenComputeWorkerServiceBinding
    )[];
  };
};

/** Official script upload parameters plus the runtime-supported Worker Loader binding. */
export type OpenComputeWorkerScriptUpdateParams = Omit<
  ScriptUpdateParams,
  "metadata"
> & {
  readonly metadata: Omit<ScriptUpdateParams["metadata"], "bindings"> & {
    readonly bindings?: readonly OpenComputeWorkerScriptBinding[];
  };
};

/** Official Version upload parameters plus the runtime-supported Worker Loader binding. */
export type OpenComputeWorkerVersionCreateParams = Omit<
  VersionCreateParams,
  "metadata"
> & {
  readonly metadata: Omit<VersionCreateParams["metadata"], "bindings"> & {
    readonly bindings?: readonly OpenComputeWorkerVersionBinding[];
  };
};

type OpenComputeWorkerUploadParams =
  OpenComputeWorkerScriptUpdateParams | OpenComputeWorkerVersionCreateParams;

function workerUpload(
  transport: BaseCloudflare,
  method: "POST",
  scriptName: string,
  params: OpenComputeWorkerVersionCreateParams,
  options?: OpenComputeRequestOptions,
): APIPromise<VersionCreateResponse>;
function workerUpload(
  transport: BaseCloudflare,
  method: "PUT",
  scriptName: string,
  params: OpenComputeWorkerScriptUpdateParams,
  options?: OpenComputeRequestOptions,
): APIPromise<ScriptUpdateResponse>;
function workerUpload(
  transport: BaseCloudflare,
  method: "POST" | "PUT",
  scriptName: string,
  params: OpenComputeWorkerUploadParams,
  options?: OpenComputeRequestOptions,
): APIPromise<VersionCreateResponse | ScriptUpdateResponse> {
  const { account_id, bindings_inherit, metadata, files = [] } = params;
  const body = new FormData();
  const bindings = metadata.bindings?.map((binding) => {
    if (binding.type !== "d1" || !("database_id" in binding)) return binding;
    const { database_id, ...rest } = binding;
    return { ...rest, id: database_id };
  });
  body.append("metadata", JSON.stringify({ ...metadata, bindings }));
  const request = Promise.all(files.map((file) => toFile(file))).then(
    (parts) => {
      for (const part of parts) body.append(part.name, part, part.name);
      return {
        ...options,
        query: { bindings_inherit },
        body,
      };
    },
  );
  const path =
    "/accounts/" +
    segment(account_id) +
    "/workers/scripts/" +
    segment(scriptName) +
    (method === "POST" ? "/versions" : "");
  return transport[method === "POST" ? "post" : "put"]<
    V4Envelope<VersionCreateResponse | ScriptUpdateResponse>
  >(path, request)._thenUnwrap((envelope) => envelope.result);
}

/** Official Static Assets upload parameters with browser-native File parts. */
export type OpenComputeAssetsUploadCreateParams = Omit<
  UploadCreateParams,
  "body"
> & {
  readonly body: Record<string, string | File>;
};

/** The Cloudflare v4 success envelope returned by every vendor operation. */
export interface V4Envelope<T> {
  readonly success: true;
  readonly result: T;
  readonly errors: readonly unknown[];
  readonly messages: readonly unknown[];
}

function segment(value: string): string {
  if (value.length === 0 || value === "." || value === "..")
    throw new Error("invalid vendor path segment");
  return encodeURIComponent(value);
}

export type Backup = {
  readonly id: string;
  readonly created_on: string;
  readonly state: string;
  readonly size?: number;
};

export type CacheStatus = {
  readonly entries: number;
  readonly bytes: number;
};

export type Capabilities = {
  readonly release: string;
  readonly wrangler_version: "4.138.0";
  readonly compatibility_date: {
    readonly minimum: string;
    readonly maximum: string;
  };
  readonly compatibility_flags: readonly string[];
  readonly endpoints: Record<
    string,
    "supported" | "supported_with_deviation" | "unsupported"
  >;
  readonly deviations: readonly string[];
  readonly configuration: {
    readonly ai_search: boolean;
  };
  readonly limits: Record<string, number>;
};

export type D1CheckpointTimes = {
  readonly checkpoints_ms: readonly number[];
};

export type D1Migration = {
  readonly id: number;
  readonly name: string;
  readonly sha256: string;
  readonly applied_at_ms: number;
};

export type D1MigrationInput = {
  readonly id: number;
  readonly name: string;
  readonly sha256: string;
  readonly sql: string;
};

export type D1MigrationRequest = readonly D1MigrationInput[];

export type D1RenameRequest = {
  readonly name: string;
};

export type D1RenameResult = {
  readonly id: string;
  readonly name: string;
};

export type DurableObjectNamespace = {
  readonly id: string;
  readonly name: string;
  readonly script_name: string;
  readonly class_name: string;
  readonly state: "creating" | "ready" | "deleting" | "tombstoned";
  readonly availability: "healthy" | "degraded" | "unavailable";
  readonly availability_code?: string;
  readonly spec_generation: number;
  readonly schema_version: number;
  readonly created_on: string;
  readonly modified_on: string;
};

export type DurableObjectNamespacePage = {
  readonly items: readonly DurableObjectNamespace[];
  readonly next_cursor?: string;
};

export type DurableObjectRecord = {
  readonly id: string;
  readonly namespace_id: string;
  readonly generation: number;
  readonly state: string;
  readonly created_on: string;
  readonly modified_on: string;
  readonly deleted_on?: string;
};

export type DurableObjectRecordPage = {
  readonly items: readonly DurableObjectRecord[];
  readonly next_cursor?: string;
};

export type ImageCapacity = {
  readonly queued: number;
  readonly running: number;
  readonly capacity: number;
};

export type ObservabilityUsage = {
  readonly events: number;
  readonly breakdown: readonly {
    readonly bin: string;
    readonly dataset: "cloudflare-workers";
    readonly service: string;
    readonly count: number;
  }[];
};

export type PublicOriginRequest = {
  readonly name: string;
};

export type QueueConsumer = {
  readonly consumer_id: string;
  readonly created_on: string;
  readonly dead_letter_queue: string;
  readonly queue_name: string;
  readonly script: string;
  readonly script_name: string;
  readonly settings: {
    readonly batch_size: number;
    readonly max_concurrency: number;
    readonly max_retries: number;
    readonly max_wait_time_ms: number;
    readonly retry_delay: number;
  };
  readonly type: "worker";
};

export type QueueConsumerRuntime = {
  readonly projection_exists: boolean;
  readonly backlog_messages: number;
  readonly backlog_bytes: number;
  readonly ready_messages: number;
  readonly claimed_batches: number;
  readonly claimed_messages: number;
  readonly dlq_pending: number;
};

export type R2BucketUsage = {
  readonly object_count: number;
  readonly size_bytes: number | null;
};

export type R2MultipartCompleteRequest = {
  readonly parts: readonly R2MultipartPart[];
};

export type R2MultipartCompletedObject = {
  readonly key: string;
  readonly version: string;
  readonly size: number;
  readonly etag: string;
  readonly httpEtag: string;
  readonly uploaded: number;
  readonly storageClass: string;
};

export type R2MultipartCreate = {
  readonly key: string;
  readonly uploadId: string;
};

export type R2MultipartCreateRequest = {
  readonly key: string;
  readonly options?: {
    readonly httpMetadata?: {
      readonly contentType?: string;
      readonly contentLanguage?: string;
      readonly contentDisposition?: string;
      readonly contentEncoding?: string;
      readonly cacheControl?: string;
      readonly cacheExpiry?: number;
    };
    readonly customMetadata?: Record<string, string>;
    readonly storageClass?: "Standard" | "InfrequentAccess";
  };
};

export type R2MultipartPart = {
  readonly partNumber: number;
  readonly etag: string;
};

export type RestoreRequest = {
  readonly name: string;
};

export type RestoredResource = {
  readonly id: string;
  readonly name: string;
  readonly kind: "kv_namespace" | "d1_database";
  readonly created_on: string;
};

export type SchedulerStatus = {
  readonly state: string;
  readonly pending: number;
  readonly running: number;
};

export type SystemStatus = {
  readonly state: string;
  readonly version: string;
  readonly components: readonly {
    readonly name: string;
    readonly state: string;
    readonly message?: string;
  }[];
  readonly operator_proxy: {
    readonly mode: "direct" | "proxy" | "invalid";
    readonly source_variable?: string;
    readonly origin?: string;
  };
  readonly observability?: {
    readonly state: "healthy" | "degraded";
    readonly retention_ms: number;
    readonly max_database_bytes: number;
    readonly query_max_timeframe_ms: number;
    readonly oldest_event_ms?: number;
    readonly tail_sessions: number;
    readonly closed_client_drops: number;
    readonly overload_drops: number;
  };
  readonly deployment_runtime?: {
    readonly dispatchable: number;
    readonly quarantined: number;
    readonly active_runtime_dispatchable: boolean;
    readonly last_quarantine_reason?: string;
  };
};

export type UpgradeCheck = {
  readonly schema_version: number;
  readonly current_version: string;
  readonly available_version?: string | null;
  readonly update_available: boolean;
  readonly upgrade_allowed: boolean;
  readonly blocked_reason?: string | null;
};

export type WorkerEndpoint = {
  readonly id: string;
  readonly kind: "local_origin" | "public_origin";
  readonly url: string;
  readonly scope: "local_machine" | "public_network";
  readonly created_on: string;
};

export type WorkerServiceMetadata = {
  readonly default_environment: {
    readonly environment: string;
    readonly script: {
      readonly tag: string;
      readonly tags: readonly string[];
      readonly last_deployed_from: string;
      readonly migration_tag?: string;
      readonly limits?: {
        readonly cpu_ms: number;
        readonly subrequests: number;
      };
    };
  };
};

export type WorkflowSettings = {
  readonly default_retention: {
    readonly success_retention: number;
    readonly error_retention: number;
  };
};

function buildOpenCompute(transport: BaseCloudflare): OpenComputeVendorNode {
  return {
    backups: {
      d1: {
        create: (
          accountId: string,
          databaseId: string,
          options?: OpenComputeRequestOptions,
        ): APIPromise<Backup> =>
          transport
            .post<V4Envelope<Backup>>(
              `/accounts/${segment(accountId)}/open-compute/d1/databases/${segment(databaseId)}/backups`,
              options,
            )
            ._thenUnwrap((envelope) => envelope.result),
        list: (
          accountId: string,
          databaseId: string,
          options?: OpenComputeRequestOptions,
        ): APIPromise<readonly Backup[]> =>
          transport
            .get<V4Envelope<readonly Backup[]>>(
              `/accounts/${segment(accountId)}/open-compute/d1/databases/${segment(databaseId)}/backups`,
              options,
            )
            ._thenUnwrap((envelope) => envelope.result),
        restore: (
          accountId: string,
          backupId: string,
          body: RestoreRequest,
          options?: OpenComputeRequestOptions,
        ): APIPromise<RestoredResource> =>
          transport
            .post<V4Envelope<RestoredResource>>(
              `/accounts/${segment(accountId)}/open-compute/d1/backups/${segment(backupId)}/restore`,
              { ...options, body },
            )
            ._thenUnwrap((envelope) => envelope.result),
      },
      kv: {
        create: (
          accountId: string,
          namespaceId: string,
          options?: OpenComputeRequestOptions,
        ): APIPromise<Backup> =>
          transport
            .post<V4Envelope<Backup>>(
              `/accounts/${segment(accountId)}/open-compute/kv/namespaces/${segment(namespaceId)}/backups`,
              options,
            )
            ._thenUnwrap((envelope) => envelope.result),
        list: (
          accountId: string,
          namespaceId: string,
          options?: OpenComputeRequestOptions,
        ): APIPromise<readonly Backup[]> =>
          transport
            .get<V4Envelope<readonly Backup[]>>(
              `/accounts/${segment(accountId)}/open-compute/kv/namespaces/${segment(namespaceId)}/backups`,
              options,
            )
            ._thenUnwrap((envelope) => envelope.result),
        restore: (
          accountId: string,
          backupId: string,
          body: RestoreRequest,
          options?: OpenComputeRequestOptions,
        ): APIPromise<RestoredResource> =>
          transport
            .post<V4Envelope<RestoredResource>>(
              `/accounts/${segment(accountId)}/open-compute/kv/backups/${segment(backupId)}/restore`,
              { ...options, body },
            )
            ._thenUnwrap((envelope) => envelope.result),
      },
    },
    cache: {
      collectGarbage: (
        options?: OpenComputeRequestOptions,
      ): APIPromise<CacheStatus> =>
        transport
          .post<V4Envelope<CacheStatus>>(
            `/open-compute/cache/garbage-collection`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
      collectGarbageForAccount: (
        accountId: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<CacheStatus> =>
        transport
          .post<V4Envelope<CacheStatus>>(
            `/accounts/${segment(accountId)}/open-compute/cache/garbage-collection`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
      get: (options?: OpenComputeRequestOptions): APIPromise<CacheStatus> =>
        transport
          .get<V4Envelope<CacheStatus>>(`/open-compute/cache`, options)
          ._thenUnwrap((envelope) => envelope.result),
      getForAccount: (
        accountId: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<CacheStatus> =>
        transport
          .get<V4Envelope<CacheStatus>>(
            `/accounts/${segment(accountId)}/open-compute/cache`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
    },
    capabilities: {
      get: (options?: OpenComputeRequestOptions): APIPromise<Capabilities> =>
        transport
          .get<V4Envelope<Capabilities>>(`/open-compute/capabilities`, options)
          ._thenUnwrap((envelope) => envelope.result),
      getForAccount: (
        accountId: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<Capabilities> =>
        transport
          .get<V4Envelope<Capabilities>>(
            `/accounts/${segment(accountId)}/open-compute/capabilities`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
    },
    d1: {
      migrations: {
        apply: (
          accountId: string,
          databaseId: string,
          body: D1MigrationRequest,
          options?: OpenComputeRequestOptions,
        ): APIPromise<readonly D1Migration[]> =>
          transport
            .put<V4Envelope<readonly D1Migration[]>>(
              `/accounts/${segment(accountId)}/open-compute/d1/databases/${segment(databaseId)}/migrations`,
              { ...options, body },
            )
            ._thenUnwrap((envelope) => envelope.result),
        list: (
          accountId: string,
          databaseId: string,
          options?: OpenComputeRequestOptions,
        ): APIPromise<readonly D1Migration[]> =>
          transport
            .get<V4Envelope<readonly D1Migration[]>>(
              `/accounts/${segment(accountId)}/open-compute/d1/databases/${segment(databaseId)}/migrations`,
              options,
            )
            ._thenUnwrap((envelope) => envelope.result),
      },
      rename: (
        accountId: string,
        databaseId: string,
        body: D1RenameRequest,
        options?: OpenComputeRequestOptions,
      ): APIPromise<D1RenameResult> =>
        transport
          .patch<V4Envelope<D1RenameResult>>(
            `/accounts/${segment(accountId)}/open-compute/d1/databases/${segment(databaseId)}/name`,
            { ...options, body },
          )
          ._thenUnwrap((envelope) => envelope.result),
      timeTravel: {
        checkpoints: (
          accountId: string,
          databaseId: string,
          options?: OpenComputeRequestOptions,
        ): APIPromise<D1CheckpointTimes> =>
          transport
            .get<V4Envelope<D1CheckpointTimes>>(
              `/accounts/${segment(accountId)}/open-compute/d1/databases/${segment(databaseId)}/time-travel/checkpoints`,
              options,
            )
            ._thenUnwrap((envelope) => envelope.result),
      },
    },
    durableObjects: {
      list: (
        accountId: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<DurableObjectNamespacePage> =>
        transport
          .get<V4Envelope<DurableObjectNamespacePage>>(
            `/accounts/${segment(accountId)}/open-compute/durable-objects`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
      objects: (
        accountId: string,
        namespaceId: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<DurableObjectRecordPage> =>
        transport
          .get<V4Envelope<DurableObjectRecordPage>>(
            `/accounts/${segment(accountId)}/open-compute/durable-objects/${segment(namespaceId)}/objects`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
    },
    images: {
      capacity: (
        options?: OpenComputeRequestOptions,
      ): APIPromise<ImageCapacity> =>
        transport
          .get<V4Envelope<ImageCapacity>>(
            `/open-compute/images/capacity`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
      capacityForAccount: (
        accountId: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<ImageCapacity> =>
        transport
          .get<V4Envelope<ImageCapacity>>(
            `/accounts/${segment(accountId)}/open-compute/images/capacity`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
    },
    queues: {
      consumerRuntime: (
        accountId: string,
        queueId: string,
        consumerId: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<QueueConsumerRuntime> =>
        transport
          .get<V4Envelope<QueueConsumerRuntime>>(
            `/accounts/${segment(accountId)}/open-compute/queues/${segment(queueId)}/consumers/${segment(consumerId)}/runtime`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
    },
    r2: {
      multipart: {
        abort: (
          accountId: string,
          bucketName: string,
          uploadId: string,
          objectKey: string,
          options?: OpenComputeRequestOptions,
        ): APIPromise<null> =>
          transport
            .delete<V4Envelope<null>>(
              `/accounts/${segment(accountId)}/open-compute/r2/buckets/${segment(bucketName)}/multipart-uploads/${segment(uploadId)}/abort/${segment(objectKey)}`,
              options,
            )
            ._thenUnwrap((envelope) => envelope.result),
        complete: (
          accountId: string,
          bucketName: string,
          uploadId: string,
          objectKey: string,
          body: R2MultipartCompleteRequest,
          options?: OpenComputeRequestOptions,
        ): APIPromise<R2MultipartCompletedObject> =>
          transport
            .post<V4Envelope<R2MultipartCompletedObject>>(
              `/accounts/${segment(accountId)}/open-compute/r2/buckets/${segment(bucketName)}/multipart-uploads/${segment(uploadId)}/complete/${segment(objectKey)}`,
              { ...options, body },
            )
            ._thenUnwrap((envelope) => envelope.result),
        create: (
          accountId: string,
          bucketName: string,
          body: R2MultipartCreateRequest,
          options?: OpenComputeRequestOptions,
        ): APIPromise<R2MultipartCreate> =>
          transport
            .post<V4Envelope<R2MultipartCreate>>(
              `/accounts/${segment(accountId)}/open-compute/r2/buckets/${segment(bucketName)}/multipart-uploads`,
              { ...options, body },
            )
            ._thenUnwrap((envelope) => envelope.result),
        uploadPart: (
          accountId: string,
          bucketName: string,
          uploadId: string,
          partNumber: string,
          objectKey: string,
          body: OpenComputeBinaryBody,
          options?: OpenComputeRequestOptions,
        ): APIPromise<R2MultipartPart> =>
          transport
            .put<V4Envelope<R2MultipartPart>>(
              `/accounts/${segment(accountId)}/open-compute/r2/buckets/${segment(bucketName)}/multipart-uploads/${segment(uploadId)}/parts/${segment(partNumber)}/${segment(objectKey)}`,
              { ...options, body },
            )
            ._thenUnwrap((envelope) => envelope.result),
      },
      usage: {
        get: (
          accountId: string,
          bucketName: string,
          options?: OpenComputeRequestOptions,
        ): APIPromise<R2BucketUsage> =>
          transport
            .get<V4Envelope<R2BucketUsage>>(
              `/accounts/${segment(accountId)}/open-compute/r2/buckets/${segment(bucketName)}/usage`,
              options,
            )
            ._thenUnwrap((envelope) => envelope.result),
      },
    },
    scheduler: {
      get: (options?: OpenComputeRequestOptions): APIPromise<SchedulerStatus> =>
        transport
          .get<V4Envelope<SchedulerStatus>>(`/open-compute/scheduler`, options)
          ._thenUnwrap((envelope) => envelope.result),
      getForAccount: (
        accountId: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<SchedulerStatus> =>
        transport
          .get<V4Envelope<SchedulerStatus>>(
            `/accounts/${segment(accountId)}/open-compute/scheduler`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
      pause: (
        options?: OpenComputeRequestOptions,
      ): APIPromise<SchedulerStatus> =>
        transport
          .post<V4Envelope<SchedulerStatus>>(
            `/open-compute/scheduler/pause`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
      pauseForAccount: (
        accountId: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<SchedulerStatus> =>
        transport
          .post<V4Envelope<SchedulerStatus>>(
            `/accounts/${segment(accountId)}/open-compute/scheduler/pause`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
      repair: (
        options?: OpenComputeRequestOptions,
      ): APIPromise<SchedulerStatus> =>
        transport
          .post<V4Envelope<SchedulerStatus>>(
            `/open-compute/scheduler/repair`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
      repairForAccount: (
        accountId: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<SchedulerStatus> =>
        transport
          .post<V4Envelope<SchedulerStatus>>(
            `/accounts/${segment(accountId)}/open-compute/scheduler/repair`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
      resume: (
        options?: OpenComputeRequestOptions,
      ): APIPromise<SchedulerStatus> =>
        transport
          .post<V4Envelope<SchedulerStatus>>(
            `/open-compute/scheduler/resume`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
      resumeForAccount: (
        accountId: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<SchedulerStatus> =>
        transport
          .post<V4Envelope<SchedulerStatus>>(
            `/accounts/${segment(accountId)}/open-compute/scheduler/resume`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
    },
    system: {
      status: (options?: OpenComputeRequestOptions): APIPromise<SystemStatus> =>
        transport
          .get<V4Envelope<SystemStatus>>(`/open-compute/system/status`, options)
          ._thenUnwrap((envelope) => envelope.result),
      statusForAccount: (
        accountId: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<SystemStatus> =>
        transport
          .get<V4Envelope<SystemStatus>>(
            `/accounts/${segment(accountId)}/open-compute/system/status`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
    },
    upgrade: {
      check: (options?: OpenComputeRequestOptions): APIPromise<UpgradeCheck> =>
        transport
          .get<V4Envelope<UpgradeCheck>>(`/open-compute/upgrade/check`, options)
          ._thenUnwrap((envelope) => envelope.result),
      checkForAccount: (
        accountId: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<UpgradeCheck> =>
        transport
          .get<V4Envelope<UpgradeCheck>>(
            `/accounts/${segment(accountId)}/open-compute/upgrade/check`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
    },
    workers: {
      endpoints: (
        accountId: string,
        scriptName: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<readonly WorkerEndpoint[]> =>
        transport
          .get<V4Envelope<readonly WorkerEndpoint[]>>(
            `/accounts/${segment(accountId)}/open-compute/workers/${segment(scriptName)}/endpoints`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
      observability: {
        usage: (
          accountId: string,
          options?: OpenComputeRequestOptions,
        ): APIPromise<ObservabilityUsage> =>
          transport
            .get<V4Envelope<ObservabilityUsage>>(
              `/accounts/${segment(accountId)}/workers/observability/usage`,
              options,
            )
            ._thenUnwrap((envelope) => envelope.result),
      },
      publicOrigin: {
        delete: (
          accountId: string,
          scriptName: string,
          options?: OpenComputeRequestOptions,
        ): APIPromise<null> =>
          transport
            .delete<V4Envelope<null>>(
              `/accounts/${segment(accountId)}/open-compute/workers/${segment(scriptName)}/public-origin`,
              options,
            )
            ._thenUnwrap((envelope) => envelope.result),
        get: (
          accountId: string,
          scriptName: string,
          options?: OpenComputeRequestOptions,
        ): APIPromise<{
          readonly name: string;
          readonly url: string;
        } | null> =>
          transport
            .get<
              V4Envelope<{
                readonly name: string;
                readonly url: string;
              } | null>
            >(
              `/accounts/${segment(accountId)}/open-compute/workers/${segment(scriptName)}/public-origin`,
              options,
            )
            ._thenUnwrap((envelope) => envelope.result),
        set: (
          accountId: string,
          scriptName: string,
          body: PublicOriginRequest,
          options?: OpenComputeRequestOptions,
        ): APIPromise<WorkerEndpoint> =>
          transport
            .put<V4Envelope<WorkerEndpoint>>(
              `/accounts/${segment(accountId)}/open-compute/workers/${segment(scriptName)}/public-origin`,
              { ...options, body },
            )
            ._thenUnwrap((envelope) => envelope.result),
      },
      queueConsumers: (
        accountId: string,
        scriptName: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<readonly QueueConsumer[]> =>
        transport
          .get<V4Envelope<readonly QueueConsumer[]>>(
            `/accounts/${segment(accountId)}/workers/scripts/${segment(scriptName)}/queue-consumers`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
      serviceMetadata: (
        accountId: string,
        scriptName: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<WorkerServiceMetadata> =>
        transport
          .get<V4Envelope<WorkerServiceMetadata>>(
            `/accounts/${segment(accountId)}/workers/services/${segment(scriptName)}`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
    },
    workflows: {
      settings: (
        accountId: string,
        options?: OpenComputeRequestOptions,
      ): APIPromise<WorkflowSettings> =>
        transport
          .get<V4Envelope<WorkflowSettings>>(
            `/accounts/${segment(accountId)}/workflows/settings`,
            options,
          )
          ._thenUnwrap((envelope) => envelope.result),
    },
  };
}

export interface OpenComputeNode {
  readonly accounts: OpenComputeAccountsNode;
  readonly aiSearch: OpenComputeAiSearchNode;
  readonly d1: OpenComputeD1Node;
  readonly kv: OpenComputeKvNode;
  readonly memberships: OpenComputeMembershipsNode;
  readonly queues: OpenComputeQueuesNode;
  readonly r2: OpenComputeR2Node;
  readonly user: OpenComputeUserNode;
  readonly vectorize: OpenComputeVectorizeNode;
  readonly workers: OpenComputeWorkersNode;
  readonly workflows: OpenComputeWorkflowsNode;
}

export interface OpenComputeAccountsNode {
  readonly get: BaseAccounts["get"];
  readonly list: BaseAccounts["list"];
}

export interface OpenComputeAiSearchNode {
  readonly namespaces: OpenComputeAiSearchNamespacesNode;
  readonly tokens: OpenComputeAiSearchTokensNode;
}

export interface OpenComputeAiSearchNamespacesNode {
  readonly instances: OpenComputeAiSearchNamespacesInstancesNode;
  readonly chatCompletions: BaseNamespaces["chatCompletions"];
  readonly create: BaseNamespaces["create"];
  readonly delete: BaseNamespaces["delete"];
  readonly list: BaseNamespaces["list"];
  readonly read: BaseNamespaces["read"];
  readonly search: BaseNamespaces["search"];
  readonly update: BaseNamespaces["update"];
}

export interface OpenComputeAiSearchNamespacesInstancesNode {
  readonly items: OpenComputeAiSearchNamespacesInstancesItemsNode;
  readonly jobs: OpenComputeAiSearchNamespacesInstancesJobsNode;
  readonly chatCompletions: BaseInstances["chatCompletions"];
  readonly create: BaseInstances["create"];
  readonly delete: BaseInstances["delete"];
  readonly list: BaseInstances["list"];
  readonly read: BaseInstances["read"];
  readonly search: BaseInstances["search"];
  readonly stats: BaseInstances["stats"];
  readonly update: BaseInstances["update"];
}

export interface OpenComputeAiSearchNamespacesInstancesItemsNode {
  readonly chunks: BaseItems["chunks"];
  readonly createOrUpdate: BaseItems["createOrUpdate"];
  readonly delete: BaseItems["delete"];
  readonly download: BaseItems["download"];
  readonly get: BaseItems["get"];
  readonly list: BaseItems["list"];
  readonly logs: BaseItems["logs"];
  readonly sync: BaseItems["sync"];
  readonly upload: BaseItems["upload"];
}

export interface OpenComputeAiSearchNamespacesInstancesJobsNode {
  readonly create: BaseJobs["create"];
  readonly get: BaseJobs["get"];
  readonly list: BaseJobs["list"];
  readonly logs: BaseJobs["logs"];
  readonly update: BaseJobs["update"];
}

export interface OpenComputeAiSearchTokensNode {
  readonly list: BaseTokens["list"];
}

export interface OpenComputeD1Node {
  readonly database: OpenComputeD1DatabaseNode;
}

export interface OpenComputeD1DatabaseNode {
  readonly timeTravel: OpenComputeD1DatabaseTimeTravelNode;
  readonly create: BaseDatabase["create"];
  readonly delete: BaseDatabase["delete"];
  readonly edit: BaseDatabase["edit"];
  readonly export: BaseDatabase["export"];
  readonly get: BaseDatabase["get"];
  readonly import: BaseDatabase["import"];
  readonly list: BaseDatabase["list"];
  readonly query: BaseDatabase["query"];
  readonly raw: BaseDatabase["raw"];
  readonly update: BaseDatabase["update"];
}

export interface OpenComputeD1DatabaseTimeTravelNode {
  readonly getBookmark: BaseTimeTravel["getBookmark"];
  readonly restore: BaseTimeTravel["restore"];
}

export interface OpenComputeKvNode {
  readonly namespaces: OpenComputeKvNamespacesNode;
}

export interface OpenComputeKvNamespacesNode {
  readonly keys: OpenComputeKvNamespacesKeysNode;
  readonly metadata: OpenComputeKvNamespacesMetadataNode;
  readonly values: OpenComputeKvNamespacesValuesNode;
  readonly bulkDelete: BaseNamespaces2["bulkDelete"];
  readonly bulkGet: BaseNamespaces2["bulkGet"];
  readonly bulkUpdate: BaseNamespaces2["bulkUpdate"];
  readonly create: BaseNamespaces2["create"];
  readonly delete: BaseNamespaces2["delete"];
  readonly get: BaseNamespaces2["get"];
  readonly list: BaseNamespaces2["list"];
  readonly update: BaseNamespaces2["update"];
}

export interface OpenComputeKvNamespacesKeysNode {
  readonly list: BaseKeys["list"];
}

export interface OpenComputeKvNamespacesMetadataNode {
  readonly get: BaseMetadata["get"];
}

export interface OpenComputeKvNamespacesValuesNode {
  readonly delete: BaseValues["delete"];
  readonly get: BaseValues["get"];
  readonly update: BaseValues["update"];
}

export interface OpenComputeMembershipsNode {
  readonly list: BaseMemberships["list"];
}

export interface OpenComputeQueuesNode {
  readonly consumers: OpenComputeQueuesConsumersNode;
  readonly messages: OpenComputeQueuesMessagesNode;
  readonly create: BaseQueues["create"];
  readonly delete: BaseQueues["delete"];
  readonly get: BaseQueues["get"];
  readonly getMetrics: BaseQueues["getMetrics"];
  readonly list: BaseQueues["list"];
  readonly update: BaseQueues["update"];
}

export interface OpenComputeQueuesConsumersNode {
  readonly create: BaseConsumers["create"];
  readonly delete: BaseConsumers["delete"];
  readonly get: BaseConsumers["get"];
  readonly list: BaseConsumers["list"];
  readonly update: BaseConsumers["update"];
}

export interface OpenComputeQueuesMessagesNode {
  readonly bulkPush: BaseMessages["bulkPush"];
  readonly push: BaseMessages["push"];
}

export interface OpenComputeR2Node {
  readonly buckets: OpenComputeR2BucketsNode;
}

export interface OpenComputeR2BucketsNode {
  readonly objects: OpenComputeR2BucketsObjectsNode;
  readonly create: BaseBuckets["create"];
  readonly delete: BaseBuckets["delete"];
  readonly get: BaseBuckets["get"];
  readonly list: BaseBuckets["list"];
}

export interface OpenComputeR2BucketsObjectsNode {
  readonly delete: BaseObjects["delete"];
  readonly get: BaseObjects["get"];
  readonly list: BaseObjects["list"];
  readonly upload: BaseObjects["upload"];
}

export interface OpenComputeUserNode {
  readonly tokens: OpenComputeUserTokensNode;
  readonly get: BaseUser["get"];
}

export interface OpenComputeUserTokensNode {
  readonly verify: BaseTokens2["verify"];
}

export interface OpenComputeVectorizeNode {
  readonly indexes: OpenComputeVectorizeIndexesNode;
}

export interface OpenComputeVectorizeIndexesNode {
  readonly metadataIndex: OpenComputeVectorizeIndexesMetadataIndexNode;
  readonly create: BaseIndexes["create"];
  readonly delete: BaseIndexes["delete"];
  readonly deleteByIDs: BaseIndexes["deleteByIDs"];
  readonly get: BaseIndexes["get"];
  readonly getByIDs: BaseIndexes["getByIDs"];
  readonly info: BaseIndexes["info"];
  readonly insert: BaseIndexes["insert"];
  readonly list: BaseIndexes["list"];
  readonly listVectors: BaseIndexes["listVectors"];
  readonly query: BaseIndexes["query"];
  readonly upsert: BaseIndexes["upsert"];
}

export interface OpenComputeVectorizeIndexesMetadataIndexNode {
  readonly create: BaseMetadataIndex["create"];
  readonly delete: BaseMetadataIndex["delete"];
  readonly list: BaseMetadataIndex["list"];
}

export interface OpenComputeWorkersNode {
  readonly assets: OpenComputeWorkersAssetsNode;
  readonly beta: OpenComputeWorkersBetaNode;
  readonly observability: OpenComputeWorkersObservabilityNode;
  readonly scripts: OpenComputeWorkersScriptsNode;
  readonly subdomains: OpenComputeWorkersSubdomainsNode;
}

export interface OpenComputeWorkersAssetsNode {
  readonly upload: OpenComputeWorkersAssetsUploadNode;
}

export interface OpenComputeWorkersAssetsUploadNode {
  readonly create: (
    params: OpenComputeAssetsUploadCreateParams,
    options?: OpenComputeRequestOptions,
  ) => ReturnType<BaseUpload["create"]>;
}

export interface OpenComputeWorkersBetaNode {
  readonly workers: OpenComputeWorkersBetaWorkersNode;
}

export interface OpenComputeWorkersBetaWorkersNode {
  readonly versions: OpenComputeWorkersBetaWorkersVersionsNode;
  readonly get: BaseWorkers["get"];
}

export interface OpenComputeWorkersBetaWorkersVersionsNode {
  readonly delete: BaseVersions["delete"];
}

export interface OpenComputeWorkersObservabilityNode {
  readonly telemetry: OpenComputeWorkersObservabilityTelemetryNode;
}

export interface OpenComputeWorkersObservabilityTelemetryNode {
  readonly keys: BaseTelemetry["keys"];
  readonly liveTail: BaseTelemetry["liveTail"];
  readonly liveTailHeartbeat: BaseTelemetry["liveTailHeartbeat"];
  readonly query: BaseTelemetry["query"];
  readonly values: BaseTelemetry["values"];
}

export interface OpenComputeWorkersScriptsNode {
  readonly assets: OpenComputeWorkersScriptsAssetsNode;
  readonly deployments: OpenComputeWorkersScriptsDeploymentsNode;
  readonly schedules: OpenComputeWorkersScriptsSchedulesNode;
  readonly scriptAndVersionSettings: OpenComputeWorkersScriptsScriptAndVersionSettingsNode;
  readonly secrets: OpenComputeWorkersScriptsSecretsNode;
  readonly settings: OpenComputeWorkersScriptsSettingsNode;
  readonly subdomain: OpenComputeWorkersScriptsSubdomainNode;
  readonly tail: OpenComputeWorkersScriptsTailNode;
  readonly versions: OpenComputeWorkersScriptsVersionsNode;
  readonly delete: BaseScripts["delete"];
  readonly get: BaseScripts["get"];
  readonly list: BaseScripts["list"];
  readonly update: (
    scriptName: string,
    params: OpenComputeWorkerScriptUpdateParams,
    options?: OpenComputeRequestOptions,
  ) => ReturnType<BaseScripts["update"]>;
}

export interface OpenComputeWorkersScriptsAssetsNode {
  readonly upload: OpenComputeWorkersScriptsAssetsUploadNode;
}

export interface OpenComputeWorkersScriptsAssetsUploadNode {
  readonly create: BaseUpload2["create"];
}

export interface OpenComputeWorkersScriptsDeploymentsNode {
  readonly create: BaseDeployments["create"];
  readonly delete: BaseDeployments["delete"];
  readonly get: BaseDeployments["get"];
  readonly list: BaseDeployments["list"];
}

export interface OpenComputeWorkersScriptsSchedulesNode {
  readonly get: BaseSchedules["get"];
  readonly update: BaseSchedules["update"];
}

export interface OpenComputeWorkersScriptsScriptAndVersionSettingsNode {
  readonly edit: (
    scriptName: string,
    params: OpenComputeWorkerSettingsEditParams,
    options?: OpenComputeRequestOptions,
  ) => ReturnType<BaseScriptAndVersionSettings["edit"]>;
  readonly get: BaseScriptAndVersionSettings["get"];
}

export interface OpenComputeWorkersScriptsSecretsNode {
  readonly bulkUpdate: BaseSecrets["bulkUpdate"];
  readonly delete: BaseSecrets["delete"];
  readonly get: BaseSecrets["get"];
  readonly list: BaseSecrets["list"];
  readonly update: BaseSecrets["update"];
}

export interface OpenComputeWorkersScriptsSettingsNode {
  readonly edit: BaseSettings["edit"];
  readonly get: BaseSettings["get"];
}

export interface OpenComputeWorkersScriptsSubdomainNode {
  readonly create: BaseSubdomain["create"];
  readonly delete: BaseSubdomain["delete"];
  readonly get: BaseSubdomain["get"];
}

export interface OpenComputeWorkersScriptsTailNode {
  readonly create: BaseTail["create"];
  readonly delete: BaseTail["delete"];
  readonly get: BaseTail["get"];
}

export interface OpenComputeWorkersScriptsVersionsNode {
  readonly create: (
    scriptName: string,
    params: OpenComputeWorkerVersionCreateParams,
    options?: OpenComputeRequestOptions,
  ) => ReturnType<BaseVersions2["create"]>;
  readonly get: BaseVersions2["get"];
  readonly list: BaseVersions2["list"];
}

export interface OpenComputeWorkersSubdomainsNode {
  readonly get: BaseSubdomains["get"];
}

export interface OpenComputeWorkflowsNode {
  readonly instances: OpenComputeWorkflowsInstancesNode;
  readonly versions: OpenComputeWorkflowsVersionsNode;
  readonly delete: BaseWorkflows["delete"];
  readonly get: BaseWorkflows["get"];
  readonly list: BaseWorkflows["list"];
  readonly update: BaseWorkflows["update"];
}

export interface OpenComputeWorkflowsInstancesNode {
  readonly events: OpenComputeWorkflowsInstancesEventsNode;
  readonly status: OpenComputeWorkflowsInstancesStatusNode;
  readonly bulk: BaseInstances2["bulk"];
  readonly create: BaseInstances2["create"];
  readonly get: BaseInstances2["get"];
  readonly list: BaseInstances2["list"];
}

export interface OpenComputeWorkflowsInstancesEventsNode {
  readonly create: BaseEvents["create"];
}

export interface OpenComputeWorkflowsInstancesStatusNode {
  readonly edit: BaseStatus["edit"];
}

export interface OpenComputeWorkflowsVersionsNode {
  readonly get: BaseVersions3["get"];
  readonly list: BaseVersions3["list"];
}

export interface OpenComputeVendorBackupsD1Node {
  readonly create: (
    accountId: string,
    databaseId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<Backup>;
  readonly list: (
    accountId: string,
    databaseId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<readonly Backup[]>;
  readonly restore: (
    accountId: string,
    backupId: string,
    body: RestoreRequest,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<RestoredResource>;
}

export interface OpenComputeVendorBackupsKvNode {
  readonly create: (
    accountId: string,
    namespaceId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<Backup>;
  readonly list: (
    accountId: string,
    namespaceId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<readonly Backup[]>;
  readonly restore: (
    accountId: string,
    backupId: string,
    body: RestoreRequest,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<RestoredResource>;
}

export interface OpenComputeVendorBackupsNode {
  readonly d1: OpenComputeVendorBackupsD1Node;
  readonly kv: OpenComputeVendorBackupsKvNode;
}

export interface OpenComputeVendorCacheNode {
  readonly collectGarbage: (
    options?: OpenComputeRequestOptions,
  ) => APIPromise<CacheStatus>;
  readonly collectGarbageForAccount: (
    accountId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<CacheStatus>;
  readonly get: (
    options?: OpenComputeRequestOptions,
  ) => APIPromise<CacheStatus>;
  readonly getForAccount: (
    accountId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<CacheStatus>;
}

export interface OpenComputeVendorCapabilitiesNode {
  readonly get: (
    options?: OpenComputeRequestOptions,
  ) => APIPromise<Capabilities>;
  readonly getForAccount: (
    accountId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<Capabilities>;
}

export interface OpenComputeVendorD1MigrationsNode {
  readonly apply: (
    accountId: string,
    databaseId: string,
    body: D1MigrationRequest,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<readonly D1Migration[]>;
  readonly list: (
    accountId: string,
    databaseId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<readonly D1Migration[]>;
}

export interface OpenComputeVendorD1TimeTravelNode {
  readonly checkpoints: (
    accountId: string,
    databaseId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<D1CheckpointTimes>;
}

export interface OpenComputeVendorD1Node {
  readonly migrations: OpenComputeVendorD1MigrationsNode;
  readonly rename: (
    accountId: string,
    databaseId: string,
    body: D1RenameRequest,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<D1RenameResult>;
  readonly timeTravel: OpenComputeVendorD1TimeTravelNode;
}

export interface OpenComputeVendorDurableObjectsNode {
  readonly list: (
    accountId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<DurableObjectNamespacePage>;
  readonly objects: (
    accountId: string,
    namespaceId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<DurableObjectRecordPage>;
}

export interface OpenComputeVendorImagesNode {
  readonly capacity: (
    options?: OpenComputeRequestOptions,
  ) => APIPromise<ImageCapacity>;
  readonly capacityForAccount: (
    accountId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<ImageCapacity>;
}

export interface OpenComputeVendorQueuesNode {
  readonly consumerRuntime: (
    accountId: string,
    queueId: string,
    consumerId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<QueueConsumerRuntime>;
}

export interface OpenComputeVendorR2MultipartNode {
  readonly abort: (
    accountId: string,
    bucketName: string,
    uploadId: string,
    objectKey: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<null>;
  readonly complete: (
    accountId: string,
    bucketName: string,
    uploadId: string,
    objectKey: string,
    body: R2MultipartCompleteRequest,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<R2MultipartCompletedObject>;
  readonly create: (
    accountId: string,
    bucketName: string,
    body: R2MultipartCreateRequest,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<R2MultipartCreate>;
  readonly uploadPart: (
    accountId: string,
    bucketName: string,
    uploadId: string,
    partNumber: string,
    objectKey: string,
    body: OpenComputeBinaryBody,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<R2MultipartPart>;
}

export interface OpenComputeVendorR2UsageNode {
  readonly get: (
    accountId: string,
    bucketName: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<R2BucketUsage>;
}

export interface OpenComputeVendorR2Node {
  readonly multipart: OpenComputeVendorR2MultipartNode;
  readonly usage: OpenComputeVendorR2UsageNode;
}

export interface OpenComputeVendorSchedulerNode {
  readonly get: (
    options?: OpenComputeRequestOptions,
  ) => APIPromise<SchedulerStatus>;
  readonly getForAccount: (
    accountId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<SchedulerStatus>;
  readonly pause: (
    options?: OpenComputeRequestOptions,
  ) => APIPromise<SchedulerStatus>;
  readonly pauseForAccount: (
    accountId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<SchedulerStatus>;
  readonly repair: (
    options?: OpenComputeRequestOptions,
  ) => APIPromise<SchedulerStatus>;
  readonly repairForAccount: (
    accountId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<SchedulerStatus>;
  readonly resume: (
    options?: OpenComputeRequestOptions,
  ) => APIPromise<SchedulerStatus>;
  readonly resumeForAccount: (
    accountId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<SchedulerStatus>;
}

export interface OpenComputeVendorSystemNode {
  readonly status: (
    options?: OpenComputeRequestOptions,
  ) => APIPromise<SystemStatus>;
  readonly statusForAccount: (
    accountId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<SystemStatus>;
}

export interface OpenComputeVendorUpgradeNode {
  readonly check: (
    options?: OpenComputeRequestOptions,
  ) => APIPromise<UpgradeCheck>;
  readonly checkForAccount: (
    accountId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<UpgradeCheck>;
}

export interface OpenComputeVendorWorkersObservabilityNode {
  readonly usage: (
    accountId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<ObservabilityUsage>;
}

export interface OpenComputeVendorWorkersPublicOriginNode {
  readonly delete: (
    accountId: string,
    scriptName: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<null>;
  readonly get: (
    accountId: string,
    scriptName: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<{
    readonly name: string;
    readonly url: string;
  } | null>;
  readonly set: (
    accountId: string,
    scriptName: string,
    body: PublicOriginRequest,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<WorkerEndpoint>;
}

export interface OpenComputeVendorWorkersNode {
  readonly endpoints: (
    accountId: string,
    scriptName: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<readonly WorkerEndpoint[]>;
  readonly observability: OpenComputeVendorWorkersObservabilityNode;
  readonly publicOrigin: OpenComputeVendorWorkersPublicOriginNode;
  readonly queueConsumers: (
    accountId: string,
    scriptName: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<readonly QueueConsumer[]>;
  readonly serviceMetadata: (
    accountId: string,
    scriptName: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<WorkerServiceMetadata>;
}

export interface OpenComputeVendorWorkflowsNode {
  readonly settings: (
    accountId: string,
    options?: OpenComputeRequestOptions,
  ) => APIPromise<WorkflowSettings>;
}

export interface OpenComputeVendorNode {
  readonly backups: OpenComputeVendorBackupsNode;
  readonly cache: OpenComputeVendorCacheNode;
  readonly capabilities: OpenComputeVendorCapabilitiesNode;
  readonly d1: OpenComputeVendorD1Node;
  readonly durableObjects: OpenComputeVendorDurableObjectsNode;
  readonly images: OpenComputeVendorImagesNode;
  readonly queues: OpenComputeVendorQueuesNode;
  readonly r2: OpenComputeVendorR2Node;
  readonly scheduler: OpenComputeVendorSchedulerNode;
  readonly system: OpenComputeVendorSystemNode;
  readonly upgrade: OpenComputeVendorUpgradeNode;
  readonly workers: OpenComputeVendorWorkersNode;
  readonly workflows: OpenComputeVendorWorkflowsNode;
}

/**
 * The closed capability-scoped surface: every selected official operation,
 * the vendor namespace, and nothing else.
 */
export interface OpenComputeSurface {
  readonly accounts: OpenComputeAccountsNode;
  readonly aiSearch: OpenComputeAiSearchNode;
  readonly d1: OpenComputeD1Node;
  readonly kv: OpenComputeKvNode;
  readonly memberships: OpenComputeMembershipsNode;
  readonly queues: OpenComputeQueuesNode;
  readonly r2: OpenComputeR2Node;
  readonly user: OpenComputeUserNode;
  readonly vectorize: OpenComputeVectorizeNode;
  readonly workers: OpenComputeWorkersNode;
  readonly workflows: OpenComputeWorkflowsNode;
  readonly artifacts: Artifacts;
  readonly openCompute: OpenComputeVendorNode;
}

/**
 * Build the closed capability-scoped surface over one hidden official
 * transport. The returned object exposes exactly the selected operations and
 * nothing else; AI Search browser folder uploads preserve the original path.
 */
export function buildFacade(transport: BaseCloudflare): OpenComputeSurface {
  const accounts = new BaseAccounts(transport);
  const aiSearchnamespaces = new BaseNamespaces(transport);
  const aiSearchnamespacesinstances = new BaseInstances(transport);
  const aiSearchnamespacesinstancesitems = new BaseItems(transport);
  const aiSearchnamespacesinstancesjobs = new BaseJobs(transport);
  const aiSearchtokens = new BaseTokens(transport);
  const d1database = new BaseDatabase(transport);
  const d1databasetimeTravel = new BaseTimeTravel(transport);
  const kvnamespaces = new BaseNamespaces2(transport);
  const kvnamespaceskeys = new BaseKeys(transport);
  const kvnamespacesmetadata = new BaseMetadata(transport);
  const kvnamespacesvalues = new BaseValues(transport);
  const memberships = new BaseMemberships(transport);
  const queues = new BaseQueues(transport);
  const queuesconsumers = new BaseConsumers(transport);
  const queuesmessages = new BaseMessages(transport);
  const r2buckets = new BaseBuckets(transport);
  const r2bucketsobjects = new BaseObjects(transport);
  const user = new BaseUser(transport);
  const usertokens = new BaseTokens2(transport);
  const vectorizeindexes = new BaseIndexes(transport);
  const vectorizeindexesmetadataIndex = new BaseMetadataIndex(transport);
  const workersassetsupload = new BaseUpload(transport);
  const workersbetaworkers = new BaseWorkers(transport);
  const workersbetaworkersversions = new BaseVersions(transport);
  const workersobservabilitytelemetry = new BaseTelemetry(transport);
  const workersscripts = new BaseScripts(transport);
  const workersscriptsassetsupload = new BaseUpload2(transport);
  const workersscriptsdeployments = new BaseDeployments(transport);
  const workersscriptsschedules = new BaseSchedules(transport);
  const workersscriptsscriptAndVersionSettings =
    new BaseScriptAndVersionSettings(transport);
  const workersscriptssecrets = new BaseSecrets(transport);
  const workersscriptssettings = new BaseSettings(transport);
  const workersscriptssubdomain = new BaseSubdomain(transport);
  const workersscriptstail = new BaseTail(transport);
  const workersscriptsversions = new BaseVersions2(transport);
  const workerssubdomains = new BaseSubdomains(transport);
  const workflows = new BaseWorkflows(transport);
  const workflowsinstances = new BaseInstances2(transport);
  const workflowsinstancesevents = new BaseEvents(transport);
  const workflowsinstancesstatus = new BaseStatus(transport);
  const workflowsversions = new BaseVersions3(transport);
  return {
    accounts: {
      get: accounts.get.bind(accounts),
      list: accounts.list.bind(accounts),
    },
    aiSearch: {
      namespaces: {
        instances: {
          items: {
            chunks: aiSearchnamespacesinstancesitems.chunks.bind(
              aiSearchnamespacesinstancesitems,
            ),
            createOrUpdate:
              aiSearchnamespacesinstancesitems.createOrUpdate.bind(
                aiSearchnamespacesinstancesitems,
              ),
            delete: aiSearchnamespacesinstancesitems.delete.bind(
              aiSearchnamespacesinstancesitems,
            ),
            download: aiSearchnamespacesinstancesitems.download.bind(
              aiSearchnamespacesinstancesitems,
            ),
            get: aiSearchnamespacesinstancesitems.get.bind(
              aiSearchnamespacesinstancesitems,
            ),
            list: aiSearchnamespacesinstancesitems.list.bind(
              aiSearchnamespacesinstancesitems,
            ),
            logs: aiSearchnamespacesinstancesitems.logs.bind(
              aiSearchnamespacesinstancesitems,
            ),
            sync: aiSearchnamespacesinstancesitems.sync.bind(
              aiSearchnamespacesinstancesitems,
            ),
            upload: (id, params, options) =>
              uploadAiSearchItem(
                transport,
                aiSearchnamespacesinstancesitems,
                id,
                params,
                options,
              ),
          },
          jobs: {
            create: aiSearchnamespacesinstancesjobs.create.bind(
              aiSearchnamespacesinstancesjobs,
            ),
            get: aiSearchnamespacesinstancesjobs.get.bind(
              aiSearchnamespacesinstancesjobs,
            ),
            list: aiSearchnamespacesinstancesjobs.list.bind(
              aiSearchnamespacesinstancesjobs,
            ),
            logs: aiSearchnamespacesinstancesjobs.logs.bind(
              aiSearchnamespacesinstancesjobs,
            ),
            update: aiSearchnamespacesinstancesjobs.update.bind(
              aiSearchnamespacesinstancesjobs,
            ),
          },
          chatCompletions: aiSearchnamespacesinstances.chatCompletions.bind(
            aiSearchnamespacesinstances,
          ),
          create: aiSearchnamespacesinstances.create.bind(
            aiSearchnamespacesinstances,
          ),
          delete: aiSearchnamespacesinstances.delete.bind(
            aiSearchnamespacesinstances,
          ),
          list: aiSearchnamespacesinstances.list.bind(
            aiSearchnamespacesinstances,
          ),
          read: aiSearchnamespacesinstances.read.bind(
            aiSearchnamespacesinstances,
          ),
          search: aiSearchnamespacesinstances.search.bind(
            aiSearchnamespacesinstances,
          ),
          stats: aiSearchnamespacesinstances.stats.bind(
            aiSearchnamespacesinstances,
          ),
          update: aiSearchnamespacesinstances.update.bind(
            aiSearchnamespacesinstances,
          ),
        },
        chatCompletions:
          aiSearchnamespaces.chatCompletions.bind(aiSearchnamespaces),
        create: aiSearchnamespaces.create.bind(aiSearchnamespaces),
        delete: aiSearchnamespaces.delete.bind(aiSearchnamespaces),
        list: aiSearchnamespaces.list.bind(aiSearchnamespaces),
        read: aiSearchnamespaces.read.bind(aiSearchnamespaces),
        search: aiSearchnamespaces.search.bind(aiSearchnamespaces),
        update: aiSearchnamespaces.update.bind(aiSearchnamespaces),
      },
      tokens: {
        list: aiSearchtokens.list.bind(aiSearchtokens),
      },
    },
    d1: {
      database: {
        timeTravel: {
          getBookmark:
            d1databasetimeTravel.getBookmark.bind(d1databasetimeTravel),
          restore: d1databasetimeTravel.restore.bind(d1databasetimeTravel),
        },
        create: d1database.create.bind(d1database),
        delete: d1database.delete.bind(d1database),
        edit: d1database.edit.bind(d1database),
        export: d1database.export.bind(d1database),
        get: d1database.get.bind(d1database),
        import: d1database.import.bind(d1database),
        list: d1database.list.bind(d1database),
        query: d1database.query.bind(d1database),
        raw: d1database.raw.bind(d1database),
        update: d1database.update.bind(d1database),
      },
    },
    kv: {
      namespaces: {
        keys: {
          list: kvnamespaceskeys.list.bind(kvnamespaceskeys),
        },
        metadata: {
          get: kvnamespacesmetadata.get.bind(kvnamespacesmetadata),
        },
        values: {
          delete: kvnamespacesvalues.delete.bind(kvnamespacesvalues),
          get: kvnamespacesvalues.get.bind(kvnamespacesvalues),
          update: kvnamespacesvalues.update.bind(kvnamespacesvalues),
        },
        bulkDelete: kvnamespaces.bulkDelete.bind(kvnamespaces),
        bulkGet: kvnamespaces.bulkGet.bind(kvnamespaces),
        bulkUpdate: kvnamespaces.bulkUpdate.bind(kvnamespaces),
        create: kvnamespaces.create.bind(kvnamespaces),
        delete: kvnamespaces.delete.bind(kvnamespaces),
        get: kvnamespaces.get.bind(kvnamespaces),
        list: kvnamespaces.list.bind(kvnamespaces),
        update: kvnamespaces.update.bind(kvnamespaces),
      },
    },
    memberships: {
      list: memberships.list.bind(memberships),
    },
    queues: {
      consumers: {
        create: queuesconsumers.create.bind(queuesconsumers),
        delete: queuesconsumers.delete.bind(queuesconsumers),
        get: queuesconsumers.get.bind(queuesconsumers),
        list: queuesconsumers.list.bind(queuesconsumers),
        update: queuesconsumers.update.bind(queuesconsumers),
      },
      messages: {
        bulkPush: queuesmessages.bulkPush.bind(queuesmessages),
        push: queuesmessages.push.bind(queuesmessages),
      },
      create: queues.create.bind(queues),
      delete: queues.delete.bind(queues),
      get: queues.get.bind(queues),
      getMetrics: queues.getMetrics.bind(queues),
      list: queues.list.bind(queues),
      update: queues.update.bind(queues),
    },
    r2: {
      buckets: {
        objects: {
          delete: r2bucketsobjects.delete.bind(r2bucketsobjects),
          get: r2bucketsobjects.get.bind(r2bucketsobjects),
          list: r2bucketsobjects.list.bind(r2bucketsobjects),
          upload: r2bucketsobjects.upload.bind(r2bucketsobjects),
        },
        create: r2buckets.create.bind(r2buckets),
        delete: r2buckets.delete.bind(r2buckets),
        get: r2buckets.get.bind(r2buckets),
        list: r2buckets.list.bind(r2buckets),
      },
    },
    user: {
      tokens: {
        verify: usertokens.verify.bind(usertokens),
      },
      get: user.get.bind(user),
    },
    vectorize: {
      indexes: {
        metadataIndex: {
          create: vectorizeindexesmetadataIndex.create.bind(
            vectorizeindexesmetadataIndex,
          ),
          delete: vectorizeindexesmetadataIndex.delete.bind(
            vectorizeindexesmetadataIndex,
          ),
          list: vectorizeindexesmetadataIndex.list.bind(
            vectorizeindexesmetadataIndex,
          ),
        },
        create: vectorizeindexes.create.bind(vectorizeindexes),
        delete: vectorizeindexes.delete.bind(vectorizeindexes),
        deleteByIDs: vectorizeindexes.deleteByIDs.bind(vectorizeindexes),
        get: vectorizeindexes.get.bind(vectorizeindexes),
        getByIDs: vectorizeindexes.getByIDs.bind(vectorizeindexes),
        info: vectorizeindexes.info.bind(vectorizeindexes),
        insert: vectorizeindexes.insert.bind(vectorizeindexes),
        list: vectorizeindexes.list.bind(vectorizeindexes),
        listVectors: vectorizeindexes.listVectors.bind(vectorizeindexes),
        query: vectorizeindexes.query.bind(vectorizeindexes),
        upsert: vectorizeindexes.upsert.bind(vectorizeindexes),
      },
    },
    workers: {
      assets: {
        upload: {
          create: (params, options) =>
            workersassetsupload.create(params as UploadCreateParams, options),
        },
      },
      beta: {
        workers: {
          versions: {
            delete: workersbetaworkersversions.delete.bind(
              workersbetaworkersversions,
            ),
          },
          get: workersbetaworkers.get.bind(workersbetaworkers),
        },
      },
      observability: {
        telemetry: {
          keys: workersobservabilitytelemetry.keys.bind(
            workersobservabilitytelemetry,
          ),
          liveTail: workersobservabilitytelemetry.liveTail.bind(
            workersobservabilitytelemetry,
          ),
          liveTailHeartbeat:
            workersobservabilitytelemetry.liveTailHeartbeat.bind(
              workersobservabilitytelemetry,
            ),
          query: workersobservabilitytelemetry.query.bind(
            workersobservabilitytelemetry,
          ),
          values: workersobservabilitytelemetry.values.bind(
            workersobservabilitytelemetry,
          ),
        },
      },
      scripts: {
        assets: {
          upload: {
            create: workersscriptsassetsupload.create.bind(
              workersscriptsassetsupload,
            ),
          },
        },
        deployments: {
          create: workersscriptsdeployments.create.bind(
            workersscriptsdeployments,
          ),
          delete: workersscriptsdeployments.delete.bind(
            workersscriptsdeployments,
          ),
          get: workersscriptsdeployments.get.bind(workersscriptsdeployments),
          list: workersscriptsdeployments.list.bind(workersscriptsdeployments),
        },
        schedules: {
          get: workersscriptsschedules.get.bind(workersscriptsschedules),
          update: workersscriptsschedules.update.bind(workersscriptsschedules),
        },
        scriptAndVersionSettings: {
          edit: (scriptName, params, options) =>
            editWorkerSettings(transport, scriptName, params, options),
          get: workersscriptsscriptAndVersionSettings.get.bind(
            workersscriptsscriptAndVersionSettings,
          ),
        },
        secrets: {
          bulkUpdate: workersscriptssecrets.bulkUpdate.bind(
            workersscriptssecrets,
          ),
          delete: workersscriptssecrets.delete.bind(workersscriptssecrets),
          get: workersscriptssecrets.get.bind(workersscriptssecrets),
          list: workersscriptssecrets.list.bind(workersscriptssecrets),
          update: workersscriptssecrets.update.bind(workersscriptssecrets),
        },
        settings: {
          edit: workersscriptssettings.edit.bind(workersscriptssettings),
          get: workersscriptssettings.get.bind(workersscriptssettings),
        },
        subdomain: {
          create: workersscriptssubdomain.create.bind(workersscriptssubdomain),
          delete: workersscriptssubdomain.delete.bind(workersscriptssubdomain),
          get: workersscriptssubdomain.get.bind(workersscriptssubdomain),
        },
        tail: {
          create: workersscriptstail.create.bind(workersscriptstail),
          delete: workersscriptstail.delete.bind(workersscriptstail),
          get: workersscriptstail.get.bind(workersscriptstail),
        },
        versions: {
          create: (scriptName, params, options) =>
            workerUpload(transport, "POST", scriptName, params, options),
          get: workersscriptsversions.get.bind(workersscriptsversions),
          list: workersscriptsversions.list.bind(workersscriptsversions),
        },
        delete: workersscripts.delete.bind(workersscripts),
        get: workersscripts.get.bind(workersscripts),
        list: workersscripts.list.bind(workersscripts),
        update: (scriptName, params, options) =>
          workerUpload(transport, "PUT", scriptName, params, options),
      },
      subdomains: {
        get: workerssubdomains.get.bind(workerssubdomains),
      },
    },
    workflows: {
      instances: {
        events: {
          create: workflowsinstancesevents.create.bind(
            workflowsinstancesevents,
          ),
        },
        status: {
          edit: workflowsinstancesstatus.edit.bind(workflowsinstancesstatus),
        },
        bulk: workflowsinstances.bulk.bind(workflowsinstances),
        create: workflowsinstances.create.bind(workflowsinstances),
        get: workflowsinstances.get.bind(workflowsinstances),
        list: workflowsinstances.list.bind(workflowsinstances),
      },
      versions: {
        get: workflowsversions.get.bind(workflowsversions),
        list: workflowsversions.list.bind(workflowsversions),
      },
      delete: workflows.delete.bind(workflows),
      get: workflows.get.bind(workflows),
      list: workflows.list.bind(workflows),
      update: workflows.update.bind(workflows),
    },
    artifacts: new Artifacts(transport),
    openCompute: buildOpenCompute(transport),
  };
}

export type {
  Account,
  AccountGetParams,
  AccountListParams,
  AccountsV4PagePaginationArray,
} from "cloudflare/resources/accounts/accounts";
export type {
  InstanceCreateParams as AisearchNamespacesInstancesInstancesInstanceCreateParams,
  InstanceCreateResponse as AisearchNamespacesInstancesInstancesInstanceCreateResponse,
  InstanceListParams as AisearchNamespacesInstancesInstancesInstanceListParams,
  InstanceListResponse as AisearchNamespacesInstancesInstancesInstanceListResponse,
  InstanceListResponsesV4PagePaginationArray as AisearchNamespacesInstancesInstancesInstanceListResponsesV4PagePaginationArray,
  InstanceChatCompletionsParams,
  InstanceChatCompletionsResponse,
  InstanceDeleteParams,
  InstanceDeleteResponse,
  InstanceReadParams,
  InstanceReadResponse,
  InstanceSearchParams,
  InstanceSearchResponse,
  InstanceStatsParams,
  InstanceStatsResponse,
  InstanceUpdateParams,
  InstanceUpdateResponse,
} from "cloudflare/resources/aisearch/namespaces/instances/instances";
export type {
  ItemChunksParams,
  ItemChunksResponse,
  ItemCreateOrUpdateParams,
  ItemCreateOrUpdateResponse,
  ItemDeleteParams,
  ItemDeleteResponse,
  ItemDownloadParams,
  ItemGetParams,
  ItemGetResponse,
  ItemListParams,
  ItemListResponse,
  ItemListResponsesV4PagePaginationArray,
  ItemLogsParams,
  ItemLogsResponse,
  ItemSyncParams,
  ItemSyncResponse,
  ItemUploadParams,
  ItemUploadResponse,
} from "cloudflare/resources/aisearch/namespaces/instances/items";
export type {
  JobCreateParams,
  JobCreateResponse,
  JobGetParams,
  JobGetResponse,
  JobListParams,
  JobListResponse,
  JobListResponsesV4PagePaginationArray,
  JobLogsParams,
  JobLogsResponse,
  JobUpdateParams,
  JobUpdateResponse,
} from "cloudflare/resources/aisearch/namespaces/instances/jobs";
export type {
  NamespaceCreateParams as AisearchNamespacesNamespacesNamespaceCreateParams,
  NamespaceDeleteParams as AisearchNamespacesNamespacesNamespaceDeleteParams,
  NamespaceDeleteResponse as AisearchNamespacesNamespacesNamespaceDeleteResponse,
  NamespaceListParams as AisearchNamespacesNamespacesNamespaceListParams,
  NamespaceUpdateParams as AisearchNamespacesNamespacesNamespaceUpdateParams,
  NamespaceChatCompletionsParams,
  NamespaceChatCompletionsResponse,
  NamespaceCreateResponse,
  NamespaceListResponse,
  NamespaceListResponsesV4PagePaginationArray,
  NamespaceReadParams,
  NamespaceReadResponse,
  NamespaceSearchParams,
  NamespaceSearchResponse,
  NamespaceUpdateResponse,
} from "cloudflare/resources/aisearch/namespaces/namespaces";
export type {
  TokenListParams,
  TokenListResponse,
  TokenListResponsesV4PagePaginationArray,
} from "cloudflare/resources/aisearch/tokens";
export type {
  DatabaseCreateParams,
  DatabaseDeleteParams,
  DatabaseDeleteResponse,
  DatabaseEditParams,
  DatabaseExportParams,
  DatabaseExportResponse,
  DatabaseGetParams,
  DatabaseImportParams,
  DatabaseImportResponse,
  DatabaseListParams,
  DatabaseListResponse,
  DatabaseListResponsesV4PagePaginationArray,
  DatabaseQueryParams,
  DatabaseRawParams,
  DatabaseRawResponse,
  DatabaseRawResponsesSinglePage,
  DatabaseUpdateParams,
  QueryResult,
  QueryResultsSinglePage,
} from "cloudflare/resources/d1/database/database";
export type {
  TimeTravelGetBookmarkParams,
  TimeTravelGetBookmarkResponse,
  TimeTravelRestoreParams,
  TimeTravelRestoreResponse,
} from "cloudflare/resources/d1/database/time-travel";
export type {
  Key,
  KeyListParams,
  KeysCursorLimitPagination,
} from "cloudflare/resources/kv/namespaces/keys";
export type {
  MetadataGetParams,
  MetadataGetResponse,
} from "cloudflare/resources/kv/namespaces/metadata";
export type {
  NamespaceCreateParams as KvNamespacesNamespacesNamespaceCreateParams,
  NamespaceDeleteParams as KvNamespacesNamespacesNamespaceDeleteParams,
  NamespaceDeleteResponse as KvNamespacesNamespacesNamespaceDeleteResponse,
  NamespaceListParams as KvNamespacesNamespacesNamespaceListParams,
  NamespaceUpdateParams as KvNamespacesNamespacesNamespaceUpdateParams,
  Namespace,
  NamespaceBulkDeleteParams,
  NamespaceBulkDeleteResponse,
  NamespaceBulkGetParams,
  NamespaceBulkGetResponse,
  NamespaceBulkUpdateParams,
  NamespaceBulkUpdateResponse,
  NamespaceGetParams,
  NamespacesV4PagePaginationArray,
} from "cloudflare/resources/kv/namespaces/namespaces";
export type {
  ValueDeleteParams,
  ValueDeleteResponse,
  ValueGetParams,
  ValueUpdateParams,
  ValueUpdateResponse,
} from "cloudflare/resources/kv/namespaces/values";
export type {
  Membership,
  MembershipListParams,
  MembershipsV4PagePaginationArray,
} from "cloudflare/resources/memberships/memberships";
export type {
  Consumer,
  ConsumerCreateParams,
  ConsumerDeleteParams,
  ConsumerDeleteResponse,
  ConsumerGetParams,
  ConsumerListParams,
  ConsumersSinglePage,
  ConsumerUpdateParams,
} from "cloudflare/resources/queues/consumers";
export type {
  MessageBulkPushParams,
  MessageBulkPushResponse,
  MessagePushParams,
  MessagePushResponse,
} from "cloudflare/resources/queues/messages";
export type {
  Queue,
  QueueCreateParams,
  QueueDeleteParams,
  QueueDeleteResponse,
  QueueGetMetricsParams,
  QueueGetMetricsResponse,
  QueueGetParams,
  QueueListParams,
  QueuesSinglePage,
  QueueUpdateParams,
} from "cloudflare/resources/queues/queues";
export type {
  Bucket,
  BucketCreateParams,
  BucketDeleteParams,
  BucketDeleteResponse,
  BucketGetParams,
  BucketListParams,
  BucketListResponse,
} from "cloudflare/resources/r2/buckets/buckets";
export type {
  ObjectDeleteParams,
  ObjectDeleteResponse,
  ObjectGetParams,
  ObjectListParams,
  ObjectListResponse,
  ObjectListResponsesCursorPagination,
  ObjectUploadParams,
  ObjectUploadResponse,
} from "cloudflare/resources/r2/buckets/objects";
export type { TokenVerifyResponse } from "cloudflare/resources/user/tokens/tokens";
export type { UserGetResponse } from "cloudflare/resources/user/user";
export type {
  CreateIndex,
  CreateIndicesSinglePage,
  IndexCreateParams,
  IndexDeleteByIDsParams,
  IndexDeleteByIDsResponse,
  IndexDeleteParams,
  IndexDeleteResponse,
  IndexDimensionConfiguration,
  IndexDimensionConfigurationParam,
  IndexGetByIDsParams,
  IndexGetByIDsResponse,
  IndexGetParams,
  IndexInfoParams,
  IndexInfoResponse,
  IndexInsertParams,
  IndexInsertResponse,
  IndexListParams,
  IndexListVectorsParams,
  IndexListVectorsResponse,
  IndexQueryParams,
  IndexQueryResponse,
  IndexUpsertParams,
  IndexUpsertResponse,
} from "cloudflare/resources/vectorize/indexes/indexes";
export type {
  MetadataIndexCreateParams,
  MetadataIndexCreateResponse,
  MetadataIndexDeleteParams,
  MetadataIndexDeleteResponse,
  MetadataIndexListParams,
  MetadataIndexListResponse,
} from "cloudflare/resources/vectorize/indexes/metadata-index";
export type {
  UploadCreateParams as WorkersAssetsUploadUploadCreateParams,
  UploadCreateResponse as WorkersAssetsUploadUploadCreateResponse,
} from "cloudflare/resources/workers/assets/upload";
export type {
  VersionDeleteParams,
  VersionDeleteResponse,
} from "cloudflare/resources/workers/beta/workers/versions";
export type {
  Worker,
  WorkerGetParams,
} from "cloudflare/resources/workers/beta/workers/workers";
export type {
  TelemetryKeysParams,
  TelemetryKeysResponse,
  TelemetryKeysResponsesSinglePage,
  TelemetryLiveTailHeartbeatParams,
  TelemetryLiveTailHeartbeatResponse,
  TelemetryLiveTailParams,
  TelemetryLiveTailResponse,
  TelemetryQueryParams,
  TelemetryQueryResponse,
  TelemetryValuesParams,
  TelemetryValuesResponse,
  TelemetryValuesResponsesSinglePage,
} from "cloudflare/resources/workers/observability/telemetry";
export type {
  UploadCreateParams as WorkersScriptsAssetsUploadUploadCreateParams,
  UploadCreateResponse as WorkersScriptsAssetsUploadUploadCreateResponse,
} from "cloudflare/resources/workers/scripts/assets/upload";
export type {
  Deployment,
  DeploymentCreateParams,
  DeploymentDeleteParams,
  DeploymentDeleteResponse,
  DeploymentGetParams,
  DeploymentListParams,
  DeploymentListResponse,
} from "cloudflare/resources/workers/scripts/deployments";
export type {
  ScheduleGetParams,
  ScheduleGetResponse,
  ScheduleUpdateParams,
  ScheduleUpdateResponse,
} from "cloudflare/resources/workers/scripts/schedules";
export type {
  ScriptAndVersionSettingEditParams,
  ScriptAndVersionSettingEditResponse,
  ScriptAndVersionSettingGetParams,
  ScriptAndVersionSettingGetResponse,
} from "cloudflare/resources/workers/scripts/script-and-version-settings";
export type {
  ScriptDeleteParams,
  ScriptDeleteResponse,
  ScriptGetParams,
  ScriptListParams,
  ScriptListResponse,
  ScriptListResponsesSinglePage,
  ScriptUpdateParams,
  ScriptUpdateResponse,
} from "cloudflare/resources/workers/scripts/scripts";
export type {
  SecretBulkUpdateParams,
  SecretBulkUpdateResponse,
  SecretDeleteParams,
  SecretDeleteResponse,
  SecretGetParams,
  SecretGetResponse,
  SecretListParams,
  SecretListResponse,
  SecretListResponsesSinglePage,
  SecretUpdateParams,
  SecretUpdateResponse,
} from "cloudflare/resources/workers/scripts/secrets";
export type {
  SettingEditParams,
  SettingGetParams,
} from "cloudflare/resources/workers/scripts/settings";
export type {
  SubdomainCreateParams,
  SubdomainCreateResponse,
  SubdomainDeleteParams,
  SubdomainDeleteResponse,
  SubdomainGetParams as WorkersScriptsSubdomainSubdomainGetParams,
  SubdomainGetResponse as WorkersScriptsSubdomainSubdomainGetResponse,
} from "cloudflare/resources/workers/scripts/subdomain";
export type {
  TailCreateParams,
  TailCreateResponse,
  TailDeleteParams,
  TailDeleteResponse,
  TailGetParams,
  TailGetResponse,
} from "cloudflare/resources/workers/scripts/tail";
export type {
  VersionCreateParams,
  VersionCreateResponse,
  VersionListResponsesV4PagePagination,
  VersionGetParams as WorkersScriptsVersionsVersionGetParams,
  VersionGetResponse as WorkersScriptsVersionsVersionGetResponse,
  VersionListParams as WorkersScriptsVersionsVersionListParams,
  VersionListResponse as WorkersScriptsVersionsVersionListResponse,
} from "cloudflare/resources/workers/scripts/versions";
export type {
  SubdomainGetParams as WorkersSubdomainsSubdomainGetParams,
  SubdomainGetResponse as WorkersSubdomainsSubdomainGetResponse,
} from "cloudflare/resources/workers/subdomains";
export type {
  EventCreateParams,
  EventCreateResponse,
} from "cloudflare/resources/workflows/instances/events";
export type {
  InstanceBulkParams,
  InstanceBulkResponse,
  InstanceBulkResponsesSinglePage,
  InstanceGetParams,
  InstanceGetResponse,
  InstanceCreateParams as WorkflowsInstancesInstancesInstanceCreateParams,
  InstanceCreateResponse as WorkflowsInstancesInstancesInstanceCreateResponse,
  InstanceListParams as WorkflowsInstancesInstancesInstanceListParams,
  InstanceListResponse as WorkflowsInstancesInstancesInstanceListResponse,
  InstanceListResponsesV4PagePaginationArray as WorkflowsInstancesInstancesInstanceListResponsesV4PagePaginationArray,
} from "cloudflare/resources/workflows/instances/instances";
export type {
  StatusEditParams,
  StatusEditResponse,
} from "cloudflare/resources/workflows/instances/status";
export type {
  VersionListResponsesV4PagePaginationArray,
  VersionGetParams as WorkflowsVersionsVersionGetParams,
  VersionGetResponse as WorkflowsVersionsVersionGetResponse,
  VersionListParams as WorkflowsVersionsVersionListParams,
  VersionListResponse as WorkflowsVersionsVersionListResponse,
} from "cloudflare/resources/workflows/versions";
export type {
  WorkflowDeleteParams,
  WorkflowDeleteResponse,
  WorkflowGetParams,
  WorkflowGetResponse,
  WorkflowListParams,
  WorkflowListResponse,
  WorkflowListResponsesV4PagePaginationArray,
  WorkflowUpdateParams,
  WorkflowUpdateResponse,
} from "cloudflare/resources/workflows/workflows";
