//! Backend-neutral object operations shared by every domain store.

use crate::client::{S3Backend, S3ObjectBody};
use crate::credentials::S3Credentials;
use crate::local::LocalBackend;
use bytes::{Bytes, BytesMut};
use futures::{Stream, StreamExt as _};
use open_compute_core::{
    LocalObjectStorageConfig, ObjectStorageKind, PlatformError, PlatformId, S3Config,
};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fs::File;
use std::os::unix::fs::{MetadataExt as _, OpenOptionsExt as _};
use std::path::Path;
use std::pin::Pin;
use std::task::{Context, Poll};
use tokio::io::{AsyncRead, ReadBuf};
use tokio::sync::mpsc;
use zeroize::{Zeroize, ZeroizeOnDrop};

/// Maximum canonical physical-key length admitted by the platform.
pub(crate) const OBJECT_KEY_MAX_BYTES: usize = 1024;

/// A validated backend physical key generated by a domain store.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(transparent)]
pub struct ObjectKey(String);

impl<'de> Deserialize<'de> for ObjectKey {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Self::new(value).map_err(serde::de::Error::custom)
    }
}

impl ObjectKey {
    /// Validate a canonical host-generated ASCII physical key.
    pub fn new(value: impl Into<String>) -> Result<Self, BackendError> {
        let value = value.into();
        if value.is_empty()
            || value.len() > OBJECT_KEY_MAX_BYTES
            || value.starts_with('/')
            || value.ends_with('/')
            || value.split('/').any(|segment| {
                segment.is_empty()
                    || segment == "."
                    || segment == ".."
                    || segment.len() > 255
                    || !segment.bytes().all(|byte| {
                        byte.is_ascii_alphanumeric()
                            || matches!(byte, b'-' | b'_' | b'.' | b'=' | b'+' | b'@')
                    })
            })
        {
            return Err(BackendError::InvalidKey);
        }
        Ok(Self(value))
    }

    /// Borrow the canonical key string.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Replayable bounded source for one object mutation.
pub enum ObjectSource {
    /// In-memory bytes.
    Bytes(Bytes),
    /// An already-opened regular file and its exact expected length.
    File {
        /// Already-opened regular file.
        file: File,
        /// Exact expected byte length.
        length: u64,
    },
}

impl std::fmt::Debug for ObjectSource {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Bytes(bytes) => formatter
                .debug_struct("ObjectSource::Bytes")
                .field("length", &bytes.len())
                .finish(),
            Self::File { length, .. } => formatter
                .debug_struct("ObjectSource::File")
                .field("length", length)
                .finish_non_exhaustive(),
        }
    }
}

impl ObjectSource {
    /// Exact source length.
    #[must_use]
    pub fn length(&self) -> u64 {
        match self {
            Self::Bytes(bytes) => bytes.len() as u64,
            Self::File { length, .. } => *length,
        }
    }

    fn validate(&self) -> Result<(), BackendError> {
        let Self::File { file, length } = self else {
            return Ok(());
        };
        let metadata = file.metadata().map_err(|_| BackendError::Unavailable)?;
        if !private_source_metadata(&metadata, *length) {
            return Err(BackendError::Corrupt);
        }
        Ok(())
    }
}

pub(crate) fn open_private_source(path: &Path, expected_length: u64) -> Result<File, BackendError> {
    let file = std::fs::OpenOptions::new()
        .read(true)
        .custom_flags(rustix::fs::OFlags::NOFOLLOW.bits() as i32)
        .open(path)
        .map_err(|_| BackendError::Unavailable)?;
    let metadata = file.metadata().map_err(|_| BackendError::Unavailable)?;
    if !private_source_metadata(&metadata, expected_length) {
        return Err(BackendError::Corrupt);
    }
    Ok(file)
}

fn private_source_metadata(metadata: &std::fs::Metadata, expected_length: u64) -> bool {
    metadata.file_type().is_file()
        && metadata.len() == expected_length
        && metadata.nlink() == 1
        && metadata.uid() == rustix::process::getuid().as_raw()
        && metadata.mode() & 0o077 == 0
}

/// Standard HTTP content metadata stored with an object.
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ObjectHttpMetadata {
    /// Media type.
    pub content_type: Option<String>,
    /// Content language.
    pub content_language: Option<String>,
    /// Content disposition.
    pub content_disposition: Option<String>,
    /// Content encoding.
    pub content_encoding: Option<String>,
    /// Cache-Control value.
    pub cache_control: Option<String>,
    /// Expiry instant in Unix milliseconds.
    pub cache_expiry: Option<i64>,
}

/// Backend-neutral physical storage class selected by an owning domain.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ObjectStorageClass {
    /// Default hot object storage.
    #[default]
    Standard,
    /// Provider infrequent-access storage when supported.
    InfrequentAccess,
}

/// Metadata persisted atomically with one committed object.
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ObjectMetadata {
    /// Plaintext byte length.
    pub size: u64,
    /// Stable opaque `ETag` without HTTP quotes.
    pub etag: String,
    /// Commit time in Unix milliseconds.
    pub last_modified_ms: i64,
    /// Canonical user metadata.
    pub user: BTreeMap<String, String>,
    /// Standard HTTP content metadata.
    pub http: ObjectHttpMetadata,
    /// Physical storage class requested by the owning domain.
    pub storage_class: ObjectStorageClass,
    /// Lowercase hex MD5 advertised for an SSE-C object.
    pub ssec_key_md5: Option<String>,
}

/// Atomic object publication policy.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum PutMode {
    /// Publish only when the key is absent.
    CreateOnly,
    /// Replace any current object.
    Replace,
    /// Replace only when the current `ETag` matches exactly.
    IfMatch(String),
}

/// Inclusive byte range for a GET.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ObjectRange {
    /// First byte offset.
    pub start: u64,
    /// Last byte offset, inclusive.
    pub end: u64,
}

/// Short-lived SSE-C key passed only to a backend operation.
#[derive(Clone, Zeroize, ZeroizeOnDrop)]
pub struct CustomerKey {
    bytes: [u8; 32],
}

impl std::fmt::Debug for CustomerKey {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("CustomerKey")
            .finish_non_exhaustive()
    }
}

impl CustomerKey {
    /// Copy a validated 32-byte customer key into short-lived storage.
    #[must_use]
    pub const fn new(bytes: [u8; 32]) -> Self {
        Self { bytes }
    }

    pub(crate) const fn bytes(&self) -> &[u8; 32] {
        &self.bytes
    }
}

/// Options for metadata-only access.
#[derive(Clone, Debug, Default)]
pub struct HeadOptions {
    /// Optional customer encryption key.
    pub customer_key: Option<CustomerKey>,
}

/// Options for one body read.
#[derive(Clone, Debug, Default)]
pub struct GetOptions {
    /// Optional inclusive byte range.
    pub range: Option<ObjectRange>,
    /// Optional exact `ETag` fence.
    pub if_match: Option<String>,
    /// Optional customer encryption key.
    pub customer_key: Option<CustomerKey>,
}

/// Options for one publication.
#[derive(Clone, Debug)]
pub struct PutOptions {
    /// Atomic publication mode.
    pub mode: PutMode,
    /// User and HTTP metadata.
    pub metadata: ObjectMetadata,
    /// Optional customer encryption key.
    pub customer_key: Option<CustomerKey>,
}

/// A successful object GET.
#[derive(Debug)]
pub struct ObjectGet {
    /// Metadata from the same committed object as `body`.
    pub metadata: ObjectMetadata,
    /// Exact returned range when a range was requested.
    pub range: Option<ObjectRange>,
    /// Bounded backend-neutral body stream.
    pub body: ObjectBody,
}

/// One canonical list result.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListedObject {
    /// Canonical physical key.
    pub key: ObjectKey,
    /// Exact committed object metadata.
    pub metadata: ObjectMetadata,
}

/// One stable lexical list page.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListPage {
    /// Listed committed objects.
    pub objects: Vec<ListedObject>,
    /// Backend-owned opaque continuation token.
    pub next_cursor: Option<String>,
}

/// One uploaded multipart part.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct UploadedPart {
    /// One-based part number.
    pub part_number: i32,
    /// Stable opaque part `ETag`.
    pub etag: String,
}

/// Backend operation failure, free of provider errors and filesystem paths.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BackendError {
    /// The exact object or multipart record is absent.
    NotFound,
    /// An atomic condition did not match.
    PreconditionFailed,
    /// A requested byte range is invalid.
    InvalidRange,
    /// Persisted bytes or metadata are corrupt.
    Corrupt,
    /// The selected authority is temporarily unavailable.
    Unavailable,
    /// Local capacity policy or provider capacity rejected the write.
    Capacity,
    /// A physical key violated the host-only grammar.
    InvalidKey,
    /// The supplied customer key is absent or incorrect.
    CustomerKeyInvalid,
    /// The supplied multipart state or part list is invalid.
    MultipartInvalid,
    /// The configured authority belongs to another platform or backend descriptor.
    AuthorityMismatch,
}

impl std::fmt::Display for BackendError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(match self {
            Self::NotFound => "object not found",
            Self::PreconditionFailed => "object precondition failed",
            Self::InvalidRange => "object range is invalid",
            Self::Corrupt => "object storage integrity failure",
            Self::Unavailable => "object storage unavailable",
            Self::Capacity => "object storage capacity exhausted",
            Self::InvalidKey => "object key is invalid",
            Self::CustomerKeyInvalid => "customer encryption key is invalid",
            Self::MultipartInvalid => "multipart upload is invalid",
            Self::AuthorityMismatch => "object storage authority mismatch",
        })
    }
}

impl std::error::Error for BackendError {}

enum BodyInner {
    S3(S3ObjectBody),
    Local(mpsc::Receiver<Result<Bytes, std::io::Error>>),
}

/// Backend-neutral bounded async object body.
pub struct ObjectBody {
    inner: BodyInner,
}

impl std::fmt::Debug for ObjectBody {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.debug_struct("ObjectBody").finish_non_exhaustive()
    }
}

impl ObjectBody {
    pub(crate) const fn from_s3(stream: S3ObjectBody) -> Self {
        Self {
            inner: BodyInner::S3(stream),
        }
    }

    pub(crate) const fn from_local(
        receiver: mpsc::Receiver<Result<Bytes, std::io::Error>>,
    ) -> Self {
        Self {
            inner: BodyInner::Local(receiver),
        }
    }

    /// Collect the bounded body into memory.
    pub async fn collect(mut self) -> Result<AggregatedObjectBytes, std::io::Error> {
        let mut bytes = BytesMut::new();
        while let Some(chunk) = self.next().await {
            bytes.extend_from_slice(&chunk?);
        }
        Ok(AggregatedObjectBytes(bytes.freeze()))
    }

    /// Convert the stream into a Tokio async reader.
    #[must_use]
    pub fn into_async_read(self) -> ObjectBodyReader {
        ObjectBodyReader {
            body: self,
            current: Bytes::new(),
        }
    }
}

impl Stream for ObjectBody {
    type Item = Result<Bytes, std::io::Error>;

    fn poll_next(mut self: Pin<&mut Self>, context: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        match &mut self.inner {
            BodyInner::S3(stream) => Pin::new(stream).poll_next(context),
            BodyInner::Local(receiver) => Pin::new(receiver).poll_recv(context),
        }
    }
}

/// Collected object bytes.
#[derive(Clone, Debug)]
pub struct AggregatedObjectBytes(Bytes);

impl AggregatedObjectBytes {
    /// Consume the aggregate and return its bytes.
    #[must_use]
    pub fn into_bytes(self) -> Bytes {
        self.0
    }
}

/// Tokio reader over an [`ObjectBody`].
#[derive(Debug)]
pub struct ObjectBodyReader {
    body: ObjectBody,
    current: Bytes,
}

impl AsyncRead for ObjectBodyReader {
    fn poll_read(
        mut self: Pin<&mut Self>,
        context: &mut Context<'_>,
        destination: &mut ReadBuf<'_>,
    ) -> Poll<std::io::Result<()>> {
        loop {
            if !self.current.is_empty() {
                let count = destination.remaining().min(self.current.len());
                destination.put_slice(&self.current.split_to(count));
                return Poll::Ready(Ok(()));
            }
            match Pin::new(&mut self.body).poll_next(context) {
                Poll::Ready(Some(Ok(bytes))) => self.current = bytes,
                Poll::Ready(Some(Err(error))) => return Poll::Ready(Err(error)),
                Poll::Ready(None) => return Poll::Ready(Ok(())),
                Poll::Pending => return Poll::Pending,
            }
        }
    }
}

#[derive(Debug)]
enum ObjectBackendImpl {
    Local(LocalBackend),
    S3(S3Backend),
}

/// Cloneable facade over the selected object-byte authority.
#[derive(Clone, Debug)]
pub struct ObjectBackend {
    inner: std::sync::Arc<ObjectBackendImpl>,
}

impl ObjectBackend {
    #[cfg(test)]
    pub(crate) fn inject_local_fault(&self, point: crate::local::LocalFaultPoint) {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.inject_fault(point),
            ObjectBackendImpl::S3(_) => panic!("local fault requires the local backend"),
        }
    }

    /// Inspect an existing local authority without locking or mutating it.
    pub fn inspect_local_authority(
        config: &LocalObjectStorageConfig,
    ) -> Result<(PlatformId, [u8; 32], u64), PlatformError> {
        LocalBackend::inspect_authority(config)
    }

    /// Read the platform identity from an existing local authority marker, then bind it.
    pub fn open_local_existing(
        config: &LocalObjectStorageConfig,
        max_object_bytes: u64,
    ) -> Result<(Self, PlatformId), PlatformError> {
        let platform_id = LocalBackend::discover_platform_id(config)?;
        Self::open_local(config, platform_id, max_object_bytes)
            .map(|backend| (backend, platform_id))
    }

    /// Open and exclusively bind a secure local object root.
    pub fn open_local(
        config: &LocalObjectStorageConfig,
        platform_id: PlatformId,
        max_object_bytes: u64,
    ) -> Result<Self, PlatformError> {
        Ok(Self {
            inner: std::sync::Arc::new(ObjectBackendImpl::Local(LocalBackend::open(
                config,
                platform_id,
                max_object_bytes,
            )?)),
        })
    }

    /// Connect an S3-compatible authority with already-resolved credentials.
    pub fn connect_s3(
        config: &S3Config,
        credentials: &S3Credentials,
        max_object_bytes: u64,
    ) -> Result<Self, PlatformError> {
        Ok(Self {
            inner: std::sync::Arc::new(ObjectBackendImpl::S3(S3Backend::connect(
                config,
                credentials,
                max_object_bytes,
            )?)),
        })
    }

    /// Selected backend kind.
    #[must_use]
    pub fn kind(&self) -> ObjectStorageKind {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(_) => ObjectStorageKind::Local,
            ObjectBackendImpl::S3(_) => ObjectStorageKind::S3,
        }
    }

    /// Canonical system prefix.
    #[must_use]
    pub fn prefix(&self) -> &str {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.prefix(),
            ObjectBackendImpl::S3(backend) => backend.prefix(),
        }
    }

    /// Canonical R2 prefix.
    #[must_use]
    pub fn r2_prefix(&self) -> &str {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.r2_prefix(),
            ObjectBackendImpl::S3(backend) => backend.r2_prefix(),
        }
    }

    /// Stable authority fingerprint.
    #[must_use]
    pub fn authority_sha256(&self) -> [u8; 32] {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.authority_sha256(),
            ObjectBackendImpl::S3(backend) => backend.authority_sha256(),
        }
    }

    /// Maximum object size accepted by this facade.
    #[must_use]
    pub fn max_object_bytes(&self) -> u64 {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.max_object_bytes(),
            ObjectBackendImpl::S3(backend) => backend.max_object_bytes(),
        }
    }

    /// Available bytes for a local authority; remote providers do not expose a value.
    pub fn available_bytes(&self) -> Result<Option<u64>, BackendError> {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.available_bytes().map(Some),
            ObjectBackendImpl::S3(_) => Ok(None),
        }
    }

    /// Reconcile only strictly owned crash remnants after SQLite has validated
    /// the immutable authority binding.
    pub async fn recover(&self) -> Result<(), BackendError> {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.recover().await,
            ObjectBackendImpl::S3(_) => Ok(()),
        }
    }

    /// Publish one complete object atomically.
    pub async fn put(
        &self,
        key: &ObjectKey,
        source: ObjectSource,
        options: PutOptions,
    ) -> Result<ObjectMetadata, BackendError> {
        source.validate()?;
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.put(key, source, options).await,
            ObjectBackendImpl::S3(backend) => backend.put(key, source, options).await,
        }
    }

    /// Read committed object metadata.
    pub async fn head(
        &self,
        key: &ObjectKey,
        options: HeadOptions,
    ) -> Result<ObjectMetadata, BackendError> {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.head(key, options).await,
            ObjectBackendImpl::S3(backend) => backend.head(key, options).await,
        }
    }

    /// Open one committed full or ranged object body.
    pub async fn get(
        &self,
        key: &ObjectKey,
        options: GetOptions,
    ) -> Result<ObjectGet, BackendError> {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.get(key, options).await,
            ObjectBackendImpl::S3(backend) => backend.get(key, options).await,
        }
    }

    /// Idempotently delete one exact object.
    pub async fn delete(&self, key: &ObjectKey) -> Result<(), BackendError> {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.delete(key).await,
            ObjectBackendImpl::S3(backend) => backend.delete(key).await,
        }
    }

    /// Idempotently delete a bounded exact key set.
    pub async fn delete_many(&self, keys: &[ObjectKey]) -> Result<bool, BackendError> {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.delete_many(keys).await,
            ObjectBackendImpl::S3(backend) => backend.delete_many(keys).await,
        }
    }

    /// List a stable lexical page below an optional physical prefix.
    pub async fn list(
        &self,
        prefix: &str,
        limit: u16,
        cursor: Option<&str>,
    ) -> Result<ListPage, BackendError> {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.list(prefix, limit, cursor).await,
            ObjectBackendImpl::S3(backend) => backend.list(prefix, limit, cursor).await,
        }
    }

    /// Create a durable multipart upload intent.
    pub async fn create_multipart(
        &self,
        key: &ObjectKey,
        metadata: ObjectMetadata,
        customer_key: Option<CustomerKey>,
    ) -> Result<String, BackendError> {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => {
                backend.create_multipart(key, metadata, customer_key).await
            }
            ObjectBackendImpl::S3(backend) => {
                backend.create_multipart(key, metadata, customer_key).await
            }
        }
    }

    /// Upload or replace one exact multipart part.
    pub async fn upload_part(
        &self,
        key: &ObjectKey,
        upload_id: &str,
        part_number: i32,
        source: ObjectSource,
        customer_key: Option<CustomerKey>,
    ) -> Result<UploadedPart, BackendError> {
        source.validate()?;
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => {
                backend
                    .upload_part(key, upload_id, part_number, source, customer_key)
                    .await
            }
            ObjectBackendImpl::S3(backend) => {
                backend
                    .upload_part(key, upload_id, part_number, source, customer_key)
                    .await
            }
        }
    }

    /// List incomplete upload IDs belonging to one exact key.
    pub async fn list_multipart(&self, key: &ObjectKey) -> Result<Vec<String>, BackendError> {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.list_multipart(key).await,
            ObjectBackendImpl::S3(backend) => backend.list_multipart(key).await,
        }
    }

    /// Atomically publish one validated multipart part sequence.
    pub async fn complete_multipart(
        &self,
        key: &ObjectKey,
        upload_id: &str,
        parts: &[UploadedPart],
        customer_key: Option<CustomerKey>,
    ) -> Result<ObjectMetadata, BackendError> {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => {
                backend
                    .complete_multipart(key, upload_id, parts, customer_key)
                    .await
            }
            ObjectBackendImpl::S3(backend) => {
                backend
                    .complete_multipart(key, upload_id, parts, customer_key)
                    .await
            }
        }
    }

    /// Idempotently abort one exact multipart upload.
    pub async fn abort_multipart(
        &self,
        key: &ObjectKey,
        upload_id: &str,
    ) -> Result<(), BackendError> {
        match self.inner.as_ref() {
            ObjectBackendImpl::Local(backend) => backend.abort_multipart(key, upload_id).await,
            ObjectBackendImpl::S3(backend) => backend.abort_multipart(key, upload_id).await,
        }
    }
}
