/* eslint-disable */
// Generated by oc types
/// <reference types="@open-compute/workers-types" />

interface __BaseEnv_Env {
	GREETING: "Hello from TypeScript";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
