import { randomBytes } from "node:crypto";
import { constants } from "node:fs";
import { mkdir, open, rename, rm } from "node:fs/promises";
import { basename, dirname, extname, relative, resolve } from "node:path";
import type { JsonValue, WorkerProject } from "./project.ts";

const GENERATED_HEADER = `/* eslint-disable */
// Generated by oc types
`;
const BINDING_TYPES = {
  kv_namespace: "KVNamespace",
  r2_bucket: "R2Bucket",
  d1_database: "D1Database",
  do_namespace: "DurableObjectNamespace",
  queue_producer: "Queue",
  workflow: "Workflow",
} as const;

function isErrno(error: unknown, code: string): boolean {
  return error instanceof Error && "code" in error && error.code === code;
}

function isValidIdentifier(key: string): boolean {
  return /^[a-zA-Z_$][\w$]*$/.test(key);
}

function constructTypeKey(key: string): string {
  return isValidIdentifier(key) ? key : JSON.stringify(key);
}

function jsonType(value: JsonValue): string {
  if (value === null || typeof value === "boolean" || typeof value === "number" || typeof value === "string") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) return `[${value.map(jsonType).join(", ")}]`;
  const keys = Object.keys(value).sort((left, right) => left < right ? -1 : left > right ? 1 : 0);
  if (keys.length === 0) return "{}";
  return `{ ${keys.map(key => `${constructTypeKey(key)}: ${jsonType(value[key]!)}`).join("; ")} }`;
}

function importSpecifier(from: string, to: string): string {
  const relativePath = relative(dirname(from), dirname(to)).replaceAll("\\", "/");
  const filename = basename(to, extname(to));
  if (!relativePath) return `./${filename}`;
  if (relativePath.startsWith("..")) return `${relativePath}/${filename}`;
  return `./${relativePath}/${filename}`;
}

function compareKeys(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function serviceType(project: WorkerProject, output: string, binding: { service: string; entrypoint?: string }): string {
  const entrypoint = binding.entrypoint ?? "default";
  if (binding.service === project.name && project.main !== undefined && project.frameworkOutput === undefined) {
    const specifier = importSpecifier(output, resolve(project.project, project.main));
    return `Service<typeof import(${JSON.stringify(specifier)}).${entrypoint}>`;
  }
  if (binding.entrypoint !== undefined) {
    return `Service /* entrypoint ${binding.entrypoint} from ${binding.service} */`;
  }
  return `Fetcher /* ${binding.service} */`;
}

function defineEnv(properties: Map<string, string>, key: string, type: string): void {
  if (properties.has(key)) throw new Error(`duplicate Env property ${constructTypeKey(key)}`);
  properties.set(key, type);
}

/** Render Cloudflare Env declarations from a normalized Worker project. */
export function generateEnvTypes(project: WorkerProject, outputPath: string): string {
  const output = resolve(outputPath);
  const properties = new Map<string, string>();
  for (const [key, value] of Object.entries(project.vars)) defineEnv(properties, key, jsonType(value));
  for (const key of Object.keys(project.secrets)) defineEnv(properties, key, "string");
  for (const [key, binding] of Object.entries(project.bindings)) {
    defineEnv(properties, key, BINDING_TYPES[binding.type]);
  }
  for (const [key, binding] of Object.entries(project.services)) {
    defineEnv(properties, key, serviceType(project, output, binding));
  }
  if (project.assets?.binding !== undefined) defineEnv(properties, project.assets.binding, "Fetcher");
  if (project.runtimeFeatures.images !== undefined) {
    defineEnv(properties, project.runtimeFeatures.images.binding, "ImagesBinding");
  }
  if (project.runtimeFeatures.versionMetadata !== undefined) {
    defineEnv(properties, project.runtimeFeatures.versionMetadata.binding, "WorkerVersionMetadata");
  }
  const lines = [...properties.entries()]
    .sort((left, right) => compareKeys(left[0], right[0]))
    .map(([key, type]) => `\t${constructTypeKey(key)}: ${type};`);
  const mainModule = project.main === undefined || project.frameworkOutput !== undefined
    ? undefined
    : importSpecifier(output, resolve(project.project, project.main));
  const globalProps = mainModule === undefined ? "" : `
	interface GlobalProps {
		mainModule: typeof import(${JSON.stringify(mainModule)});
	}`;
  return `${GENERATED_HEADER}/// <reference types="@open-compute/workers-types" />

interface __BaseEnv_Env {
${lines.join("\n")}
}
declare namespace Cloudflare {${globalProps}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
`;
}

async function existingRegularFile(path: string): Promise<string | undefined> {
  let file: Awaited<ReturnType<typeof open>>;
  try {
    file = await open(path, constants.O_RDONLY | constants.O_NOFOLLOW);
  } catch (error) {
    if (isErrno(error, "ENOENT")) return undefined;
    if (isErrno(error, "ELOOP") || isErrno(error, "EEXIST")) {
      throw new Error("types output cannot be a symbolic link");
    }
    throw error;
  }
  try {
    const info = await file.stat();
    if (!info.isFile()) throw new Error("types output must be a regular file");
    const bytes = Buffer.alloc(info.size);
    let offset = 0;
    while (offset < bytes.length) {
      const { bytesRead } = await file.read(bytes, offset, bytes.length - offset, offset);
      if (!bytesRead) break;
      offset += bytesRead;
    }
    return new TextDecoder("utf-8", { fatal: true }).decode(bytes.subarray(0, offset));
  } finally {
    await file.close();
  }
}

/** Atomically replace a regular generated types file; never follow a destination symlink. */
export async function writeGeneratedTypes(path: string, content: string): Promise<string> {
  const output = resolve(path);
  const existing = await existingRegularFile(output);
  if (existing !== undefined && !existing.startsWith(GENERATED_HEADER)) {
    throw new Error("types output already exists and was not generated by oc types");
  }
  await mkdir(dirname(output), { recursive: true });
  const staging = `${output}.${process.pid}.${randomBytes(8).toString("hex")}.tmp`;
  const file = await open(staging, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | constants.O_NOFOLLOW, 0o644);
  try {
    try {
      await file.writeFile(content);
      await file.sync();
    } finally {
      await file.close();
    }
    await rename(staging, output);
  } catch (error) {
    await rm(staging, { force: true });
    throw error;
  }
  return output;
}
