//! Reproducible platform Caddyfile projection for the one public Worker namespace.

use open_compute_core::{ErrorCode, PlatformError, PublicGatewayConfig};
use std::net::IpAddr;
use std::path::Path;

const ACME_CA: &str = "https://acme-v02.api.letsencrypt.org/directory";

/// Render and atomically publish the two platform-owned Caddyfiles.
pub(crate) fn write_managed(
    config: &PublicGatewayConfig,
    gateway_dir: &Path,
    admin_socket: &Path,
    upstream_socket: &Path,
    provider_socket: &Path,
) -> Result<(), PlatformError> {
    let (managed, entrypoint) = render(
        config,
        gateway_dir,
        admin_socket,
        upstream_socket,
        provider_socket,
    )?;
    open_compute_storage::atomic_write(&gateway_dir.join("managed.caddyfile"), managed.as_bytes())?;
    open_compute_storage::atomic_write(&gateway_dir.join("Caddyfile"), entrypoint.as_bytes())
}

/// Render the platform Caddyfile and the ordered import entrypoint.
pub(crate) fn render(
    config: &PublicGatewayConfig,
    gateway_dir: &Path,
    admin_socket: &Path,
    upstream_socket: &Path,
    provider_socket: &Path,
) -> Result<(String, String), PlatformError> {
    render_with_managed_path(
        config,
        gateway_dir,
        &gateway_dir.join("managed.caddyfile"),
        admin_socket,
        upstream_socket,
        provider_socket,
    )
}

/// Render a candidate whose private runtime paths remain on the live gateway.
pub(crate) fn render_candidate(
    config: &PublicGatewayConfig,
    gateway_dir: &Path,
    candidate_managed_path: &Path,
    admin_socket: &Path,
    upstream_socket: &Path,
    provider_socket: &Path,
) -> Result<(String, String), PlatformError> {
    render_with_managed_path(
        config,
        gateway_dir,
        candidate_managed_path,
        admin_socket,
        upstream_socket,
        provider_socket,
    )
}

fn render_with_managed_path(
    config: &PublicGatewayConfig,
    gateway_dir: &Path,
    managed_path: &Path,
    admin_socket: &Path,
    upstream_socket: &Path,
    provider_socket: &Path,
) -> Result<(String, String), PlatformError> {
    config.validate()?;
    if [admin_socket, upstream_socket, provider_socket]
        .into_iter()
        .any(|path| !crate::instance_control::unix_socket_path_is_valid(path))
    {
        return Err(invalid_path());
    }
    let admin = quoted_url("unix/", admin_socket)?;
    let storage = quoted(&gateway_dir.join("storage"))?;
    let upstream = quoted_url("unix/", upstream_socket)?;
    let provider = quoted(provider_socket)?;
    let mut entrypoint = format!(
        "# Generated by ocd. Do not edit.\nimport {}\n",
        quoted(managed_path)?
    );
    for file in &config.caddy {
        entrypoint.push_str(&format!("import {}\n", quoted(&file.caddy_file)?));
    }
    let listen = config.https_listen;
    let bind = match listen.ip() {
        IpAddr::V4(ip) => ip.to_string(),
        IpAddr::V6(ip) => format!("[{ip}]"),
    };
    let proxy_protocol = if config.proxy_protocol_from.is_empty() {
        String::new()
    } else {
        let peers = config
            .proxy_protocol_from
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(" ");
        format!(
            "        listener_wrappers {{\n            proxy_protocol {{\n                timeout 2s\n                allow {peers}\n                fallback_policy reject\n            }}\n            tls\n        }}\n"
        )
    };
    let managed = format!(
        "# Generated by ocd. Do not edit.\n{{\n    admin {admin}\n    persist_config off\n    storage file_system {storage}\n    auto_https disable_redirects\n    https_port {port}\n    acme_ca {ACME_CA}\n    default_bind {bind}\n    servers {listen} {{\n        protocols h1 h2\n        strict_sni_host on\n{proxy_protocol}    }}\n}}\n\nhttps://*.{base}:{port} {{\n    tls {{\n        dns opencompute {provider}\n    }}\n    reverse_proxy {upstream} {{\n        header_up Host {{host}}\n        header_up -Forwarded\n        header_up -X-Forwarded-*\n        header_up -CF-Connecting-IP\n        header_up CF-Connecting-IP {{remote_ip}}\n        header_up -X-Open-Compute-*\n        transport http {{\n            dial_timeout 2s\n        }}\n    }}\n}}\n",
        base = config.base_domain,
        port = listen.port(),
    );
    Ok((managed, entrypoint))
}

fn quoted_url(scheme: &str, path: &Path) -> Result<String, PlatformError> {
    if !path.is_absolute() {
        return Err(invalid_path());
    }
    let path = path.to_str().ok_or_else(invalid_path)?;
    quoted_text(&format!("{scheme}{path}"))
}

fn quoted(path: &Path) -> Result<String, PlatformError> {
    if !path.is_absolute() {
        return Err(invalid_path());
    }
    let path = path.to_str().ok_or_else(invalid_path)?;
    quoted_text(path)
}

fn quoted_text(value: &str) -> Result<String, PlatformError> {
    if value.chars().any(char::is_control) {
        return Err(invalid_path());
    }
    Ok(format!(
        "\"{}\"",
        value.replace('\\', "\\\\").replace('"', "\\\"")
    ))
}

fn invalid_path() -> PlatformError {
    PlatformError::new(
        ErrorCode::ConfigPathInvalid,
        "public gateway path is invalid",
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::PermissionsExt as _;

    #[test]
    fn projection_has_one_private_upstream_and_ordered_operator_imports() {
        let config = PublicGatewayConfig {
            base_domain: "compute.example.com".into(),
            ingress_ipv4: vec!["203.0.113.10".parse().unwrap()],
            ingress_ipv6: Vec::new(),
            https_listen: "127.0.0.1:8443".parse().unwrap(),
            challenge_dns_listen: "127.0.0.1:8053".parse().unwrap(),
            proxy_protocol_from: vec!["192.0.2.0/24".parse().unwrap()],
            caddy: vec![
                open_compute_core::CaddyFileConfig {
                    caddy_file: "/src/test/gateway/sites/first.caddyfile".into(),
                },
                open_compute_core::CaddyFileConfig {
                    caddy_file: "/src/test/gateway/sites/second.caddyfile".into(),
                },
            ],
        };
        let (managed, entrypoint) = render(
            &config,
            Path::new("/data/gateway"),
            Path::new("/data/gateway/run/admin.sock"),
            Path::new("/data/runtime/gateway-upstream.sock"),
            Path::new("/data/gateway/run/challenge-provider.sock"),
        )
        .unwrap();
        assert_eq!(
            managed,
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/../../test/gateway/managed.caddyfile"
            ))
        );
        assert_eq!(
            entrypoint,
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/../../test/gateway/Caddyfile"
            ))
        );
        assert!(managed.contains("https://*.compute.example.com:8443"));
        assert!(managed.contains("admin \"unix//data/gateway/run/admin.sock\""));
        assert!(managed.contains("reverse_proxy \"unix//data/runtime/gateway-upstream.sock\""));
        assert!(managed.contains("dns opencompute \"/data/gateway/run/challenge-provider.sock\""));
        assert!(managed.contains("allow 192.0.2.0/24"));
        assert!(managed.contains("protocols h1 h2"));
        assert!(managed.contains("https_port 8443"));
        assert!(
            entrypoint.find("managed.caddyfile").unwrap()
                < entrypoint.find("first.caddyfile").unwrap()
        );
        assert!(
            entrypoint.find("first.caddyfile").unwrap()
                < entrypoint.find("second.caddyfile").unwrap()
        );
        let temp = tempfile::tempdir().unwrap();
        let gateway = temp.path().join("gateway");
        open_compute_storage::ensure_dir_secure(&gateway).unwrap();
        let (expected_managed, expected_entrypoint) = render(
            &config,
            &gateway,
            Path::new("/data/gateway/run/admin.sock"),
            Path::new("/data/runtime/gateway-upstream.sock"),
            Path::new("/data/gateway/run/challenge-provider.sock"),
        )
        .unwrap();
        write_managed(
            &config,
            &gateway,
            Path::new("/data/gateway/run/admin.sock"),
            Path::new("/data/runtime/gateway-upstream.sock"),
            Path::new("/data/gateway/run/challenge-provider.sock"),
        )
        .unwrap();
        for (name, expected) in [
            ("managed.caddyfile", expected_managed),
            ("Caddyfile", expected_entrypoint),
        ] {
            let path = gateway.join(name);
            assert_eq!(std::fs::read_to_string(&path).unwrap(), expected);
            assert_eq!(
                std::fs::metadata(path).unwrap().permissions().mode() & 0o777,
                0o600
            );
        }
        assert!(
            render(
                &config,
                Path::new("/data/gateway"),
                Path::new("/data/gateway/run/admin.sock"),
                Path::new("relative.sock"),
                Path::new("/data/gateway/run/challenge-provider.sock"),
            )
            .is_err()
        );
        let long_socket = Path::new("/tmp").join("x".repeat(100));
        assert!(
            render(
                &config,
                Path::new("/data/gateway"),
                &long_socket,
                Path::new("/data/runtime/gateway-upstream.sock"),
                Path::new("/data/gateway/run/challenge-provider.sock"),
            )
            .is_err()
        );

        let mut direct = config.clone();
        direct.proxy_protocol_from.clear();
        let (managed, _) = render(
            &direct,
            Path::new("/data/gateway"),
            Path::new("/data/gateway/run/admin.sock"),
            Path::new("/data/runtime/gateway-upstream.sock"),
            Path::new("/data/gateway/run/challenge-provider.sock"),
        )
        .unwrap();
        assert!(!managed.contains("proxy_protocol {"));
        direct.caddy[0].caddy_file = "/tmp/site.caddyfile\nimport /tmp/unsafe".into();
        assert_eq!(
            render(
                &direct,
                Path::new("/data/gateway"),
                Path::new("/data/gateway/run/admin.sock"),
                Path::new("/data/runtime/gateway-upstream.sock"),
                Path::new("/data/gateway/run/challenge-provider.sock"),
            )
            .unwrap_err()
            .code(),
            ErrorCode::ConfigPathInvalid
        );
    }
}
