//! Qualified page commands and events; browser-wide authority is handled separately.

pub(super) fn page_method(method: &str) -> bool {
    matches!(
        method,
        "Runtime.enable"
            | "Runtime.evaluate"
            | "Runtime.callFunctionOn"
            | "Runtime.getProperties"
            | "Runtime.releaseObject"
            | "Runtime.releaseObjectGroup"
            | "Runtime.runIfWaitingForDebugger"
            | "Runtime.addBinding"
            | "Runtime.removeBinding"
            | "Runtime.disable"
            | "Runtime.getIsolateId"
            | "Debugger.enable"
            | "Debugger.disable"
            | "Debugger.getScriptSource"
            | "Debugger.setPauseOnExceptions"
            | "Debugger.setAsyncCallStackDepth"
            | "Debugger.setBlackboxPatterns"
            | "Page.enable"
            | "Page.disable"
            | "Page.getFrameTree"
            | "Page.navigate"
            | "Page.reload"
            | "Page.stopLoading"
            | "Page.setDocumentContent"
            | "Page.getLayoutMetrics"
            | "Page.captureScreenshot"
            | "Page.printToPDF"
            | "Page.createIsolatedWorld"
            | "Page.addScriptToEvaluateOnNewDocument"
            | "Page.removeScriptToEvaluateOnNewDocument"
            | "Page.setLifecycleEventsEnabled"
            | "Page.setFontFamilies"
            | "Page.bringToFront"
            | "Page.setBypassCSP"
            | "Page.startScreencast"
            | "Page.stopScreencast"
            | "Page.screencastFrameAck"
            | "Network.enable"
            | "Network.disable"
            | "Network.setCacheDisabled"
            | "Network.setExtraHTTPHeaders"
            | "Network.setUserAgentOverride"
            | "Network.setBypassServiceWorker"
            | "Network.getResponseBody"
            | "Network.getRequestPostData"
            | "Network.setCookies"
            | "Network.getCookies"
            | "Network.deleteCookies"
            | "Network.emulateNetworkConditions"
            | "Log.enable"
            | "Log.disable"
            | "DOM.enable"
            | "DOM.getDocument"
            | "DOM.querySelector"
            | "DOM.querySelectorAll"
            | "DOM.describeNode"
            | "DOM.resolveNode"
            | "DOM.getBoxModel"
            | "DOM.getContentQuads"
            | "DOM.scrollIntoViewIfNeeded"
            | "DOM.getNodeForLocation"
            | "DOM.focus"
            | "DOM.getOuterHTML"
            | "DOM.getFrameOwner"
            | "Emulation.setDeviceMetricsOverride"
            | "Emulation.setUserAgentOverride"
            | "Emulation.clearDeviceMetricsOverride"
            | "Emulation.setTouchEmulationEnabled"
            | "Emulation.setEmulatedMedia"
            | "Emulation.setTimezoneOverride"
            | "Emulation.setLocaleOverride"
            | "Emulation.setGeolocationOverride"
            | "Emulation.setScriptExecutionDisabled"
            | "Emulation.setFocusEmulationEnabled"
            | "Emulation.setIdleOverride"
            | "Emulation.clearIdleOverride"
            | "Emulation.setEmulatedVisionDeficiency"
            | "Emulation.setCPUThrottlingRate"
            | "Performance.enable"
            | "Performance.getMetrics"
            | "Performance.disable"
            | "Accessibility.enable"
            | "Accessibility.getFullAXTree"
            | "Accessibility.getPartialAXTree"
            | "Input.dispatchKeyEvent"
            | "Input.dispatchMouseEvent"
            | "Input.dispatchTouchEvent"
            | "Input.insertText"
            | "Input.synthesizeScrollGesture"
            | "Fetch.enable"
            | "Fetch.disable"
            | "Fetch.continueRequest"
            | "Fetch.fulfillRequest"
            | "Fetch.failRequest"
            | "Fetch.continueWithAuth"
            | "Fetch.getResponseBody"
            | "IO.read"
            | "IO.close"
    )
}
pub(super) fn page_event(method: &str) -> bool {
    matches!(
        method.split_once('.').map(|(domain, _)| domain),
        Some(
            "Runtime"
                | "Debugger"
                | "Page"
                | "Network"
                | "Log"
                | "DOM"
                | "Accessibility"
                | "Fetch"
                | "Inspector"
        )
    )
}
