[package]
name = "open-compute-images"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
rust-version.workspace = true
description.workspace = true
publish.workspace = true

[dependencies]
image.workspace = true
open-compute-core = { path = "../core" }
serde.workspace = true

[lints]
workspace = true
