//! Offline local-authority snapshot preparation and manifest authentication.

use crate::{
    ControlDb, D1_DATABASE_SCHEMA_VERSION, DataDir, KV_SCHEMA_VERSION, MasterKey,
    current_scheduler_schema_version, inspect_control_db, inspect_scheduler_db, migrations,
};
use hmac::{Hmac, Mac};
use open_compute_core::{
    AccountId, ErrorCode, HardeningConfig, PlatformError, PlatformReleaseIdentityV1,
    PlatformSnapshotManifestV1, ResourceId, SnapshotFileRole, SnapshotFileV1, SnapshotTotalsV1,
};
use rusqlite::{Connection, OpenFlags};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::io::{Read, Write};
use std::os::unix::fs::OpenOptionsExt as _;
use std::path::{Path, PathBuf};
use std::str::FromStr as _;

type HmacSha256 = Hmac<Sha256>;
const SNAPSHOT_HKDF_INFO: &[u8] = b"open-compute/platform-snapshot-manifest/v1";

/// One prepared local object awaiting verified upload.
#[derive(Clone, Debug)]
pub struct PreparedSnapshotFile {
    /// Signed manifest entry.
    pub entry: SnapshotFileV1,
    /// Flat, private staging file containing the exact object bytes.
    pub staging_path: PathBuf,
}

/// Offline local snapshot material. Dropping it removes only its exact flat staging files.
#[derive(Debug)]
pub struct PreparedPlatformSnapshot {
    /// Unsigned manifest. The caller adds immutable references and authenticates it.
    pub manifest: PlatformSnapshotManifestV1,
    /// Exact local files corresponding to `manifest.files`.
    pub files: Vec<PreparedSnapshotFile>,
    staging_dir: PathBuf,
}

impl Drop for PreparedPlatformSnapshot {
    fn drop(&mut self) {
        for file in &self.files {
            let _ = std::fs::remove_file(&file.staging_path);
        }
        let _ = std::fs::remove_dir(&self.staging_dir);
    }
}

/// Inputs that bind snapshot creation to one release and remote authority.
#[derive(Clone, Debug)]
pub struct PreparePlatformSnapshotRequest<'a> {
    /// Canonical `UUIDv7` snapshot identity.
    pub snapshot_id: &'a str,
    /// Bounded operator label.
    pub label: &'a str,
    /// Audit time in Unix milliseconds.
    pub created_at_ms: i64,
    /// Release identity generated by production registries.
    pub release: PlatformReleaseIdentityV1,
    /// Existing master-key fingerprint.
    pub master_key_fingerprint: &'a str,
    /// Configured S3 authority fingerprint.
    pub s3_authority_fingerprint: &'a str,
    /// Configured R2 prefix fingerprint.
    pub r2_prefix_fingerprint: &'a str,
    /// Redacted product/storage policy fingerprint required for restore.
    pub config_policy_sha256: &'a str,
    /// Full canonical S3 prefix ending in `/objects/`.
    pub object_prefix: &'a str,
    /// Operator hard caps.
    pub hardening: &'a HardeningConfig,
    /// SQLite busy timeout.
    pub sqlite_busy_timeout_ms: u64,
}

/// Prepare consistent standalone SQLite copies and opaque DO files while the offline lock is held.
pub fn prepare_platform_snapshot(
    data_dir: &DataDir,
    request: &PreparePlatformSnapshotRequest<'_>,
) -> Result<PreparedPlatformSnapshot, PlatformError> {
    validate_request(request)?;
    let (control_schema, identity) =
        inspect_control_db(&data_dir.control_db_path(), request.sqlite_busy_timeout_ms)
            .map_err(|error| snapshot_stage(&error, "snapshot control preflight failed"))?;
    if identity.master_key_id != request.master_key_fingerprint {
        return Err(PlatformError::new(
            ErrorCode::MasterKeyMismatch,
            "snapshot master key does not match platform authority",
        ));
    }
    let scheduler_schema = inspect_scheduler_db(
        &data_dir.scheduler_db_path(),
        request.sqlite_busy_timeout_ms,
        request.created_at_ms,
    )
    .map_err(|error| snapshot_stage(&error, "snapshot scheduler preflight failed"))?;
    if u32::try_from(control_schema).ok() != Some(request.release.control_schema_version)
        || u32::try_from(scheduler_schema.schema_version).ok()
            != Some(request.release.scheduler_schema_version)
        || request.release.kv_schema_version_min != KV_SCHEMA_VERSION
        || request.release.kv_schema_version_max != KV_SCHEMA_VERSION
        || request.release.d1_schema_version_min != D1_DATABASE_SCHEMA_VERSION
        || request.release.d1_schema_version_max != D1_DATABASE_SCHEMA_VERSION
    {
        return Err(PlatformError::new(
            ErrorCode::UpgradeRequired,
            "snapshot source schema tuple does not match the executing release",
        ));
    }
    let sources = snapshot_sources(data_dir, request, &identity.platform_id.to_string())?;
    let staging_dir = create_staging_dir(data_dir, request.snapshot_id)?;
    let result = prepare_files(request, &staging_dir, sources);
    let files = match result {
        Ok(files) => files,
        Err(error) => {
            let _ = remove_flat_staging(&staging_dir);
            return Err(error);
        }
    };
    let total_bytes = files.iter().try_fold(0_u64, |total, file| {
        total
            .checked_add(file.entry.size)
            .ok_or_else(snapshot_invalid)
    })?;
    let mut source_schemas = BTreeMap::new();
    source_schemas.insert(
        "control".to_owned(),
        u32::try_from(control_schema).map_err(|_| snapshot_invalid())?,
    );
    source_schemas.insert(
        "scheduler".to_owned(),
        u32::try_from(scheduler_schema.schema_version).map_err(|_| snapshot_invalid())?,
    );
    source_schemas.insert("kv".to_owned(), KV_SCHEMA_VERSION);
    source_schemas.insert("d1".to_owned(), D1_DATABASE_SCHEMA_VERSION);
    let manifest = PlatformSnapshotManifestV1 {
        schema_version: 1,
        snapshot_id: request.snapshot_id.to_owned(),
        platform_id: identity.platform_id.to_string(),
        label: request.label.to_owned(),
        created_at_ms: request.created_at_ms,
        source_release: request.release.clone(),
        source_schemas,
        master_key_fingerprint: request.master_key_fingerprint.to_owned(),
        s3_authority_fingerprint: request.s3_authority_fingerprint.to_owned(),
        r2_prefix_fingerprint: request.r2_prefix_fingerprint.to_owned(),
        config_policy_sha256: request.config_policy_sha256.to_owned(),
        immutable_references: Vec::new(),
        files: files.iter().map(|file| file.entry.clone()).collect(),
        totals: SnapshotTotalsV1 {
            files: u32::try_from(files.len()).map_err(|_| snapshot_invalid())?,
            bytes: total_bytes,
        },
        manifest_mac: "0".repeat(64),
    };
    manifest
        .validate(
            request.hardening.max_snapshot_files,
            request.hardening.max_snapshot_file_bytes,
            request.hardening.max_snapshot_total_bytes,
        )
        .map_err(|error| snapshot_stage(&error, "snapshot manifest assembly failed"))?;
    Ok(PreparedPlatformSnapshot {
        manifest,
        files,
        staging_dir,
    })
}

/// Conservatively estimate bytes that will be copied into local snapshot staging.
pub fn estimate_platform_snapshot_bytes(
    data_dir: &DataDir,
    request: &PreparePlatformSnapshotRequest<'_>,
    platform_id: &str,
) -> Result<u64, PlatformError> {
    snapshot_sources(data_dir, request, platform_id)?
        .into_iter()
        .try_fold(0_u64, |total, source| {
            let file = crate::fs::open_nofollow(&source.path, false, false)?;
            crate::fs::validate_owned_read_fd(&file)?;
            let size = file.metadata().map_err(|_| snapshot_invalid())?.len();
            if size > request.hardening.max_snapshot_file_bytes {
                return Err(snapshot_invalid());
            }
            total
                .checked_add(size)
                .filter(|value| *value <= request.hardening.max_snapshot_total_bytes)
                .ok_or_else(snapshot_invalid)
        })
}

/// Authenticate a manifest with the domain-separated master-key derivative.
pub fn sign_snapshot_manifest(
    manifest: &mut PlatformSnapshotManifestV1,
    master_key: &MasterKey,
) -> Result<(), PlatformError> {
    let bytes = manifest.canonical_unsigned_bytes()?;
    manifest.manifest_mac = manifest_mac(master_key, &manifest.platform_id, &bytes)?;
    Ok(())
}

/// Verify a manifest MAC in constant time.
pub fn verify_snapshot_manifest_mac(
    manifest: &PlatformSnapshotManifestV1,
    master_key: &MasterKey,
) -> Result<(), PlatformError> {
    let expected = hex::decode(&manifest.manifest_mac).map_err(|_| snapshot_invalid())?;
    let key = derive_manifest_key(master_key, &manifest.platform_id)?;
    let mut mac = HmacSha256::new_from_slice(&key).map_err(|_| snapshot_invalid())?;
    mac.update(&manifest.canonical_unsigned_bytes()?);
    mac.verify_slice(&expected).map_err(|_| snapshot_invalid())
}

fn prepare_files(
    request: &PreparePlatformSnapshotRequest<'_>,
    staging_dir: &Path,
    sources: Vec<SnapshotSource>,
) -> Result<Vec<PreparedSnapshotFile>, PlatformError> {
    let mut files = Vec::with_capacity(sources.len());
    let mut total = 0_u64;
    for (index, source) in sources.into_iter().enumerate() {
        let staged = staging_dir.join(format!("{index:06}.bin"));
        let stage = match source.role {
            SnapshotFileRole::ControlSqlite => "snapshot control copy failed",
            SnapshotFileRole::SchedulerSqlite => "snapshot scheduler copy failed",
            SnapshotFileRole::KvSqlite => "snapshot KV copy failed",
            SnapshotFileRole::D1Sqlite => "snapshot D1 copy failed",
            SnapshotFileRole::DurableObjectFile => "snapshot localDisk copy failed",
        };
        if source.sqlite {
            sqlite_backup(&source.path, &staged, request.sqlite_busy_timeout_ms)
                .map_err(|error| snapshot_stage(&error, stage))?;
            sqlite_quick_check(&staged, request.sqlite_busy_timeout_ms)
                .map_err(|error| snapshot_stage(&error, stage))?;
        } else {
            copy_regular_file(&source.path, &staged)
                .map_err(|error| snapshot_stage(&error, stage))?;
        }
        let (sha256, size) = hash_regular_file(&staged)
            .map_err(|error| snapshot_stage(&error, "snapshot staged file validation failed"))?;
        if size > request.hardening.max_snapshot_file_bytes {
            return Err(PlatformError::new(
                ErrorCode::SnapshotInvalid,
                "snapshot staged file exceeds the configured size limit",
            ));
        }
        total = total.checked_add(size).ok_or_else(snapshot_invalid)?;
        if total > request.hardening.max_snapshot_total_bytes {
            return Err(PlatformError::new(
                ErrorCode::SnapshotInvalid,
                "snapshot staged files exceed the configured total size limit",
            ));
        }
        files.push(PreparedSnapshotFile {
            entry: SnapshotFileV1 {
                role: source.role,
                logical_id: source.logical_id,
                restore_path: source.restore_path,
                object_key: format!("{}{index:06}.bin", request.object_prefix),
                size,
                sha256,
                mode: 0o600,
            },
            staging_path: staged,
        });
    }
    Ok(files)
}

fn snapshot_sources(
    data_dir: &DataDir,
    request: &PreparePlatformSnapshotRequest<'_>,
    platform_id: &str,
) -> Result<Vec<SnapshotSource>, PlatformError> {
    let mut sources = vec![SnapshotSource {
        role: SnapshotFileRole::ControlSqlite,
        logical_id: "control".to_owned(),
        restore_path: "control.sqlite".to_owned(),
        path: data_dir.control_db_path(),
        sqlite: true,
    }];
    sources.push(SnapshotSource {
        role: SnapshotFileRole::SchedulerSqlite,
        logical_id: "scheduler".to_owned(),
        restore_path: "scheduler.sqlite".to_owned(),
        path: data_dir.scheduler_db_path(),
        sqlite: true,
    });
    sources.extend(
        resource_sources(
            &data_dir.control_db_path(),
            data_dir.root(),
            request.sqlite_busy_timeout_ms,
        )
        .map_err(|error| snapshot_stage(&error, "snapshot resource enumeration failed"))?,
    );
    sources.extend(
        durable_object_sources(data_dir.root(), platform_id)
            .map_err(|error| snapshot_stage(&error, "snapshot localDisk enumeration failed"))?,
    );
    sources.sort_by(|left, right| left.restore_path.cmp(&right.restore_path));
    if sources.len() > request.hardening.max_snapshot_files as usize {
        return Err(snapshot_invalid());
    }
    Ok(sources)
}

struct SnapshotSource {
    role: SnapshotFileRole,
    logical_id: String,
    restore_path: String,
    path: PathBuf,
    sqlite: bool,
}

fn resource_sources(
    control_path: &Path,
    data_root: &Path,
    busy_timeout_ms: u64,
) -> Result<Vec<SnapshotSource>, PlatformError> {
    let db = ControlDb::open_readonly(control_path, busy_timeout_ms)?;
    db.with_read(|connection| {
        let mut statement = connection
            .prepare(
                "SELECT r.account_id, r.id, r.kind,
                        COALESCE(k.storage_key, d.storage_key)
                 FROM resources r
                 LEFT JOIN kv_namespaces k ON k.resource_id = r.id
                 LEFT JOIN d1_databases d ON d.resource_id = r.id
                 WHERE r.state != 'tombstoned'
                   AND r.kind IN ('kv_namespace', 'd1_database')
                 ORDER BY r.kind, r.account_id, r.id",
            )
            .map_err(|_| snapshot_invalid())?;
        let rows = statement
            .query_map([], |row| {
                Ok((
                    row.get::<_, String>(0)?,
                    row.get::<_, String>(1)?,
                    row.get::<_, String>(2)?,
                    row.get::<_, String>(3)?,
                ))
            })
            .map_err(|_| snapshot_invalid())?;
        let mut sources = Vec::new();
        for row in rows {
            let (account, resource, kind, storage_key) = row.map_err(|_| snapshot_invalid())?;
            let account = AccountId::from_str(&account).map_err(|_| snapshot_invalid())?;
            let resource = ResourceId::from_str(&resource).map_err(|_| snapshot_invalid())?;
            let expected = format!("v1/{account}/{resource}/data.sqlite");
            if storage_key != expected {
                return Err(snapshot_invalid());
            }
            let (role, product) = match kind.as_str() {
                "kv_namespace" => (SnapshotFileRole::KvSqlite, "kv"),
                "d1_database" => (SnapshotFileRole::D1Sqlite, "d1"),
                _ => return Err(snapshot_invalid()),
            };
            let restore_path = format!("{product}/{account}/{resource}/data.sqlite");
            let path = data_root.join(&restore_path);
            crate::fs::validate_contained(data_root, &path)?;
            crate::fs::validate_owned_file(&path, false)?;
            sources.push(SnapshotSource {
                role,
                logical_id: resource.to_string(),
                restore_path,
                path,
                sqlite: true,
            });
        }
        Ok(sources)
    })
}

fn durable_object_sources(
    data_root: &Path,
    platform_id: &str,
) -> Result<Vec<SnapshotSource>, PlatformError> {
    let root = data_root.join("do");
    if !root.exists() {
        return Ok(Vec::new());
    }
    crate::fs::validate_owned_dir(&root)?;
    let mut pending = vec![root.clone()];
    let mut sources = Vec::new();
    while let Some(directory) = pending.pop() {
        for entry in std::fs::read_dir(&directory).map_err(|_| snapshot_invalid())? {
            let entry = entry.map_err(|_| snapshot_invalid())?;
            let kind = entry.file_type().map_err(|_| snapshot_invalid())?;
            if kind.is_symlink() {
                return Err(snapshot_invalid());
            }
            if kind.is_dir() {
                pending.push(entry.path());
                continue;
            }
            if !kind.is_file() {
                return Err(snapshot_invalid());
            }
            crate::fs::validate_owned_file(&entry.path(), false)?;
            let relative = entry
                .path()
                .strip_prefix(data_root)
                .map_err(|_| snapshot_invalid())?
                .to_string_lossy()
                .replace('\\', "/");
            sources.push(SnapshotSource {
                role: SnapshotFileRole::DurableObjectFile,
                logical_id: platform_id.to_owned(),
                restore_path: relative,
                path: entry.path(),
                sqlite: false,
            });
        }
    }
    Ok(sources)
}

fn sqlite_backup(
    source: &Path,
    destination: &Path,
    busy_timeout_ms: u64,
) -> Result<(), PlatformError> {
    crate::fs::validate_owned_file(source, false)?;
    if destination.exists() || std::fs::symlink_metadata(destination).is_ok() {
        return Err(snapshot_invalid());
    }
    let source_path = crate::control_db::leaf_nofollow_path(source)?;
    let source_connection = Connection::open_with_flags(
        source_path,
        OpenFlags::SQLITE_OPEN_READ_ONLY | OpenFlags::SQLITE_OPEN_NOFOLLOW,
    )
    .map_err(|_| snapshot_invalid())?;
    source_connection
        .busy_timeout(std::time::Duration::from_millis(busy_timeout_ms))
        .map_err(|_| snapshot_invalid())?;
    let destination_path = crate::control_db::leaf_nofollow_path(destination)?;
    let mut target = Connection::open_with_flags(
        destination_path,
        OpenFlags::SQLITE_OPEN_READ_WRITE
            | OpenFlags::SQLITE_OPEN_CREATE
            | OpenFlags::SQLITE_OPEN_NOFOLLOW,
    )
    .map_err(|_| snapshot_invalid())?;
    {
        let backup = rusqlite::backup::Backup::new(&source_connection, &mut target)
            .map_err(|_| snapshot_invalid())?;
        backup
            .run_to_completion(256, std::time::Duration::from_millis(5), None)
            .map_err(|_| snapshot_invalid())?;
    }
    // SQLite Online Backup copies the source header, including WAL journal mode. Normalize the
    // standalone snapshot only after the copy so read-only verification cannot create sidecars.
    target
        .pragma_update(None, "journal_mode", "DELETE")
        .map_err(|_| snapshot_invalid())?;
    target.close().map_err(|_| snapshot_invalid())?;
    crate::fs::chmod(destination, 0o600)?;
    sync_file(destination)
}

fn sqlite_quick_check(path: &Path, busy_timeout_ms: u64) -> Result<(), PlatformError> {
    let open_path = crate::control_db::leaf_nofollow_path(path)?;
    let connection = Connection::open_with_flags(
        open_path,
        OpenFlags::SQLITE_OPEN_READ_ONLY | OpenFlags::SQLITE_OPEN_NOFOLLOW,
    )
    .map_err(|_| snapshot_invalid())?;
    connection
        .busy_timeout(std::time::Duration::from_millis(busy_timeout_ms))
        .map_err(|_| snapshot_invalid())?;
    let result: String = connection
        .pragma_query_value(None, "quick_check", |row| row.get(0))
        .map_err(|_| snapshot_invalid())?;
    if result != "ok" {
        return Err(snapshot_invalid());
    }
    Ok(())
}

fn copy_regular_file(source: &Path, destination: &Path) -> Result<(), PlatformError> {
    crate::fs::validate_owned_file(source, false)?;
    let mut input = crate::fs::open_nofollow(source, false, false)?;
    crate::fs::validate_owned_read_fd(&input)?;
    let mut output = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(destination)
        .map_err(|_| snapshot_invalid())?;
    let mut buffer = [0_u8; 64 * 1024];
    loop {
        let read = input.read(&mut buffer).map_err(|_| snapshot_invalid())?;
        if read == 0 {
            break;
        }
        output
            .write_all(&buffer[..read])
            .map_err(|_| snapshot_invalid())?;
    }
    output.sync_all().map_err(|_| snapshot_invalid())
}

fn hash_regular_file(path: &Path) -> Result<(String, u64), PlatformError> {
    crate::fs::validate_owned_file(path, true)?;
    let mut input = std::fs::File::open(path).map_err(|_| snapshot_invalid())?;
    let size = input.metadata().map_err(|_| snapshot_invalid())?.len();
    let mut hasher = Sha256::new();
    let mut buffer = [0_u8; 64 * 1024];
    loop {
        let read = input.read(&mut buffer).map_err(|_| snapshot_invalid())?;
        if read == 0 {
            break;
        }
        hasher.update(&buffer[..read]);
    }
    Ok((hex::encode(hasher.finalize()), size))
}

fn create_staging_dir(data_dir: &DataDir, snapshot_id: &str) -> Result<PathBuf, PlatformError> {
    let path = data_dir
        .backup_staging_dir()
        .join(format!("platform-{snapshot_id}"));
    std::fs::create_dir(&path).map_err(|_| snapshot_invalid())?;
    crate::fs::chmod(&path, 0o700)?;
    crate::fs::validate_owned_dir(&path)?;
    Ok(path)
}

fn remove_flat_staging(path: &Path) -> Result<(), PlatformError> {
    for entry in std::fs::read_dir(path).map_err(|_| snapshot_invalid())? {
        let entry = entry.map_err(|_| snapshot_invalid())?;
        if !entry.file_type().map_err(|_| snapshot_invalid())?.is_file() {
            return Err(snapshot_invalid());
        }
        std::fs::remove_file(entry.path()).map_err(|_| snapshot_invalid())?;
    }
    std::fs::remove_dir(path).map_err(|_| snapshot_invalid())
}

fn sync_file(path: &Path) -> Result<(), PlatformError> {
    std::fs::File::open(path)
        .and_then(|file| file.sync_all())
        .map_err(|_| snapshot_invalid())
}

fn validate_request(request: &PreparePlatformSnapshotRequest<'_>) -> Result<(), PlatformError> {
    let uuid = uuid::Uuid::parse_str(request.snapshot_id).map_err(|_| snapshot_invalid())?;
    if uuid.get_version_num() != 7
        || uuid.hyphenated().to_string() != request.snapshot_id
        || request.label.is_empty()
        || request.label.len() > 128
        || request.created_at_ms <= 0
        || !request.release.validate()
        || request.master_key_fingerprint.len() != 64
        || request.config_policy_sha256.len() != 64
        || !request
            .config_policy_sha256
            .bytes()
            .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
        || !request.object_prefix.ends_with("/objects/")
        || request.sqlite_busy_timeout_ms == 0
        || u32::try_from(migrations::current_schema_version()).ok()
            != Some(request.release.control_schema_version)
        || u32::try_from(current_scheduler_schema_version()).ok()
            != Some(request.release.scheduler_schema_version)
    {
        return Err(snapshot_invalid());
    }
    Ok(())
}

fn manifest_mac(
    master_key: &MasterKey,
    platform_id: &str,
    canonical: &[u8],
) -> Result<String, PlatformError> {
    let key = derive_manifest_key(master_key, platform_id)?;
    let mut mac = HmacSha256::new_from_slice(&key).map_err(|_| snapshot_invalid())?;
    mac.update(canonical);
    Ok(hex::encode(mac.finalize().into_bytes()))
}

fn derive_manifest_key(
    master_key: &MasterKey,
    platform_id: &str,
) -> Result<[u8; 32], PlatformError> {
    let mut extract =
        HmacSha256::new_from_slice(platform_id.as_bytes()).map_err(|_| snapshot_invalid())?;
    extract.update(master_key.bytes().expose());
    let prk = extract.finalize().into_bytes();
    let mut expand = HmacSha256::new_from_slice(&prk).map_err(|_| snapshot_invalid())?;
    expand.update(SNAPSHOT_HKDF_INFO);
    expand.update(&[1]);
    Ok(expand.finalize().into_bytes().into())
}

fn snapshot_invalid() -> PlatformError {
    PlatformError::new(
        ErrorCode::SnapshotInvalid,
        "platform snapshot local authority is invalid",
    )
}

fn snapshot_stage(error: &PlatformError, message: &'static str) -> PlatformError {
    PlatformError::new(error.code(), message)
}
