using Workerd = import "/workerd/workerd.capnp";

const internalToken :Text = "__OPEN_COMPUTE_INTERNAL_TOKEN__";
const doRouterRpcHost :Text = "__OPEN_COMPUTE_DO_RPC_HOST__";
const bindingToken :Text = "__OPEN_COMPUTE_BINDING_TOKEN__";
const observabilityToken :Text = "__OPEN_COMPUTE_OBSERVABILITY_TOKEN__";
const doMaxObjectNameBytes :Text = "__OPEN_COMPUTE_DO_MAX_OBJECT_NAME_BYTES__";
const doMaxFetchBodyBytes :Text = "__OPEN_COMPUTE_DO_MAX_FETCH_BODY_BYTES__";
const doDispatchTimeoutMs :Text = "__OPEN_COMPUTE_DO_DISPATCH_TIMEOUT_MS__";
const doMaxInFlightDispatches :Text = "__OPEN_COMPUTE_DO_MAX_IN_FLIGHT_DISPATCHES__";
const doDiskStopWritesPercent :Text = "__OPEN_COMPUTE_DO_DISK_STOP_WRITES_PERCENT__";
const systemCompatibilityDate :Text = "__OPEN_COMPUTE_SYSTEM_COMPATIBILITY_DATE__";
const systemCompatibilityFlagsJson :Text = "__OPEN_COMPUTE_SYSTEM_COMPATIBILITY_FLAGS_JSON__";

const runtimeExtensions :List(Workerd.Extension) = [(modules = [
    (name = "cloudflare-internal:open-compute-do-id", internal = true,
      esModule = embed "dist/durable-objects/native-id.js"),
    (name = "cloudflare-internal:open-compute-host-policy", internal = true,
      esModule = embed "dist/loader/host-policy.js"),
    (name = "cloudflare-internal:open-compute-forwarding", internal = true,
      esModule = embed "dist/loader/forwarding.js"),
    (name = "open-compute:worker-loader", esModule = embed "dist/loader/worker-loader.js"),
    (name = "cloudflare-internal:open-compute-vectorize", internal = true,
      esModule = embed "dist/vectorize/facade.js"),
    (name = "cloudflare-internal:open-compute-browser", internal = true,
      esModule = embed "dist/browser/facade.js"),
    (name = "cloudflare-internal:open-compute-images", internal = true,
      esModule = embed "dist/images/facade.js"),
    (name = "cloudflare-internal:open-compute-ai", internal = true,
      esModule = embed "dist/ai/facade.js"),
    (name = "cloudflare-internal:open-compute-artifacts", internal = true,
      esModule = embed "dist/artifacts/facade.js"),
    (name = "cloudflare-internal:open-compute-assets", internal = true,
      esModule = embed "dist/assets/facade.js"),
    (name = "cloudflare-internal:open-compute-ai-search-namespace", internal = true,
      esModule = embed "dist/ai-search/namespace-binding.js"),
    (name = "cloudflare-internal:open-compute-ai-search-instance", internal = true,
      esModule = embed "dist/ai-search/instance-binding.js"),
  ])];

const config :Workerd.Config = (
  structuredLogging = true,
  extensions = .runtimeExtensions,
  services = [
    (name = "ingress", worker = .ingressWorker),
    (name = "loader-host", worker = .loaderHostWorker),
    (name = "browser-actions", worker = .browserActionsWorker),
    (name = "do-router", worker = .doHostWorker),
    (name = "do-storage", disk = (writable = true, allowDotfiles = true)),
    # The address is deliberately omitted from the compiled config. ocd
    # injects a generation-local loopback listener with --external-addr.
    (name = "runtime-source", external = (http = ())),
    (name = "binding-backend", external = (http = ())),
    (name = "observability-backend", external = (http = ())),
    (name = "outbound-network", network = (
      allow = ["network", "local"],
      deny = ["unix", "unix-abstract"],
      tlsOptions = (trustBrowserCas = true),
    )),
  ],

  sockets = [
    (name = "http", address = "127.0.0.1:0", http = (capnpConnectHost = .doRouterRpcHost), service = "ingress"),
  ],
);

# One-shot Python preparation delegates DO capabilities to the running instance.
# This process has no Durable Object namespace, disk service, or storage directory.
const prepareConfig :Workerd.Config = (
  structuredLogging = true,
  extensions = .runtimeExtensions,
  services = [
    (name = "ingress", worker = .ingressWorker),
    (name = "loader-host", worker = .loaderHostWorker),
    (name = "browser-actions", worker = .browserActionsWorker),
    (name = "do-router", external = (http = (
      capnpConnectHost = .doRouterRpcHost,
      injectRequestHeaders = [(name = "x-open-compute-internal-token", value = .internalToken)],
    ))),
    (name = "runtime-source", external = (http = ())),
    (name = "binding-backend", external = (http = ())),
    (name = "observability-backend", external = (http = ())),
    (name = "outbound-network", network = (
      allow = ["network", "local"],
      deny = ["unix", "unix-abstract"],
      tlsOptions = (trustBrowserCas = true),
    )),
  ],
  sockets = [
    (name = "http", address = "127.0.0.1:0", http = (), service = "ingress"),
  ],
);

const ingressWorker :Workerd.Worker = (
  compatibilityDate = .systemCompatibilityDate,
  compatibilityFlags = __OPEN_COMPUTE_SYSTEM_COMPATIBILITY_FLAGS__,
  modules = [
    (name = "gateway/ingress.js", esModule = embed "dist/gateway/ingress.js"),
    (name = "gateway/token.js", esModule = embed "dist/gateway/token.js"),
    (name = "sockets/tunnel.js", esModule = embed "dist/sockets/tunnel.js"),
  ],
  bindings = [
    (name = "INTERNAL_TOKEN", text = .internalToken),
    (name = "LOADER_HOST", service = "loader-host"),
    (name = "BROWSER_ACTIONS", service = "browser-actions"),
    (name = "DO_ROUTER", service = "do-router"),
  ],
  globalOutbound = "outbound-network",
);

const loaderHostWorker :Workerd.Worker = (
  compatibilityDate = .systemCompatibilityDate,
  compatibilityFlags = __OPEN_COMPUTE_SYSTEM_COMPATIBILITY_FLAGS__,
  modules = [
    (name = "loader/host.js", esModule = embed "dist/loader/host.js"),
    (name = "loader/python-prepare.js", esModule = embed "dist/loader/python-prepare.js"),
    (name = "loader/python-snapshot.js", esModule = embed "dist/loader/python-snapshot.js"),
    (name = "gateway/token.js", esModule = embed "dist/gateway/token.js"),
    (name = "loader/dispatch.js", esModule = embed "dist/loader/dispatch.js"),
    (name = "loader/envelope.js", esModule = embed "dist/loader/envelope.js"),
    (name = "loader/transports.js", esModule = embed "dist/loader/transports.js"),
    (name = "durable-objects/identity.js", esModule = embed "dist/durable-objects/identity.js"),
    (name = "loader/namespaces.js", esModule = embed "dist/loader/namespaces.js"),
    (name = "loader/shared.js", esModule = embed "dist/loader/shared.js"),
    (name = "private-weak-map.js", esModule = embed "dist/private-weak-map.js"),
    (name = "bindings/private-transport.js", esModule = embed "dist/bindings/private-transport.js"),
    (name = "bindings/rpc-disposal.js", esModule = embed "dist/bindings/rpc-disposal.js"),
    (name = "cache/host.js", esModule = embed "dist/cache/host.js"),
    (name = "cache/native-adapter.js", esModule = embed "dist/cache/native-adapter.js"),
    (name = "browser/host.js", esModule = embed "dist/browser/host.js"),
    (name = "images/host.js", esModule = embed "dist/images/host.js"),
    (name = "ai/host.js", esModule = embed "dist/ai/host.js"),
    (name = "vectorize/host.js", esModule = embed "dist/vectorize/host.js"),
    (name = "ai-search/host.js", esModule = embed "dist/ai-search/host.js"),
    (name = "observability/collector.js", esModule = embed "dist/observability/collector.js"),
    (name = "services/capabilities.js", esModule = embed "dist/services/capabilities.js"),
    (name = "services/capability-transfer.js", esModule = embed "dist/services/capability-transfer.js"),
    (name = "services/control.js", esModule = embed "dist/services/control.js"),
    (name = "services/deadline.js", esModule = embed "dist/services/deadline.js"),
    (name = "services/rpc-member.js", esModule = embed "dist/services/rpc-member.js"),
    (name = "services/facade.js", esModule = embed "dist/services/facade.js"),
    (name = "services/scope.js", esModule = embed "dist/services/scope.js"),
    (name = "services/transport.js", esModule = embed "dist/services/transport.js"),
    (name = "assets/router.js", esModule = embed "dist/assets/router.js"),
    (name = "workflows/host.js", esModule = embed "dist/workflows/host.js"),
    (name = "workflows/controller.js", esModule = embed "dist/workflows/controller.js"),
    (name = "loader/policy.js", esModule = embed "dist/loader/policy.js"),
    (name = "loader/modules.js", esModule = embed "dist/loader/modules.js"),
    (name = "loader/module-values.js", esModule = embed "dist/loader/module-values.js"),
    (name = "loader/snapshot.js", esModule = embed "dist/loader/snapshot.js"),
    (name = "kv/transport.js", esModule = embed "dist/kv/transport.js"),
    (name = "kv/native-adapter.js", esModule = embed "dist/kv/native-adapter.js"),
    (name = "bindings/json-body.js", esModule = embed "dist/bindings/json-body.js"),
    (name = "artifacts/transport.js", esModule = embed "dist/artifacts/transport.js"),
    (name = "serialization/codec.js", esModule = embed "dist/serialization/codec.js"),
    (name = "serialization/encode.js", esModule = embed "dist/serialization/encode.js"),
    (name = "serialization/decode.js", esModule = embed "dist/serialization/decode.js"),
    (name = "serialization/format.js", esModule = embed "dist/serialization/format.js"),
    (name = "queues/native-adapter.js", esModule = embed "dist/queues/native-adapter.js"),
    (name = "queues/transport.js", esModule = embed "dist/queues/transport.js"),
    (name = "queues/frame.js", esModule = embed "dist/queues/frame.js"),
    (name = "queues/metrics.js", esModule = embed "dist/queues/metrics.js"),
    (name = "workflows/binding.js", esModule = embed "dist/workflows/binding.js"),
    (name = "workflows/codec.js", esModule = embed "dist/workflows/codec.js"),
    (name = "loader/bindings.js", esModule = embed "dist/loader/bindings.js"),
    (name = "bindings/native-construction.js", esModule = embed "dist/bindings/native-construction.js"),
    (name = "r2/transport.js", esModule = embed "dist/r2/transport.js"),
    (name = "r2/native-adapter.js", esModule = embed "dist/r2/native-adapter.js"),
    (name = "r2/validation.js", esModule = embed "dist/r2/validation.js"),
    (name = "d1/transport.js", esModule = embed "dist/d1/transport.js"),
    (name = "d1/native-adapter.js", esModule = embed "dist/d1/native-adapter.js"),
    (name = "d1/validation.js", esModule = embed "dist/d1/validation.js"),
    (name = "sockets/tunnel.js", esModule = embed "dist/sockets/tunnel.js"),
  ],
  bindings = [
    (name = "LOADER", workerLoader = (id = "open-compute", inheritTails = true)),
    (name = "WORKER_LOADER_FACTORY", workerLoader = (id = "open-compute-public", factory = true)),
    (name = "HOST_EXTENSION_FACTORY", hostExtensionFactory = void),
    (name = "QUEUE_WIRE_CODEC", openComputeQueueCodec = void),
    (name = "RUNTIME_SOURCE", service = "runtime-source"),
    (name = "BINDING_BACKEND", service = "binding-backend"),
    (name = "BINDING_BACKEND_TOKEN", text = .bindingToken),
    (name = "OBSERVABILITY_BACKEND", service = "observability-backend"),
    (name = "OBSERVABILITY_BACKEND_TOKEN", text = .observabilityToken),
    (name = "INTERNAL_TOKEN", text = .internalToken),
    (name = "DO_ROUTER", service = "do-router"),
    (name = "OUTBOUND_NETWORK", service = "outbound-network"),
    (name = "DO_MAX_OBJECT_NAME_BYTES", text = .doMaxObjectNameBytes),
    (name = "DO_MAX_FETCH_BODY_BYTES", text = .doMaxFetchBodyBytes),
    (name = "DO_DISPATCH_TIMEOUT_MS", text = .doDispatchTimeoutMs),
    (name = "DO_MAX_IN_FLIGHT_DISPATCHES", text = .doMaxInFlightDispatches),
    (name = "SYSTEM_COMPATIBILITY_DATE", text = .systemCompatibilityDate),
    (name = "SYSTEM_COMPATIBILITY_FLAGS", json = .systemCompatibilityFlagsJson),
  ],
  cacheApiOutbound = (name = "loader-host", entrypoint = "CacheWriteTransport"),
  globalOutbound = "outbound-network",
);

const doHostWorker :Workerd.Worker = (
  compatibilityDate = .systemCompatibilityDate,
  compatibilityFlags = __OPEN_COMPUTE_SYSTEM_COMPATIBILITY_FLAGS__,
  modules = [
    (name = "durable-objects/router.js", esModule = embed "dist/durable-objects/router.js"),
    (name = "durable-objects/admission.js", esModule = embed "dist/durable-objects/admission.js"),
    (name = "durable-objects/errors.js", esModule = embed "dist/durable-objects/errors.js"),
    (name = "durable-objects/host.js", esModule = embed "dist/durable-objects/host.js"),
    (name = "durable-objects/facet-manager.js", esModule = embed "dist/durable-objects/facet-manager.js"),
    (name = "durable-objects/host-protocol.js", esModule = embed "dist/durable-objects/host-protocol.js"),
    (name = "durable-objects/identity.js", esModule = embed "dist/durable-objects/identity.js"),
    (name = "loader/host.js", esModule = embed "dist/loader/host.js"),
    (name = "gateway/token.js", esModule = embed "dist/gateway/token.js"),
    (name = "loader/python-prepare.js", esModule = embed "dist/loader/python-prepare.js"),
    (name = "loader/python-snapshot.js", esModule = embed "dist/loader/python-snapshot.js"),
    (name = "loader/dispatch.js", esModule = embed "dist/loader/dispatch.js"),
    (name = "loader/envelope.js", esModule = embed "dist/loader/envelope.js"),
    (name = "loader/transports.js", esModule = embed "dist/loader/transports.js"),
    (name = "loader/namespaces.js", esModule = embed "dist/loader/namespaces.js"),
    (name = "loader/shared.js", esModule = embed "dist/loader/shared.js"),
    (name = "private-weak-map.js", esModule = embed "dist/private-weak-map.js"),
    (name = "bindings/private-transport.js", esModule = embed "dist/bindings/private-transport.js"),
    (name = "bindings/rpc-disposal.js", esModule = embed "dist/bindings/rpc-disposal.js"),
    (name = "cache/host.js", esModule = embed "dist/cache/host.js"),
    (name = "cache/native-adapter.js", esModule = embed "dist/cache/native-adapter.js"),
    (name = "browser/host.js", esModule = embed "dist/browser/host.js"),
    (name = "images/host.js", esModule = embed "dist/images/host.js"),
    (name = "ai/host.js", esModule = embed "dist/ai/host.js"),
    (name = "vectorize/host.js", esModule = embed "dist/vectorize/host.js"),
    (name = "ai-search/host.js", esModule = embed "dist/ai-search/host.js"),
    (name = "observability/collector.js", esModule = embed "dist/observability/collector.js"),
    (name = "services/capabilities.js", esModule = embed "dist/services/capabilities.js"),
    (name = "services/capability-transfer.js", esModule = embed "dist/services/capability-transfer.js"),
    (name = "services/control.js", esModule = embed "dist/services/control.js"),
    (name = "services/deadline.js", esModule = embed "dist/services/deadline.js"),
    (name = "services/rpc-member.js", esModule = embed "dist/services/rpc-member.js"),
    (name = "services/facade.js", esModule = embed "dist/services/facade.js"),
    (name = "services/scope.js", esModule = embed "dist/services/scope.js"),
    (name = "services/transport.js", esModule = embed "dist/services/transport.js"),
    (name = "assets/router.js", esModule = embed "dist/assets/router.js"),
    (name = "workflows/host.js", esModule = embed "dist/workflows/host.js"),
    (name = "workflows/controller.js", esModule = embed "dist/workflows/controller.js"),
    (name = "loader/policy.js", esModule = embed "dist/loader/policy.js"),
    (name = "loader/modules.js", esModule = embed "dist/loader/modules.js"),
    (name = "loader/module-values.js", esModule = embed "dist/loader/module-values.js"),
    (name = "loader/snapshot.js", esModule = embed "dist/loader/snapshot.js"),
    (name = "kv/transport.js", esModule = embed "dist/kv/transport.js"),
    (name = "kv/native-adapter.js", esModule = embed "dist/kv/native-adapter.js"),
    (name = "bindings/json-body.js", esModule = embed "dist/bindings/json-body.js"),
    (name = "artifacts/transport.js", esModule = embed "dist/artifacts/transport.js"),
    (name = "serialization/codec.js", esModule = embed "dist/serialization/codec.js"),
    (name = "serialization/encode.js", esModule = embed "dist/serialization/encode.js"),
    (name = "serialization/decode.js", esModule = embed "dist/serialization/decode.js"),
    (name = "serialization/format.js", esModule = embed "dist/serialization/format.js"),
    (name = "queues/native-adapter.js", esModule = embed "dist/queues/native-adapter.js"),
    (name = "queues/transport.js", esModule = embed "dist/queues/transport.js"),
    (name = "queues/frame.js", esModule = embed "dist/queues/frame.js"),
    (name = "queues/metrics.js", esModule = embed "dist/queues/metrics.js"),
    (name = "workflows/binding.js", esModule = embed "dist/workflows/binding.js"),
    (name = "workflows/codec.js", esModule = embed "dist/workflows/codec.js"),
    (name = "loader/bindings.js", esModule = embed "dist/loader/bindings.js"),
    (name = "bindings/native-construction.js", esModule = embed "dist/bindings/native-construction.js"),
    (name = "r2/transport.js", esModule = embed "dist/r2/transport.js"),
    (name = "r2/native-adapter.js", esModule = embed "dist/r2/native-adapter.js"),
    (name = "r2/validation.js", esModule = embed "dist/r2/validation.js"),
    (name = "d1/transport.js", esModule = embed "dist/d1/transport.js"),
    (name = "d1/native-adapter.js", esModule = embed "dist/d1/native-adapter.js"),
    (name = "d1/validation.js", esModule = embed "dist/d1/validation.js"),
    (name = "sockets/tunnel.js", esModule = embed "dist/sockets/tunnel.js"),
  ],
  bindings = [
    (name = "LOADER", workerLoader = (id = "open-compute", inheritTails = true)),
    (name = "WORKER_LOADER_FACTORY", workerLoader = (id = "open-compute-public", factory = true)),
    (name = "HOST_EXTENSION_FACTORY", hostExtensionFactory = void),
    (name = "QUEUE_WIRE_CODEC", openComputeQueueCodec = void),
    (name = "RUNTIME_SOURCE", service = "runtime-source"),
    (name = "BINDING_BACKEND", service = "binding-backend"),
    (name = "BINDING_BACKEND_TOKEN", text = .bindingToken),
    (name = "OBSERVABILITY_BACKEND", service = "observability-backend"),
    (name = "OBSERVABILITY_BACKEND_TOKEN", text = .observabilityToken),
    (name = "INTERNAL_TOKEN", text = .internalToken),
    (name = "DO_ROUTER", service = "do-router"),
    (name = "DO_HOST", durableObjectNamespace = "DoHost"),
    (name = "NATIVE_DO_ID", wrapped = (moduleName = "cloudflare-internal:open-compute-do-id")),
    (name = "OUTBOUND_NETWORK", service = "outbound-network"),
    (name = "DO_MAX_OBJECT_NAME_BYTES", text = .doMaxObjectNameBytes),
    (name = "DO_MAX_FETCH_BODY_BYTES", text = .doMaxFetchBodyBytes),
    (name = "DO_DISPATCH_TIMEOUT_MS", text = .doDispatchTimeoutMs),
    (name = "DO_MAX_IN_FLIGHT_DISPATCHES", text = .doMaxInFlightDispatches),
    (name = "DO_DISK_STOP_WRITES_PERCENT", text = .doDiskStopWritesPercent),
    (name = "SYSTEM_COMPATIBILITY_DATE", text = .systemCompatibilityDate),
    (name = "SYSTEM_COMPATIBILITY_FLAGS", json = .systemCompatibilityFlagsJson),
  ],
  durableObjectNamespaces = [
    (
      className = "DoHost",
      uniqueKey = "open-compute-do-host-v1",
      enableSql = true,
    ),
  ],
  durableObjectStorage = (localDisk = "do-storage"),
  cacheApiOutbound = (name = "do-router", entrypoint = "CacheWriteTransport"),
  globalOutbound = "outbound-network",
);

const browserActionsWorker :Workerd.Worker = (
  compatibilityDate = .systemCompatibilityDate,
  compatibilityFlags = ["nodejs_compat"],
  globalOutbound = (name = "ingress", entrypoint = "NoOutbound"),
  modules = [(name = "browser/actions.js", esModule = embed "dist/browser/actions.js")],
  bindings = [
    (name = "BINDING_BACKEND", service = "binding-backend"),
    (name = "BINDING_BACKEND_TOKEN", text = .bindingToken),
    (name = "INTERNAL_TOKEN", text = .internalToken),
  ],
);
