using Workerd = import "/workerd/workerd.capnp";

const internalToken :Text = "__OPEN_COMPUTE_INTERNAL_TOKEN__";
const bindingToken :Text = "__OPEN_COMPUTE_BINDING_TOKEN__";
const doMaxObjectNameBytes :Text = "__OPEN_COMPUTE_DO_MAX_OBJECT_NAME_BYTES__";
const doMaxFetchBodyBytes :Text = "__OPEN_COMPUTE_DO_MAX_FETCH_BODY_BYTES__";
const doDispatchTimeoutMs :Text = "__OPEN_COMPUTE_DO_DISPATCH_TIMEOUT_MS__";
const doMaxInFlightDispatches :Text = "__OPEN_COMPUTE_DO_MAX_IN_FLIGHT_DISPATCHES__";
const doDiskStopWritesPercent :Text = "__OPEN_COMPUTE_DO_DISK_STOP_WRITES_PERCENT__";
const compatibilityDate :Text = "__OPEN_COMPUTE_COMPATIBILITY_DATE__";
const requiredCompatibilityFlagsJson :Text = "__OPEN_COMPUTE_REQUIRED_COMPATIBILITY_FLAGS_JSON__";

const config :Workerd.Config = (
  structuredLogging = true,

  services = [
    (name = "ingress", worker = .ingressWorker),
    (name = "loader-host", worker = .loaderHostWorker),
    (name = "do-router", worker = .doHostWorker),
    (name = "do-storage", disk = (writable = true, allowDotfiles = true)),
    # The address is deliberately omitted from the compiled config. platformd
    # injects a generation-local loopback listener with --external-addr.
    (name = "runtime-source", external = (http = ())),
    (name = "binding-backend", external = (http = ())),
    (name = "internet", network = (
      allow = ["public"],
      tlsOptions = (trustBrowserCas = true),
    )),
  ],

  sockets = [
    (name = "http", address = "127.0.0.1:0", http = (), service = "ingress"),
  ],
);

const ingressWorker :Workerd.Worker = (
  compatibilityDate = .compatibilityDate,
  compatibilityFlags = __OPEN_COMPUTE_SYSTEM_COMPATIBILITY_FLAGS__,
  modules = [
    (name = "gateway/ingress.js", esModule = embed "dist/gateway/ingress.js"),
  ],
  bindings = [
    (name = "INTERNAL_TOKEN", text = .internalToken),
    (name = "LOADER_HOST", service = "loader-host"),
    (name = "DO_ROUTER", service = "do-router"),
  ],
  globalOutbound = "internet",
);

const loaderHostWorker :Workerd.Worker = (
  compatibilityDate = .compatibilityDate,
  compatibilityFlags = __OPEN_COMPUTE_SYSTEM_COMPATIBILITY_FLAGS__,
  modules = [
    (name = "loader/host.js", esModule = embed "dist/loader/host.js"),
    (name = "loader/shared.js", esModule = embed "dist/loader/shared.js"),
    (name = "bindings/private-transport.js", esModule = embed "dist/bindings/private-transport.js"),
    (name = "cache/host.js", esModule = embed "dist/cache/host.js"),
    (name = "images/host.js", esModule = embed "dist/images/host.js"),
    (name = "services/transport.js", esModule = embed "dist/services/transport.js"),
    (name = "assets/router.js", esModule = embed "dist/assets/router.js"),
    (name = "workflows/host.js", esModule = embed "dist/workflows/host.js"),
    (name = "workflows/controller.js", esModule = embed "dist/workflows/controller.js"),
    (name = "loader/modules.js", esModule = embed "dist/loader/modules.js"),
    (name = "loader/snapshot.js", esModule = embed "dist/loader/snapshot.js"),
    (name = "kv/transport.js", esModule = embed "dist/kv/transport.js"),
    (name = "loader/wrapper-runtime-source", text = embed "dist/loader/wrappers/runtime.js"),
    (name = "loader/do-wrapper-source", text = embed "dist/loader/wrappers/durable-object.js"),
    (name = "loader/workflow-wrapper-source", text = embed "dist/loader/wrappers/workflow.js"),
    (name = "loader/workflow-runner-source", text = embed "dist/workflows/runner.js"),
    (name = "loader/workflow-duration-source", text = embed "dist/workflows/duration.js"),
    (name = "loader/workflow-codec-source", text = embed "dist/workflows/codec.js"),
    (name = "loader/workflow-facade-source", text = embed "dist/workflows/facade.js"),
    (name = "loader/kv-facade-source", text = embed "dist/kv/facade.js"),
    (name = "loader/r2-facade-source", text = embed "dist/r2/facade.js"),
    (name = "loader/d1-facade-source", text = embed "dist/d1/facade.js"),
    (name = "loader/do-facade-source", text = embed "dist/durable-objects/facade.js"),
    (name = "loader/do-id-codec-source", text = embed "dist/durable-objects/id-codec.js"),
    (name = "loader/do-alarm-shim-source", text = embed "dist/durable-objects/alarm-shim.js"),
    (name = "loader/do-output-gate-source", text = embed "dist/durable-objects/output-gate.js"),
    (name = "loader/do-facets-source", text = embed "dist/durable-objects/facets.js"),
    (name = "loader/queue-facade-source", text = embed "dist/queues/facade.js"),
    (name = "loader/serialization-codec-source", text = embed "dist/serialization/codec.js"),
    (name = "loader/serialization-encode-source", text = embed "dist/serialization/encode.js"),
    (name = "loader/serialization-decode-source", text = embed "dist/serialization/decode.js"),
    (name = "loader/serialization-format-source", text = embed "dist/serialization/format.js"),
    (name = "serialization/codec.js", esModule = embed "dist/serialization/codec.js"),
    (name = "serialization/encode.js", esModule = embed "dist/serialization/encode.js"),
    (name = "serialization/decode.js", esModule = embed "dist/serialization/decode.js"),
    (name = "serialization/format.js", esModule = embed "dist/serialization/format.js"),
    (name = "loader/assets-facade-source", text = embed "dist/assets/facade.js"),
    (name = "loader/service-facade-source", text = embed "dist/services/facade.js"),
    (name = "loader/service-scope-source", text = embed "dist/services/scope.js"),
    (name = "loader/socket-tunnel-source", text = embed "dist/sockets/tunnel.js"),
    (name = "loader/cache-facade-source", text = embed "dist/cache/facade.js"),
    (name = "loader/images-facade-source", text = embed "dist/images/facade.js"),
    (name = "loader/wrappers/generator.js", esModule = embed "dist/loader/wrappers/generator.js"),
    (name = "workflows/binding.js", esModule = embed "dist/workflows/binding.js"),
    (name = "workflows/codec.js", esModule = embed "dist/workflows/codec.js"),
    (name = "loader/bindings.js", esModule = embed "dist/loader/bindings.js"),
    (name = "r2/transport.js", esModule = embed "dist/r2/transport.js"),
    (name = "d1/transport.js", esModule = embed "dist/d1/transport.js"),
    (name = "sockets/tunnel.js", esModule = embed "dist/sockets/tunnel.js"),
  ],
  bindings = [
    (name = "LOADER", workerLoader = (id = "open-compute")),
    (name = "RUNTIME_SOURCE", service = "runtime-source"),
    (name = "BINDING_BACKEND", service = "binding-backend"),
    (name = "BINDING_BACKEND_TOKEN", text = .bindingToken),
    (name = "INTERNAL_TOKEN", text = .internalToken),
    (name = "DO_ROUTER", service = "do-router"),
    (name = "PUBLIC_NETWORK", service = "internet"),
    (name = "DO_MAX_OBJECT_NAME_BYTES", text = .doMaxObjectNameBytes),
    (name = "DO_MAX_FETCH_BODY_BYTES", text = .doMaxFetchBodyBytes),
    (name = "DO_DISPATCH_TIMEOUT_MS", text = .doDispatchTimeoutMs),
    (name = "DO_MAX_IN_FLIGHT_DISPATCHES", text = .doMaxInFlightDispatches),
    (name = "COMPATIBILITY_DATE", text = .compatibilityDate),
    (name = "REQUIRED_COMPATIBILITY_FLAGS", json = .requiredCompatibilityFlagsJson),
  ],
  globalOutbound = "internet",
);

const doHostWorker :Workerd.Worker = (
  compatibilityDate = .compatibilityDate,
  compatibilityFlags = __OPEN_COMPUTE_SYSTEM_COMPATIBILITY_FLAGS__,
  modules = [
    (name = "durable-objects/router.js", esModule = embed "dist/durable-objects/router.js"),
    (name = "durable-objects/host.js", esModule = embed "dist/durable-objects/host.js"),
    (name = "loader/host.js", esModule = embed "dist/loader/host.js"),
    (name = "loader/shared.js", esModule = embed "dist/loader/shared.js"),
    (name = "bindings/private-transport.js", esModule = embed "dist/bindings/private-transport.js"),
    (name = "cache/host.js", esModule = embed "dist/cache/host.js"),
    (name = "images/host.js", esModule = embed "dist/images/host.js"),
    (name = "services/transport.js", esModule = embed "dist/services/transport.js"),
    (name = "assets/router.js", esModule = embed "dist/assets/router.js"),
    (name = "workflows/host.js", esModule = embed "dist/workflows/host.js"),
    (name = "workflows/controller.js", esModule = embed "dist/workflows/controller.js"),
    (name = "loader/modules.js", esModule = embed "dist/loader/modules.js"),
    (name = "loader/snapshot.js", esModule = embed "dist/loader/snapshot.js"),
    (name = "kv/transport.js", esModule = embed "dist/kv/transport.js"),
    (name = "loader/wrapper-runtime-source", text = embed "dist/loader/wrappers/runtime.js"),
    (name = "loader/do-wrapper-source", text = embed "dist/loader/wrappers/durable-object.js"),
    (name = "loader/workflow-wrapper-source", text = embed "dist/loader/wrappers/workflow.js"),
    (name = "loader/workflow-runner-source", text = embed "dist/workflows/runner.js"),
    (name = "loader/workflow-duration-source", text = embed "dist/workflows/duration.js"),
    (name = "loader/workflow-codec-source", text = embed "dist/workflows/codec.js"),
    (name = "loader/workflow-facade-source", text = embed "dist/workflows/facade.js"),
    (name = "loader/kv-facade-source", text = embed "dist/kv/facade.js"),
    (name = "loader/r2-facade-source", text = embed "dist/r2/facade.js"),
    (name = "loader/d1-facade-source", text = embed "dist/d1/facade.js"),
    (name = "loader/do-facade-source", text = embed "dist/durable-objects/facade.js"),
    (name = "loader/do-id-codec-source", text = embed "dist/durable-objects/id-codec.js"),
    (name = "loader/do-alarm-shim-source", text = embed "dist/durable-objects/alarm-shim.js"),
    (name = "loader/do-output-gate-source", text = embed "dist/durable-objects/output-gate.js"),
    (name = "loader/do-facets-source", text = embed "dist/durable-objects/facets.js"),
    (name = "loader/queue-facade-source", text = embed "dist/queues/facade.js"),
    (name = "loader/serialization-codec-source", text = embed "dist/serialization/codec.js"),
    (name = "loader/serialization-encode-source", text = embed "dist/serialization/encode.js"),
    (name = "loader/serialization-decode-source", text = embed "dist/serialization/decode.js"),
    (name = "loader/serialization-format-source", text = embed "dist/serialization/format.js"),
    (name = "serialization/codec.js", esModule = embed "dist/serialization/codec.js"),
    (name = "serialization/encode.js", esModule = embed "dist/serialization/encode.js"),
    (name = "serialization/decode.js", esModule = embed "dist/serialization/decode.js"),
    (name = "serialization/format.js", esModule = embed "dist/serialization/format.js"),
    (name = "loader/assets-facade-source", text = embed "dist/assets/facade.js"),
    (name = "loader/service-facade-source", text = embed "dist/services/facade.js"),
    (name = "loader/service-scope-source", text = embed "dist/services/scope.js"),
    (name = "loader/socket-tunnel-source", text = embed "dist/sockets/tunnel.js"),
    (name = "loader/cache-facade-source", text = embed "dist/cache/facade.js"),
    (name = "loader/images-facade-source", text = embed "dist/images/facade.js"),
    (name = "loader/wrappers/generator.js", esModule = embed "dist/loader/wrappers/generator.js"),
    (name = "workflows/binding.js", esModule = embed "dist/workflows/binding.js"),
    (name = "workflows/codec.js", esModule = embed "dist/workflows/codec.js"),
    (name = "loader/bindings.js", esModule = embed "dist/loader/bindings.js"),
    (name = "r2/transport.js", esModule = embed "dist/r2/transport.js"),
    (name = "d1/transport.js", esModule = embed "dist/d1/transport.js"),
    (name = "sockets/tunnel.js", esModule = embed "dist/sockets/tunnel.js"),
  ],
  bindings = [
    (name = "LOADER", workerLoader = (id = "open-compute")),
    (name = "RUNTIME_SOURCE", service = "runtime-source"),
    (name = "BINDING_BACKEND", service = "binding-backend"),
    (name = "BINDING_BACKEND_TOKEN", text = .bindingToken),
    (name = "INTERNAL_TOKEN", text = .internalToken),
    (name = "DO_ROUTER", service = "do-router"),
    (name = "DO_HOST", durableObjectNamespace = "DoHost"),
    (name = "PUBLIC_NETWORK", service = "internet"),
    (name = "DO_MAX_OBJECT_NAME_BYTES", text = .doMaxObjectNameBytes),
    (name = "DO_MAX_FETCH_BODY_BYTES", text = .doMaxFetchBodyBytes),
    (name = "DO_DISPATCH_TIMEOUT_MS", text = .doDispatchTimeoutMs),
    (name = "DO_MAX_IN_FLIGHT_DISPATCHES", text = .doMaxInFlightDispatches),
    (name = "DO_DISK_STOP_WRITES_PERCENT", text = .doDiskStopWritesPercent),
    (name = "COMPATIBILITY_DATE", text = .compatibilityDate),
    (name = "REQUIRED_COMPATIBILITY_FLAGS", json = .requiredCompatibilityFlagsJson),
  ],
  durableObjectNamespaces = [
    (
      className = "DoHost",
      uniqueKey = "open-compute-do-host-v1",
      enableSql = true,
    ),
  ],
  durableObjectStorage = (localDisk = "do-storage"),
  globalOutbound = "internet",
);
