use super::*;

pub(super) fn refuse_nonempty_data(path: &Path) -> Result<(), PlatformError> {
    match fs::symlink_metadata(path) {
        Ok(meta) if meta.is_dir() && !meta.file_type().is_symlink() => {
            if meta.uid() != rustix::process::getuid().as_raw()
                || meta.permissions().mode() & 0o777 != 0o700
            {
                return Err(PlatformError::new(
                    ErrorCode::PathInvalid,
                    "setup data directory must be private and owned by the caller",
                ));
            }
            if fs::read_dir(path)
                .map_err(|_| {
                    PlatformError::new(
                        ErrorCode::PathInvalid,
                        "cannot inspect setup data directory",
                    )
                })?
                .next()
                .is_some()
            {
                return Err(PlatformError::new(
                    ErrorCode::PathInvalid,
                    "setup data directory must be empty before initialization",
                ));
            }
            Ok(())
        }
        Ok(_) => Err(PlatformError::new(
            ErrorCode::PathInvalid,
            "setup data path is not an empty directory",
        )),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(_) => Err(PlatformError::new(
            ErrorCode::PathInvalid,
            "cannot inspect setup data directory",
        )),
    }
}

#[allow(
    clippy::too_many_arguments,
    reason = "transport boundary inputs mirror the wire contract"
)]
pub(super) fn prepare_staging(
    plan: &SetupPlan,
    staging_dir: &Path,
    deployer_secret: &Path,
    read_only_secret: &Path,
    master_key_file: &Path,
    objects_dir: &Path,
    startup_cwd: &Path,
) -> Result<(), PlatformError> {
    let config_name = plan
        .config_path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| {
            PlatformError::new(
                ErrorCode::ConfigPathInvalid,
                "setup config path must name a UTF-8 file",
            )
        })?;
    let marker = format!("{SETUP_STAGING_MARKER}{config_name}\n");
    exclusive_write_bytes(
        &staging_dir.join(".owner"),
        marker.as_bytes(),
        0o600,
        plan.scope,
    )?;
    let staging_secrets = staging_dir.join("secrets");
    create_dir_mapped(&staging_secrets, plan.scope)?;

    let (admin, deployer, read_only) = generate_distinct_tokens()?;
    exclusive_write_secret(&staging_secrets.join("admin.token"), &admin, plan.scope)?;
    exclusive_write_secret(
        &staging_secrets.join("deployer.token"),
        &deployer,
        plan.scope,
    )?;
    exclusive_write_secret(
        &staging_secrets.join("read-only.token"),
        &read_only,
        plan.scope,
    )?;

    let mut config = PlatformConfig::from_toml_str(DEFAULT_CONFIG)?;
    config.auth.deployer_auth = SecretReference {
        env: None,
        file: Some(deployer_secret.to_owned()),
    };
    config.auth.read_only_auth = SecretReference {
        env: None,
        file: Some(read_only_secret.to_owned()),
    };
    config.data.path = plan.data_dir.clone();
    config.data.master_key_file = master_key_file.to_owned();
    config.data.master_key_env = None;
    let ObjectStorageConfig::Local(local) = &mut config.object_storage else {
        return Err(PlatformError::new(
            ErrorCode::ConfigInvalid,
            "embedded default config must use local object storage",
        ));
    };
    local.path = objects_dir.to_owned();
    config.dashboard = DashboardConfig {
        enabled: plan.dashboard_enabled,
    };
    config.validate()?;

    let text = format!(
        "# Generated by `ocd setup`. Secrets are file references only.\n{}",
        toml::to_string_pretty(&config).map_err(|_| PlatformError::new(
            ErrorCode::ConfigInvalid,
            "failed to serialize setup configuration",
        ))?
    );
    let staging_config = staging_dir.join(config_name);
    exclusive_write_bytes(&staging_config, text.as_bytes(), 0o600, plan.scope)?;
    let _ = load_platform_config_from(&staging_config, startup_cwd)?;
    Ok(())
}

pub(super) fn publish_exclusive(
    plan: &SetupPlan,
    staging_dir: &Path,
    staging_secrets: &Path,
    admin_secret: &Path,
    deployer_secret: &Path,
    read_only_secret: &Path,
) -> Result<Vec<PublishedFile>, PlatformError> {
    let mut published = Vec::new();
    let result = (|| {
        published.push(publish_file(
            &staging_secrets.join("admin.token"),
            admin_secret,
            plan.scope,
        )?);
        published.push(publish_file(
            &staging_secrets.join("deployer.token"),
            deployer_secret,
            plan.scope,
        )?);
        published.push(publish_file(
            &staging_secrets.join("read-only.token"),
            read_only_secret,
            plan.scope,
        )?);
        let staging_config = staging_dir.join(plan.config_path.file_name().ok_or_else(|| {
            PlatformError::new(
                ErrorCode::ConfigPathInvalid,
                "setup config path must name a regular file",
            )
        })?);
        published.push(publish_file(
            &staging_config,
            &plan.config_path,
            plan.scope,
        )?);
        Ok(())
    })();
    if let Err(error) = result {
        if remove_published_files(&published).is_err() {
            return Err(PlatformError::new(
                ErrorCode::PathInvalid,
                "setup file publication failed and rollback was incomplete",
            ));
        }
        return Err(error);
    }
    Ok(published)
}

pub(super) fn rollback_pre_start(
    published: &[PublishedFile],
    record: Option<&crate::instance_registry::InstanceRecord>,
    service_installed: bool,
    registry: &InstanceRegistry,
    manager: &dyn ServiceManager,
) -> Result<(), PlatformError> {
    if let Some(record) = record {
        if service_installed {
            manager.uninstall(record.service_scope)?;
        }
        registry.remove_record(record)?;
    }
    remove_published_files(published)
}

pub(super) fn remove_published_files(paths: &[PublishedFile]) -> Result<(), PlatformError> {
    let mut failed = false;
    for path in paths.iter().rev() {
        failed |= path.remove_if_same().is_err();
    }
    if failed {
        Err(rollback_error())
    } else {
        Ok(())
    }
}

#[derive(Debug)]
pub(super) struct PublishedFile {
    path: PathBuf,
    device: u64,
    inode: u64,
}

impl PublishedFile {
    fn from_file(path: &Path, file: &fs::File) -> Result<Self, PlatformError> {
        let meta = file.metadata().map_err(|_| {
            PlatformError::new(
                ErrorCode::PathInvalid,
                "failed to inspect a published setup file",
            )
        })?;
        Ok(Self {
            path: path.to_owned(),
            device: meta.dev(),
            inode: meta.ino(),
        })
    }

    fn remove_if_same(&self) -> Result<(), PlatformError> {
        let meta = match fs::symlink_metadata(&self.path) {
            Ok(meta) => meta,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
            Err(_) => return Err(rollback_error()),
        };
        if !meta.is_file() || meta.dev() != self.device || meta.ino() != self.inode {
            return Err(rollback_error());
        }
        fs::remove_file(&self.path).map_err(|_| rollback_error())
    }
}

fn rollback_error() -> PlatformError {
    PlatformError::new(
        ErrorCode::PathInvalid,
        "setup file changed before rollback; refusing to remove it",
    )
}

pub(super) fn assign_system_ownership(
    plan: &SetupPlan,
    service_user: &crate::service_manager::SystemServiceUser,
) -> Result<(), PlatformError> {
    let root = match plan.scope {
        ServiceScope::System => &plan.system_registry_root,
        ServiceScope::User => &plan.user_registry_root,
    };
    assign_path_ownership(root, service_user)?;
    assign_path_ownership(&root.join("ocd.lock"), service_user)?;
    assign_path_ownership(&root.join("keys"), service_user)?;
    assign_path_ownership(&root.join("tmp"), service_user)?;
    assign_path_ownership(&root.join("keys/admin.token"), service_user)?;
    assign_path_ownership(&root.join("instances"), service_user)?;
    if !assign_scoped_ancestors(root, &plan.config_path, service_user)? {
        let parent = plan.config_path.parent().ok_or_else(|| {
            PlatformError::new(ErrorCode::PathInvalid, "setup config path has no parent")
        })?;
        assign_path_ownership(parent, service_user)?;
    }
    assign_scoped_ancestors(root, &plan.data_dir, service_user)?;
    assign_path_ownership(&plan.config_path, service_user)?;
    fs::set_permissions(&plan.config_path, fs::Permissions::from_mode(0o600)).map_err(|_| {
        PlatformError::new(
            ErrorCode::PathInvalid,
            "failed to secure the system configuration",
        )
    })?;
    Ok(())
}

pub(super) fn assign_scoped_ancestors(
    root: &Path,
    path: &Path,
    service_user: &crate::service_manager::SystemServiceUser,
) -> Result<bool, PlatformError> {
    let canonical_root = fs::canonicalize(root).map_err(|_| {
        PlatformError::new(ErrorCode::PathInvalid, "system OCD root is unavailable")
    })?;
    let parent = path
        .parent()
        .ok_or_else(|| PlatformError::new(ErrorCode::PathInvalid, "setup path has no parent"))?;
    let Ok(relative) = parent.strip_prefix(&canonical_root) else {
        return Ok(false);
    };
    let mut directory = canonical_root;
    for component in relative.components() {
        directory.push(component);
        assign_path_ownership(&directory, service_user)?;
    }
    Ok(true)
}

pub(super) fn assign_path_ownership(
    path: &Path,
    service_user: &crate::service_manager::SystemServiceUser,
) -> Result<(), PlatformError> {
    let invalid = || {
        PlatformError::new(
            ErrorCode::PathInvalid,
            "failed to assign setup files to the non-root service user",
        )
    };
    if service_user.uid == u32::MAX || service_user.gid == u32::MAX {
        return Err(invalid());
    }
    let metadata = fs::symlink_metadata(path).map_err(|_| invalid())?;
    if !metadata.is_dir() && !metadata.is_file() {
        return Err(invalid());
    }
    let mut flags =
        rustix::fs::OFlags::RDONLY | rustix::fs::OFlags::NOFOLLOW | rustix::fs::OFlags::CLOEXEC;
    if metadata.is_dir() {
        flags |= rustix::fs::OFlags::DIRECTORY;
    }
    let fd = rustix::fs::open(path, flags, rustix::fs::Mode::empty()).map_err(|_| invalid())?;
    let opened = rustix::fs::fstat(&fd).map_err(|_| invalid())?;
    // rustix st_dev width differs by OS; Metadata::dev is always u64.
    if opened.st_dev as u64 != metadata.dev() || opened.st_ino != metadata.ino() {
        return Err(invalid());
    }
    rustix::fs::fchown(
        &fd,
        Some(rustix::fs::Uid::from_raw(service_user.uid)),
        Some(rustix::fs::Gid::from_raw(service_user.gid)),
    )
    .map_err(|_| invalid())
}

pub(super) fn assign_initialized_data_ownership(
    root: &Path,
    service_user: &crate::service_manager::SystemServiceUser,
) -> Result<(), PlatformError> {
    const DIRS: &[&str] = &[
        "keys",
        "objects",
        "runtime",
        "tmp",
        "cache",
        "cache/artifacts",
        "cache/artifacts/sha256",
        "artifacts",
        "artifacts/git",
        "artifacts/quarantine",
        "version-staging",
        "backup-staging",
        "diagnostics",
        "diagnostics/failed-starts",
    ];
    const FILES: &[&str] = &[
        "keys/deployer.token",
        "keys/read-only.token",
        "keys/master.key",
        "platform.lock",
        "control.sqlite",
        "control.sqlite-wal",
        "control.sqlite-shm",
    ];
    fn collect(
        root: &Path,
        current: &Path,
        device: u64,
        paths: &mut Vec<PathBuf>,
    ) -> Result<(), PlatformError> {
        for entry in fs::read_dir(current).map_err(|_| setup_data_invalid())? {
            let path = entry.map_err(|_| setup_data_invalid())?.path();
            let relative = path.strip_prefix(root).map_err(|_| setup_data_invalid())?;
            let name = relative.to_str().ok_or_else(setup_data_invalid)?;
            let metadata = fs::symlink_metadata(&path).map_err(|_| setup_data_invalid())?;
            if metadata.dev() != device || metadata.uid() != rustix::process::getuid().as_raw() {
                return Err(setup_data_invalid());
            }
            if metadata.is_dir()
                && DIRS.contains(&name)
                && metadata.permissions().mode() & 0o777 == 0o700
            {
                collect(root, &path, device, paths)?;
            } else if !metadata.is_file()
                || !FILES.contains(&name)
                || metadata.permissions().mode() & 0o777 != 0o600
            {
                return Err(setup_data_invalid());
            }
            paths.push(path);
        }
        Ok(())
    }
    let metadata = fs::symlink_metadata(root).map_err(|_| setup_data_invalid())?;
    if !metadata.is_dir()
        || metadata.uid() != rustix::process::getuid().as_raw()
        || metadata.permissions().mode() & 0o777 != 0o700
    {
        return Err(setup_data_invalid());
    }
    let mut paths = Vec::new();
    collect(root, root, metadata.dev(), &mut paths)?;
    paths.push(root.to_owned());
    for path in paths {
        assign_path_ownership(&path, service_user)?;
    }
    Ok(())
}

fn setup_data_invalid() -> PlatformError {
    PlatformError::new(
        ErrorCode::PathInvalid,
        "setup data contains an unknown or insecure entry; refusing ownership transfer",
    )
}

pub(super) fn publish_file(
    from: &Path,
    to: &Path,
    scope: ServiceScope,
) -> Result<PublishedFile, PlatformError> {
    refuse_existing(to, "setup target")?;
    let mut source = fs::File::open(from)
        .map_err(|err| map_privilege(&err, scope, "failed to open a staged setup file"))?;
    let mut target = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(to)
        .map_err(|err| map_privilege(&err, scope, "failed to exclusive-create a setup file"))?;
    let published = PublishedFile::from_file(to, &target)?;
    let copied = std::io::copy(&mut source, &mut target).and_then(|_| target.sync_all());
    if let Err(error) = copied {
        drop(target);
        published.remove_if_same()?;
        return Err(map_privilege(
            &error,
            scope,
            "failed to publish a setup file",
        ));
    }
    let _ = fs::remove_file(from);
    Ok(published)
}

pub(super) fn generate_distinct_tokens() -> Result<(String, String, String), PlatformError> {
    let mut tokens = Vec::with_capacity(3);
    while tokens.len() < 3 {
        let candidate = random_token()?;
        if !tokens.iter().any(|existing| existing == &candidate) {
            tokens.push(candidate);
        }
    }
    Ok((tokens.remove(0), tokens.remove(0), tokens.remove(0)))
}

pub(super) fn random_token() -> Result<String, PlatformError> {
    let mut buf = [0u8; TOKEN_BYTES];
    rand::rngs::OsRng.try_fill_bytes(&mut buf).map_err(|_| {
        PlatformError::new(
            ErrorCode::Internal,
            "failed to generate setup Bearer token material",
        )
    })?;
    Ok(hex::encode(buf))
}

pub(super) fn exclusive_write_secret(
    path: &Path,
    value: &str,
    scope: ServiceScope,
) -> Result<PublishedFile, PlatformError> {
    let mut body = value.as_bytes().to_vec();
    body.push(b'\n');
    exclusive_write_bytes(path, &body, 0o600, scope)
}

pub(super) fn exclusive_write_bytes(
    path: &Path,
    contents: &[u8],
    mode: u32,
    scope: ServiceScope,
) -> Result<PublishedFile, PlatformError> {
    refuse_existing(path, "setup target")?;
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(mode)
        .open(path)
        .map_err(|err| map_privilege(&err, scope, "failed to exclusive-create a setup file"))?;
    let published = PublishedFile::from_file(path, &file)?;
    let written = file.write_all(contents).and_then(|()| file.sync_all());
    if let Err(error) = written {
        drop(file);
        published.remove_if_same()?;
        return Err(map_privilege(&error, scope, "failed to write a setup file"));
    }
    Ok(published)
}

pub(super) fn ensure_dir_tree(path: &Path, scope: ServiceScope) -> Result<(), PlatformError> {
    if path.as_os_str().is_empty() {
        return Err(PlatformError::new(
            ErrorCode::PathInvalid,
            "setup directory path is empty",
        ));
    }
    let mut built = PathBuf::new();
    for component in path.components() {
        built.push(component.as_os_str());
        if matches!(
            component,
            std::path::Component::RootDir | std::path::Component::Prefix(_)
        ) {
            continue;
        }
        if built.exists() {
            continue;
        }
        create_dir_mapped(&built, scope)?;
    }
    if path.exists() {
        ensure_dir_secure(path).map_err(|err| {
            if matches!(scope, ServiceScope::System) {
                PlatformError::new(
                    err.code(),
                    "insufficient privileges or insecure setup directory; retry with `sudo ocd setup --yes` when privilege is required",
                )
            } else {
                err
            }
        })?;
    }
    Ok(())
}

pub(super) fn create_dir_mapped(path: &Path, scope: ServiceScope) -> Result<(), PlatformError> {
    match fs::create_dir(path) {
        Ok(()) => {
            fs::set_permissions(path, fs::Permissions::from_mode(0o700)).map_err(|err| {
                map_privilege(&err, scope, "failed to set mode 0700 on a setup directory")
            })?;
            Ok(())
        }
        Err(err) if err.kind() == std::io::ErrorKind::AlreadyExists => Ok(()),
        Err(err) => Err(map_privilege(
            &err,
            scope,
            "failed to create a setup directory",
        )),
    }
}

pub(super) fn refuse_existing(path: &Path, _label: &str) -> Result<(), PlatformError> {
    match fs::symlink_metadata(path) {
        Ok(_) => Err(PlatformError::new(
            ErrorCode::PathInvalid,
            "refusing to overwrite an existing setup target",
        )),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(_) => Err(PlatformError::new(
            ErrorCode::PathInvalid,
            "failed to inspect a setup target path",
        )),
    }
}

pub(super) fn map_privilege(
    err: &std::io::Error,
    scope: ServiceScope,
    fallback: &'static str,
) -> PlatformError {
    if err.kind() == std::io::ErrorKind::PermissionDenied && matches!(scope, ServiceScope::System) {
        return PlatformError::new(
            ErrorCode::PathInvalid,
            "insufficient privileges to write system setup paths; retry with `sudo ocd setup --yes`",
        );
    }
    if err.kind() == std::io::ErrorKind::AlreadyExists {
        return PlatformError::new(
            ErrorCode::PathInvalid,
            "refusing to overwrite an existing setup target",
        );
    }
    PlatformError::new(ErrorCode::PathInvalid, fallback)
}

pub(super) fn prompt_line(
    input: &mut dyn std::io::BufRead,
    prompt_out: &mut dyn Write,
    label: &str,
    default: &str,
) -> Result<String, PlatformError> {
    writeln_prompt(prompt_out, label)?;
    let mut line = String::new();
    input
        .read_line(&mut line)
        .map_err(|_| PlatformError::new(ErrorCode::ConfigInvalid, "failed to read setup prompt"))?;
    let trimmed = line.trim();
    if trimmed.is_empty() {
        Ok(default.to_owned())
    } else {
        Ok(trimmed.to_owned())
    }
}

pub(super) fn prompt_bool(
    input: &mut dyn std::io::BufRead,
    prompt_out: &mut dyn Write,
    label: &str,
    default: bool,
) -> Result<bool, PlatformError> {
    let answer = prompt_line(input, prompt_out, label, if default { "y" } else { "n" })?;
    match answer.to_ascii_lowercase().as_str() {
        "y" | "yes" => Ok(true),
        "n" | "no" => Ok(false),
        _ => Err(PlatformError::new(
            ErrorCode::ConfigInvalid,
            "expected y/n for a setup yes/no prompt",
        )),
    }
}

pub(super) fn writeln_prompt(
    prompt_out: &mut dyn Write,
    message: &str,
) -> Result<(), PlatformError> {
    writeln!(prompt_out, "{message}").map_err(|_| io_failed())
}

pub(super) fn io_failed() -> PlatformError {
    PlatformError::new(ErrorCode::Internal, "failed to write setup output")
}
