use super::*;

#[allow(
    clippy::too_many_arguments,
    reason = "transport boundary inputs mirror the wire contract"
)]
pub(super) fn prepare_staging(
    plan: &SetupPlan,
    staging_dir: &Path,
    admin_secret: &Path,
    deployer_secret: &Path,
    read_only_secret: &Path,
    master_key_file: &Path,
    objects_dir: &Path,
    startup_cwd: &Path,
) -> Result<(), PlatformError> {
    create_dir_mapped(staging_dir, plan.scope)?;
    let staging_secrets = staging_dir.join("secrets");
    create_dir_mapped(&staging_secrets, plan.scope)?;

    let (admin, deployer, read_only) = generate_distinct_tokens()?;
    exclusive_write_secret(&staging_secrets.join("admin.token"), &admin, plan.scope)?;
    exclusive_write_secret(
        &staging_secrets.join("deployer.token"),
        &deployer,
        plan.scope,
    )?;
    exclusive_write_secret(
        &staging_secrets.join("read-only.token"),
        &read_only,
        plan.scope,
    )?;

    let mut config = PlatformConfig::from_toml_str(DEFAULT_CONFIG)?;
    config.server.public_bind = plan.public_bind.clone();
    config.server.admin_auth = SecretReference {
        env: None,
        file: Some(admin_secret.to_owned()),
    };
    config.server.deployer_auth = SecretReference {
        env: None,
        file: Some(deployer_secret.to_owned()),
    };
    config.server.read_only_auth = SecretReference {
        env: None,
        file: Some(read_only_secret.to_owned()),
    };
    config.data.path = plan.data_dir.clone();
    config.data.master_key_file = master_key_file.to_owned();
    config.data.master_key_env = None;
    let ObjectStorageConfig::Local(local) = &mut config.object_storage else {
        return Err(PlatformError::new(
            ErrorCode::ConfigInvalid,
            "embedded default config must use local object storage",
        ));
    };
    local.path = objects_dir.to_owned();
    config.dashboard = DashboardConfig {
        enabled: plan.dashboard_enabled,
    };
    config.validate()?;

    let text = format!(
        "# Generated by `ocd setup`. Secrets are file references only.\n{}",
        toml::to_string_pretty(&config).map_err(|_| PlatformError::new(
            ErrorCode::ConfigInvalid,
            "failed to serialize setup configuration",
        ))?
    );
    let staging_config = staging_dir.join(plan.config_path.file_name().ok_or_else(|| {
        PlatformError::new(
            ErrorCode::ConfigPathInvalid,
            "setup config path must name a regular file",
        )
    })?);
    exclusive_write_bytes(&staging_config, text.as_bytes(), 0o600, plan.scope)?;
    let _ = load_platform_config_from(&staging_config, startup_cwd)?;
    Ok(())
}

pub(super) fn publish_exclusive(
    plan: &SetupPlan,
    staging_dir: &Path,
    staging_secrets: &Path,
    admin_secret: &Path,
    deployer_secret: &Path,
    read_only_secret: &Path,
) -> Result<Vec<PathBuf>, PlatformError> {
    let mut published = Vec::new();
    let result = (|| {
        publish_file(
            &staging_secrets.join("admin.token"),
            admin_secret,
            plan.scope,
        )?;
        published.push(admin_secret.to_owned());
        publish_file(
            &staging_secrets.join("deployer.token"),
            deployer_secret,
            plan.scope,
        )?;
        published.push(deployer_secret.to_owned());
        publish_file(
            &staging_secrets.join("read-only.token"),
            read_only_secret,
            plan.scope,
        )?;
        published.push(read_only_secret.to_owned());
        let staging_config = staging_dir.join(plan.config_path.file_name().ok_or_else(|| {
            PlatformError::new(
                ErrorCode::ConfigPathInvalid,
                "setup config path must name a regular file",
            )
        })?);
        publish_file(&staging_config, &plan.config_path, plan.scope)?;
        published.push(plan.config_path.clone());
        Ok(())
    })();
    if let Err(error) = result {
        if remove_published_files(&published).is_err() {
            return Err(PlatformError::new(
                ErrorCode::PathInvalid,
                "setup file publication failed and rollback was incomplete",
            ));
        }
        return Err(error);
    }
    Ok(published)
}

pub(super) fn rollback_pre_start(
    published: &[PathBuf],
    record: Option<&crate::instance_registry::InstanceRecord>,
    service_installed: bool,
    registry: &InstanceRegistry,
    manager: &dyn ServiceManager,
) -> Result<(), PlatformError> {
    if let Some(record) = record {
        if service_installed {
            manager.uninstall(record)?;
        }
        let selector = record.instance_id.parse()?;
        registry.remove(&selector)?;
    }
    remove_published_files(published)
}

pub(super) fn remove_published_files(paths: &[PathBuf]) -> Result<(), PlatformError> {
    for path in paths.iter().rev() {
        match fs::remove_file(path) {
            Ok(()) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(_) => {
                return Err(PlatformError::new(
                    ErrorCode::PathInvalid,
                    "failed to remove a setup file during rollback",
                ));
            }
        }
    }
    Ok(())
}

pub(super) fn assign_system_ownership(
    plan: &SetupPlan,
    account: &crate::service_manager::SystemServiceAccount,
) -> Result<(), PlatformError> {
    assign_path_ownership(&plan.data_dir, account, true)?;
    fs::set_permissions(&plan.config_path, fs::Permissions::from_mode(0o644)).map_err(|_| {
        PlatformError::new(
            ErrorCode::PathInvalid,
            "failed to make the system configuration readable by the service account",
        )
    })?;
    if let Some(parent) = plan.config_path.parent() {
        fs::set_permissions(parent, fs::Permissions::from_mode(0o755)).map_err(|_| {
            PlatformError::new(
                ErrorCode::PathInvalid,
                "failed to make the system configuration directory traversable",
            )
        })?;
    }
    Ok(())
}

pub(super) fn assign_path_ownership(
    path: &Path,
    account: &crate::service_manager::SystemServiceAccount,
    recursive: bool,
) -> Result<(), PlatformError> {
    let owner = format!("{}:{}", account.uid, account.gid);
    let path_text = path.to_string_lossy();
    let mut command = std::process::Command::new("chown");
    if recursive {
        command.arg("-R");
    }
    let status = command.args([owner.as_str(), path_text.as_ref()]).status();
    if status.is_ok_and(|status| status.success()) {
        Ok(())
    } else {
        Err(PlatformError::new(
            ErrorCode::PathInvalid,
            "failed to assign setup files to the non-root service account",
        ))
    }
}

pub(super) fn publish_file(
    from: &Path,
    to: &Path,
    scope: ServiceScope,
) -> Result<(), PlatformError> {
    refuse_existing(to, "setup target")?;
    fs::hard_link(from, to)
        .or_else(|_| fs::copy(from, to).map(|_| ()))
        .map_err(|err| {
            map_privilege(
                &err,
                scope,
                "failed to publish a setup file to its final path",
            )
        })?;
    let meta = fs::symlink_metadata(to)
        .map_err(|err| map_privilege(&err, scope, "failed to inspect a published setup file"))?;
    if meta.permissions().mode() & 0o777 != 0o600 {
        fs::set_permissions(to, fs::Permissions::from_mode(0o600)).map_err(|err| {
            map_privilege(
                &err,
                scope,
                "failed to set mode 0600 on a published setup file",
            )
        })?;
    }
    let _ = fs::remove_file(from);
    Ok(())
}

pub(super) fn generate_distinct_tokens() -> Result<(String, String, String), PlatformError> {
    let mut tokens = Vec::with_capacity(3);
    while tokens.len() < 3 {
        let candidate = random_token()?;
        if !tokens.iter().any(|existing| existing == &candidate) {
            tokens.push(candidate);
        }
    }
    Ok((tokens.remove(0), tokens.remove(0), tokens.remove(0)))
}

pub(super) fn random_token() -> Result<String, PlatformError> {
    let mut buf = [0u8; TOKEN_BYTES];
    rand::rngs::OsRng.try_fill_bytes(&mut buf).map_err(|_| {
        PlatformError::new(
            ErrorCode::Internal,
            "failed to generate setup Bearer token material",
        )
    })?;
    Ok(hex::encode(buf))
}

pub(super) fn exclusive_write_secret(
    path: &Path,
    value: &str,
    scope: ServiceScope,
) -> Result<(), PlatformError> {
    let mut body = value.as_bytes().to_vec();
    body.push(b'\n');
    exclusive_write_bytes(path, &body, 0o600, scope)
}

pub(super) fn exclusive_write_bytes(
    path: &Path,
    contents: &[u8],
    mode: u32,
    scope: ServiceScope,
) -> Result<(), PlatformError> {
    refuse_existing(path, "setup target")?;
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(mode)
        .open(path)
        .map_err(|err| map_privilege(&err, scope, "failed to exclusive-create a setup file"))?;
    file.write_all(contents)
        .map_err(|err| map_privilege(&err, scope, "failed to write a setup file"))?;
    file.sync_all()
        .map_err(|err| map_privilege(&err, scope, "failed to fsync a setup file"))?;
    Ok(())
}

pub(super) fn ensure_dir_tree(path: &Path, scope: ServiceScope) -> Result<(), PlatformError> {
    if path.as_os_str().is_empty() {
        return Err(PlatformError::new(
            ErrorCode::PathInvalid,
            "setup directory path is empty",
        ));
    }
    let mut built = PathBuf::new();
    for component in path.components() {
        built.push(component.as_os_str());
        if matches!(
            component,
            std::path::Component::RootDir | std::path::Component::Prefix(_)
        ) {
            continue;
        }
        if built.exists() {
            continue;
        }
        create_dir_mapped(&built, scope)?;
    }
    if path.exists() {
        ensure_dir_secure(path).map_err(|err| {
            if matches!(scope, ServiceScope::System) {
                PlatformError::new(
                    err.code(),
                    "insufficient privileges or insecure setup directory; retry with `sudo ocd setup --yes` when privilege is required",
                )
            } else {
                err
            }
        })?;
    }
    Ok(())
}

pub(super) fn create_dir_mapped(path: &Path, scope: ServiceScope) -> Result<(), PlatformError> {
    match fs::create_dir(path) {
        Ok(()) => {
            fs::set_permissions(path, fs::Permissions::from_mode(0o700)).map_err(|err| {
                map_privilege(&err, scope, "failed to set mode 0700 on a setup directory")
            })?;
            Ok(())
        }
        Err(err) if err.kind() == std::io::ErrorKind::AlreadyExists => Ok(()),
        Err(err) => Err(map_privilege(
            &err,
            scope,
            "failed to create a setup directory",
        )),
    }
}

pub(super) fn refuse_existing(path: &Path, _label: &str) -> Result<(), PlatformError> {
    match fs::symlink_metadata(path) {
        Ok(_) => Err(PlatformError::new(
            ErrorCode::PathInvalid,
            "refusing to overwrite an existing setup target",
        )),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(_) => Err(PlatformError::new(
            ErrorCode::PathInvalid,
            "failed to inspect a setup target path",
        )),
    }
}

pub(super) fn map_privilege(
    err: &std::io::Error,
    scope: ServiceScope,
    fallback: &'static str,
) -> PlatformError {
    if err.kind() == std::io::ErrorKind::PermissionDenied && matches!(scope, ServiceScope::System) {
        return PlatformError::new(
            ErrorCode::PathInvalid,
            "insufficient privileges to write system setup paths; retry with `sudo ocd setup --yes`",
        );
    }
    if err.kind() == std::io::ErrorKind::AlreadyExists {
        return PlatformError::new(
            ErrorCode::PathInvalid,
            "refusing to overwrite an existing setup target",
        );
    }
    PlatformError::new(ErrorCode::PathInvalid, fallback)
}

pub(super) fn prompt_line(
    input: &mut dyn std::io::BufRead,
    prompt_out: &mut dyn Write,
    label: &str,
    default: &str,
) -> Result<String, PlatformError> {
    writeln_prompt(prompt_out, label)?;
    let mut line = String::new();
    input
        .read_line(&mut line)
        .map_err(|_| PlatformError::new(ErrorCode::ConfigInvalid, "failed to read setup prompt"))?;
    let trimmed = line.trim();
    if trimmed.is_empty() {
        Ok(default.to_owned())
    } else {
        Ok(trimmed.to_owned())
    }
}

pub(super) fn prompt_bool(
    input: &mut dyn std::io::BufRead,
    prompt_out: &mut dyn Write,
    label: &str,
    default: bool,
) -> Result<bool, PlatformError> {
    let answer = prompt_line(input, prompt_out, label, if default { "y" } else { "n" })?;
    match answer.to_ascii_lowercase().as_str() {
        "y" | "yes" => Ok(true),
        "n" | "no" => Ok(false),
        _ => Err(PlatformError::new(
            ErrorCode::ConfigInvalid,
            "expected y/n for a setup yes/no prompt",
        )),
    }
}

pub(super) fn writeln_prompt(
    prompt_out: &mut dyn Write,
    message: &str,
) -> Result<(), PlatformError> {
    writeln!(prompt_out, "{message}").map_err(|_| io_failed())
}

pub(super) fn io_failed() -> PlatformError {
    PlatformError::new(ErrorCode::Internal, "failed to write setup output")
}
