/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedD1IndexRouteImport } from './routes/_authenticated/d1/index'
import { Route as AuthenticatedD1DatabaseIdRouteImport } from './routes/_authenticated/d1/$databaseId'
import { Route as AuthenticatedDurableObjectsIndexRouteImport } from './routes/_authenticated/durable-objects/index'
import { Route as AuthenticatedDurableObjectsNamespaceIdRouteImport } from './routes/_authenticated/durable-objects/$namespaceId'
import { Route as AuthenticatedKvIndexRouteImport } from './routes/_authenticated/kv/index'
import { Route as AuthenticatedKvNamespaceIdRouteImport } from './routes/_authenticated/kv/$namespaceId'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform/index'
import { Route as AuthenticatedQueuesIndexRouteImport } from './routes/_authenticated/queues/index'
import { Route as AuthenticatedQueuesQueueIdRouteImport } from './routes/_authenticated/queues/$queueId'
import { Route as AuthenticatedR2IndexRouteImport } from './routes/_authenticated/r2/index'
import { Route as AuthenticatedR2BucketIdRouteImport } from './routes/_authenticated/r2/$bucketId'
import { Route as AuthenticatedWorkersIndexRouteImport } from './routes/_authenticated/workers/index'
import { Route as AuthenticatedWorkersWorkerIdRouteImport } from './routes/_authenticated/workers/$workerId'
import { Route as AuthenticatedWorkflowsIndexRouteImport } from './routes/_authenticated/workflows/index'
import { Route as AuthenticatedWorkflowsWorkflowIdRouteImport } from './routes/_authenticated/workflows/$workflowId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedD1IndexRoute = AuthenticatedD1IndexRouteImport.update({
  id: '/d1/',
  path: '/d1/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedD1DatabaseIdRoute =
  AuthenticatedD1DatabaseIdRouteImport.update({
    id: '/d1/$databaseId',
    path: '/d1/$databaseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDurableObjectsIndexRoute =
  AuthenticatedDurableObjectsIndexRouteImport.update({
    id: '/durable-objects/',
    path: '/durable-objects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDurableObjectsNamespaceIdRoute =
  AuthenticatedDurableObjectsNamespaceIdRouteImport.update({
    id: '/durable-objects/$namespaceId',
    path: '/durable-objects/$namespaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKvIndexRoute = AuthenticatedKvIndexRouteImport.update({
  id: '/kv/',
  path: '/kv/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKvNamespaceIdRoute =
  AuthenticatedKvNamespaceIdRouteImport.update({
    id: '/kv/$namespaceId',
    path: '/kv/$namespaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/platform/',
    path: '/platform/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQueuesIndexRoute =
  AuthenticatedQueuesIndexRouteImport.update({
    id: '/queues/',
    path: '/queues/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQueuesQueueIdRoute =
  AuthenticatedQueuesQueueIdRouteImport.update({
    id: '/queues/$queueId',
    path: '/queues/$queueId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedR2IndexRoute = AuthenticatedR2IndexRouteImport.update({
  id: '/r2/',
  path: '/r2/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedR2BucketIdRoute = AuthenticatedR2BucketIdRouteImport.update({
  id: '/r2/$bucketId',
  path: '/r2/$bucketId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkersIndexRoute =
  AuthenticatedWorkersIndexRouteImport.update({
    id: '/workers/',
    path: '/workers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkersWorkerIdRoute =
  AuthenticatedWorkersWorkerIdRouteImport.update({
    id: '/workers/$workerId',
    path: '/workers/$workerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsIndexRoute =
  AuthenticatedWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsWorkflowIdRoute =
  AuthenticatedWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/d1/$databaseId': typeof AuthenticatedD1DatabaseIdRoute
  '/durable-objects/$namespaceId': typeof AuthenticatedDurableObjectsNamespaceIdRoute
  '/kv/$namespaceId': typeof AuthenticatedKvNamespaceIdRoute
  '/queues/$queueId': typeof AuthenticatedQueuesQueueIdRoute
  '/r2/$bucketId': typeof AuthenticatedR2BucketIdRoute
  '/workers/$workerId': typeof AuthenticatedWorkersWorkerIdRoute
  '/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
  '/d1/': typeof AuthenticatedD1IndexRoute
  '/durable-objects/': typeof AuthenticatedDurableObjectsIndexRoute
  '/kv/': typeof AuthenticatedKvIndexRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
  '/queues/': typeof AuthenticatedQueuesIndexRoute
  '/r2/': typeof AuthenticatedR2IndexRoute
  '/workers/': typeof AuthenticatedWorkersIndexRoute
  '/workflows/': typeof AuthenticatedWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/d1/$databaseId': typeof AuthenticatedD1DatabaseIdRoute
  '/durable-objects/$namespaceId': typeof AuthenticatedDurableObjectsNamespaceIdRoute
  '/kv/$namespaceId': typeof AuthenticatedKvNamespaceIdRoute
  '/queues/$queueId': typeof AuthenticatedQueuesQueueIdRoute
  '/r2/$bucketId': typeof AuthenticatedR2BucketIdRoute
  '/workers/$workerId': typeof AuthenticatedWorkersWorkerIdRoute
  '/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
  '/d1': typeof AuthenticatedD1IndexRoute
  '/durable-objects': typeof AuthenticatedDurableObjectsIndexRoute
  '/kv': typeof AuthenticatedKvIndexRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
  '/queues': typeof AuthenticatedQueuesIndexRoute
  '/r2': typeof AuthenticatedR2IndexRoute
  '/workers': typeof AuthenticatedWorkersIndexRoute
  '/workflows': typeof AuthenticatedWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/d1/$databaseId': typeof AuthenticatedD1DatabaseIdRoute
  '/_authenticated/durable-objects/$namespaceId': typeof AuthenticatedDurableObjectsNamespaceIdRoute
  '/_authenticated/kv/$namespaceId': typeof AuthenticatedKvNamespaceIdRoute
  '/_authenticated/queues/$queueId': typeof AuthenticatedQueuesQueueIdRoute
  '/_authenticated/r2/$bucketId': typeof AuthenticatedR2BucketIdRoute
  '/_authenticated/workers/$workerId': typeof AuthenticatedWorkersWorkerIdRoute
  '/_authenticated/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
  '/_authenticated/d1/': typeof AuthenticatedD1IndexRoute
  '/_authenticated/durable-objects/': typeof AuthenticatedDurableObjectsIndexRoute
  '/_authenticated/kv/': typeof AuthenticatedKvIndexRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
  '/_authenticated/queues/': typeof AuthenticatedQueuesIndexRoute
  '/_authenticated/r2/': typeof AuthenticatedR2IndexRoute
  '/_authenticated/workers/': typeof AuthenticatedWorkersIndexRoute
  '/_authenticated/workflows/': typeof AuthenticatedWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/d1/$databaseId'
    | '/durable-objects/$namespaceId'
    | '/kv/$namespaceId'
    | '/queues/$queueId'
    | '/r2/$bucketId'
    | '/workers/$workerId'
    | '/workflows/$workflowId'
    | '/d1/'
    | '/durable-objects/'
    | '/kv/'
    | '/platform/'
    | '/queues/'
    | '/r2/'
    | '/workers/'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/d1/$databaseId'
    | '/durable-objects/$namespaceId'
    | '/kv/$namespaceId'
    | '/queues/$queueId'
    | '/r2/$bucketId'
    | '/workers/$workerId'
    | '/workflows/$workflowId'
    | '/d1'
    | '/durable-objects'
    | '/kv'
    | '/platform'
    | '/queues'
    | '/r2'
    | '/workers'
    | '/workflows'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/d1/$databaseId'
    | '/_authenticated/durable-objects/$namespaceId'
    | '/_authenticated/kv/$namespaceId'
    | '/_authenticated/queues/$queueId'
    | '/_authenticated/r2/$bucketId'
    | '/_authenticated/workers/$workerId'
    | '/_authenticated/workflows/$workflowId'
    | '/_authenticated/d1/'
    | '/_authenticated/durable-objects/'
    | '/_authenticated/kv/'
    | '/_authenticated/platform/'
    | '/_authenticated/queues/'
    | '/_authenticated/r2/'
    | '/_authenticated/workers/'
    | '/_authenticated/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/d1/': {
      id: '/_authenticated/d1/'
      path: '/d1'
      fullPath: '/d1/'
      preLoaderRoute: typeof AuthenticatedD1IndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/d1/$databaseId': {
      id: '/_authenticated/d1/$databaseId'
      path: '/d1/$databaseId'
      fullPath: '/d1/$databaseId'
      preLoaderRoute: typeof AuthenticatedD1DatabaseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/durable-objects/': {
      id: '/_authenticated/durable-objects/'
      path: '/durable-objects'
      fullPath: '/durable-objects/'
      preLoaderRoute: typeof AuthenticatedDurableObjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/durable-objects/$namespaceId': {
      id: '/_authenticated/durable-objects/$namespaceId'
      path: '/durable-objects/$namespaceId'
      fullPath: '/durable-objects/$namespaceId'
      preLoaderRoute: typeof AuthenticatedDurableObjectsNamespaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kv/': {
      id: '/_authenticated/kv/'
      path: '/kv'
      fullPath: '/kv/'
      preLoaderRoute: typeof AuthenticatedKvIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kv/$namespaceId': {
      id: '/_authenticated/kv/$namespaceId'
      path: '/kv/$namespaceId'
      fullPath: '/kv/$namespaceId'
      preLoaderRoute: typeof AuthenticatedKvNamespaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queues/': {
      id: '/_authenticated/queues/'
      path: '/queues'
      fullPath: '/queues/'
      preLoaderRoute: typeof AuthenticatedQueuesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queues/$queueId': {
      id: '/_authenticated/queues/$queueId'
      path: '/queues/$queueId'
      fullPath: '/queues/$queueId'
      preLoaderRoute: typeof AuthenticatedQueuesQueueIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/r2/': {
      id: '/_authenticated/r2/'
      path: '/r2'
      fullPath: '/r2/'
      preLoaderRoute: typeof AuthenticatedR2IndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/r2/$bucketId': {
      id: '/_authenticated/r2/$bucketId'
      path: '/r2/$bucketId'
      fullPath: '/r2/$bucketId'
      preLoaderRoute: typeof AuthenticatedR2BucketIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workers/': {
      id: '/_authenticated/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof AuthenticatedWorkersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workers/$workerId': {
      id: '/_authenticated/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId'
      preLoaderRoute: typeof AuthenticatedWorkersWorkerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/': {
      id: '/_authenticated/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthenticatedWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/$workflowId': {
      id: '/_authenticated/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AuthenticatedWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedD1DatabaseIdRoute: typeof AuthenticatedD1DatabaseIdRoute
  AuthenticatedDurableObjectsNamespaceIdRoute: typeof AuthenticatedDurableObjectsNamespaceIdRoute
  AuthenticatedKvNamespaceIdRoute: typeof AuthenticatedKvNamespaceIdRoute
  AuthenticatedQueuesQueueIdRoute: typeof AuthenticatedQueuesQueueIdRoute
  AuthenticatedR2BucketIdRoute: typeof AuthenticatedR2BucketIdRoute
  AuthenticatedWorkersWorkerIdRoute: typeof AuthenticatedWorkersWorkerIdRoute
  AuthenticatedWorkflowsWorkflowIdRoute: typeof AuthenticatedWorkflowsWorkflowIdRoute
  AuthenticatedD1IndexRoute: typeof AuthenticatedD1IndexRoute
  AuthenticatedDurableObjectsIndexRoute: typeof AuthenticatedDurableObjectsIndexRoute
  AuthenticatedKvIndexRoute: typeof AuthenticatedKvIndexRoute
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
  AuthenticatedQueuesIndexRoute: typeof AuthenticatedQueuesIndexRoute
  AuthenticatedR2IndexRoute: typeof AuthenticatedR2IndexRoute
  AuthenticatedWorkersIndexRoute: typeof AuthenticatedWorkersIndexRoute
  AuthenticatedWorkflowsIndexRoute: typeof AuthenticatedWorkflowsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedD1DatabaseIdRoute: AuthenticatedD1DatabaseIdRoute,
  AuthenticatedDurableObjectsNamespaceIdRoute:
    AuthenticatedDurableObjectsNamespaceIdRoute,
  AuthenticatedKvNamespaceIdRoute: AuthenticatedKvNamespaceIdRoute,
  AuthenticatedQueuesQueueIdRoute: AuthenticatedQueuesQueueIdRoute,
  AuthenticatedR2BucketIdRoute: AuthenticatedR2BucketIdRoute,
  AuthenticatedWorkersWorkerIdRoute: AuthenticatedWorkersWorkerIdRoute,
  AuthenticatedWorkflowsWorkflowIdRoute: AuthenticatedWorkflowsWorkflowIdRoute,
  AuthenticatedD1IndexRoute: AuthenticatedD1IndexRoute,
  AuthenticatedDurableObjectsIndexRoute: AuthenticatedDurableObjectsIndexRoute,
  AuthenticatedKvIndexRoute: AuthenticatedKvIndexRoute,
  AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
  AuthenticatedQueuesIndexRoute: AuthenticatedQueuesIndexRoute,
  AuthenticatedR2IndexRoute: AuthenticatedR2IndexRoute,
  AuthenticatedWorkersIndexRoute: AuthenticatedWorkersIndexRoute,
  AuthenticatedWorkflowsIndexRoute: AuthenticatedWorkflowsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
