import { z } from "zod";

export const ErrorCodeSchema = z.enum([
  "config_path_invalid",
  "config_parse_failed",
  "runtime_invalid",
  "config_compile_failed",
  "migration_failed",
  "schema_too_new",
  "master_key_mismatch",
  "s3_unavailable",
  "cache_entry_corrupt",
  "runtime_exited_before_ready",
  "runtime_exited_in_flight",
  "process_killed",
  "snapshot_invalid",
  "restore_invalid",
  "schema_unsupported",
  "release_unsupported",
  "support_bundle_invalid",
  "data_dir_in_use",
  "admin_auth_required",
  "secret_ref_invalid",
  "path_invalid",
  "s3_prefix_invalid",
  "cache_bounds_invalid",
  "account_not_found",
  "worker_not_found",
  "worker_deleted",
  "deployment_not_found",
  "route_not_found",
  "resource_not_found",
  "resource_name_conflict",
  "resource_not_ready",
  "resource_referenced",
  "resource_unavailable",
  "resource_invariant_violation",
  "worker_name_conflict",
  "route_conflict",
  "deployment_not_ready",
  "deployment_active",
  "deployment_referenced",
  "deployment_invariant_violation",
  "service_binding_denied",
  "service_target_not_ready",
  "service_unavailable",
  "service_entrypoint_not_found",
  "service_limit_exceeded",
  "service_timeout",
  "service_target_referenced",
  "bundle_invalid",
  "idempotency_conflict",
  "bundle_too_large",
  "bundle_runtime_invalid",
  "compatibility_unsupported",
  "artifact_unavailable",
  "artifact_integrity_error",
  "entrypoint_not_found",
  "secret_invalid",
  "limit_invalid",
  "quota_exceeded",
  "admission_busy",
  "runtime_unavailable",
  "runtime_result_unknown",
  "resource_limit_exceeded",
  "platform_unavailable",
  "storage_pressure",
  "disk_hard_limit",
  "config_invalid",
  "internal",
  "asset_manifest_invalid",
  "asset_path_invalid",
  "asset_limit_exceeded",
  "asset_upload_incomplete",
  "asset_upload_conflict",
  "asset_integrity_error",
  "asset_storage_unavailable",
  "asset_config_unsupported",
  "kv_key_invalid",
  "kv_key_too_large",
  "kv_value_too_large",
  "kv_metadata_invalid",
  "kv_metadata_too_large",
  "kv_invalid_options",
  "kv_too_many_keys",
  "kv_response_too_large",
  "kv_cursor_invalid",
  "kv_busy",
  "kv_storage_full",
  "kv_unavailable",
  "kv_corrupt",
  "kv_result_unknown",
  "kv_internal_protocol_error",
  "r2_key_too_large",
  "r2_invalid_options",
  "r2_checksum_mismatch",
  "r2_ssec_invalid",
  "r2_multipart_invalid",
  "r2_object_too_large",
  "r2_metadata_too_large",
  "r2_cursor_invalid",
  "r2_bucket_not_empty",
  "r2_precondition_failed",
  "r2_overloaded",
  "r2_provider_unavailable",
  "r2_result_unknown",
  "r2_object_metadata_invalid",
  "r2_prefix_collision",
  "d1_type_error",
  "d1_sql_invalid",
  "d1_parameter_mismatch",
  "d1_authorizer_denied",
  "d1_limit_error",
  "d1_timeout",
  "d1_column_notfound",
  "d1_invalid_batch",
  "d1_session_error",
  "d1_dump_error",
  "d1_migration_drift",
  "d1_database_full",
  "d1_overloaded",
  "d1_result_unknown",
  "d1_database_corrupt",
  "d1_identity_mismatch",
  "d1_internal_protocol_error",
  "do_namespace_not_found",
  "do_id_invalid",
  "do_object_deleting",
  "do_deployment_stale",
  "do_class_not_found",
  "do_storage_unavailable",
  "do_storage_limit",
  "do_dispatch_timeout",
  "do_rpc_unsupported",
  "do_runtime_exception",
  "do_namespace_not_empty",
  "do_internal_protocol_error",
  "do_alarm_index_unavailable",
  "queue_not_found",
  "queue_name_conflict",
  "queue_not_ready",
  "queue_config_pending",
  "queue_referenced",
  "queue_not_empty",
  "queue_content_type_unsupported",
  "queue_invalid_message",
  "queue_message_too_large",
  "queue_batch_limit_exceeded",
  "queue_delay_invalid",
  "queue_backlog_limit_exceeded",
  "queue_storage_unavailable",
  "queue_send_result_unknown",
  "queue_consumer_conflict",
  "queue_consumer_not_ready",
  "queue_consumer_projection_pending",
  "queue_consumer_generation_stale",
  "queue_disposition_invalid",
  "queue_retry_delay_invalid",
  "queue_dlq_invalid",
  "queue_dlq_backpressured",
  "queue_custom_event_unsupported",
  "cron_expression_invalid",
  "cron_expression_unsupported",
  "cron_projection_pending",
  "cron_activation_stale",
  "cron_custom_event_unsupported",
  "queue_invariant_violation",
  "workflow_not_found",
  "workflow_not_ready",
  "workflow_version_not_ready",
  "workflow_binding_stale",
  "workflow_capability_mismatch",
  "workflow_instance_state_conflict",
  "workflow_instance_busy",
  "workflow_instance_cleanup_pending",
  "workflow_event_type_invalid",
  "workflow_event_queue_full",
  "workflow_step_timeout",
  "workflow_step_retries_exhausted",
  "workflow_non_retryable",
  "workflow_event_timeout",
  "workflow_instance_id_invalid",
  "workflow_instance_already_exists",
  "workflow_instance_not_found",
  "workflow_payload_too_large",
  "workflow_result_too_large",
  "workflow_serialization_unsupported",
  "workflow_state_quota_exceeded",
  "workflow_step_limit_exceeded",
  "workflow_step_config_unsupported",
  "workflow_duration_invalid",
  "workflow_method_unsupported",
  "workflow_non_deterministic",
  "workflow_run_stale",
  "workflow_step_stale",
  "workflow_runtime_unavailable",
  "workflow_execution_failed",
  "workflow_referenced",
  "workflow_invariant_violation",
  "workflow_name_conflict",
  "cache_key_invalid",
  "cache_put_rejected",
  "cache_limit_exceeded",
  "cache_unavailable",
  "cache_corrupt",
  "cache_protocol_error",
  "cache_result_unknown",
  "scheduler_unavailable",
  "scheduler_corrupt",
  "scheduler_busy",
  "scheduler_internal_protocol_error",
  "scheduler_kind_not_enabled",
  "binding_not_found",
  "binding_type_mismatch",
  "binding_permission_denied",
  "binding_capability_unsupported",
  "binding_protocol_error",
  "binding_limit_exceeded",
  "image_input_invalid",
  "image_format_unsupported",
  "image_option_unsupported",
  "image_limit_exceeded",
  "image_timeout",
  "image_unavailable",
  "image_protocol_error",
]);

/** Normalize Rust uppercase wire codes to the SDK's lowercase enum tokens. */
export function normalizeOperatorErrorCode(value: unknown): unknown {
  return typeof value === "string" ? value.toLowerCase() : value;
}

export const OperatorErrorBodySchema = z.strictObject({
  ok: z.literal(false),
  error: z.strictObject({
    code: z.preprocess(normalizeOperatorErrorCode, ErrorCodeSchema),
    message: z.string(),
    requestId: z.string(),
  }),
});

export type OperatorErrorBody = z.output<typeof OperatorErrorBodySchema>;

export const CursorPageSchema = <T extends z.ZodType>(itemSchema: T) =>
  z.strictObject({
    items: z.array(itemSchema),
    nextCursor: z.string().nullable().optional(),
  });

export type CursorPage<T> = {
  items: T[];
  nextCursor?: string | null;
};

export const ListQuerySchema = z.strictObject({
  limit: z.number().int().min(1).max(1000).optional(),
  cursor: z.string().optional(),
  signal: z.custom<AbortSignal>().optional(),
});

export type ListQuery = z.input<typeof ListQuerySchema>;

/** Success schema for operator endpoints that return `204 No Content`. */
export const EmptyResponseSchema = z.void();
