import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { chmod, mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { promisify } from "node:util";
import test from "node:test";
import { runCli } from "../src/cli.ts";
import { generateEnvTypes, writeGeneratedTypes } from "../src/generate-types.ts";
import { loadProject } from "../src/project.ts";
import { loadFormalRuntimeLock } from "../src/runtime-lock.ts";

const execFileAsync = promisify(execFile);
const require = createRequire(resolve(import.meta.dirname, "../package.json"));
const compiler = resolve(dirname(require.resolve("typescript/package.json")), "bin/tsc");
const bin = resolve(import.meta.dirname, "../src/bin.ts");
const typesPackage = resolve(import.meta.dirname, "../../types");
const cloudflareTypes = resolve(typesPackage, "node_modules/@cloudflare/workers-types");

const config = {
  name: "hello",
  main: "src/index.ts",
  
  vars: {
    GREETING: "你好 🌍",
    COUNT: 42,
    FLAG: true,
    NESTED: { b: [null, false], a: 1 },
    "empty obj": {},
    "weird-key": "x",
  },
  secrets: { TOKEN: { env: "ABSENT_PROJECT_SECRET" } },
  bindings: {
    KV: { type: "kv_namespace", id: "kv-id" },
    BUCKET: { type: "r2_bucket", id: "r2-id" },
    DB: { type: "d1_database", id: "d1-id" },
    DO: { type: "do_namespace", id: "do-id", className: "PortableObject" },
    QUEUE: { type: "queue_producer", id: "q-id" },
    FLOW: { type: "workflow", id: "wf-id", className: "PortableWorkflow" },
  },
  services: [
    { binding: "SELF", service: "hello" },
    { binding: "ADMIN", service: "hello", entrypoint: "Admin" },
    { binding: "CATALOG", service: "catalog", entrypoint: "CatalogApi" },
    { binding: "OTHER", service: "other" },
  ],
  assets: { directory: "dist", binding: "ASSETS" },
  images: { binding: "IMAGES" },
  version_metadata: { binding: "VERSION", tag: "release-1" },
};

async function fixture(t, value) {
  const directory = await mkdtemp(join(tmpdir(), "open-compute-types-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  await mkdir(join(directory, "src"), { recursive: true });
  const filename = join(directory, "open-compute.json");
  await writeFile(filename, JSON.stringify(value));
  return { directory, filename };
}

function expectedTypes() {
  const specifier = "./src/index";
  return `/* eslint-disable */
// Generated by oc types
/// <reference types="@open-compute/workers-types" />

interface __BaseEnv_Env {
	ADMIN: Service<typeof import(${JSON.stringify(specifier)}).Admin>;
	ASSETS: Fetcher;
	BUCKET: R2Bucket;
	CATALOG: Service /* entrypoint CatalogApi from catalog */;
	COUNT: 42;
	DB: D1Database;
	DO: DurableObjectNamespace;
	FLAG: true;
	FLOW: Workflow;
	GREETING: "你好 🌍";
	IMAGES: ImagesBinding;
	KV: KVNamespace;
	NESTED: { a: 1; b: [null, false] };
	OTHER: Fetcher /* other */;
	QUEUE: Queue;
	SELF: Service<typeof import(${JSON.stringify(specifier)}).default>;
	TOKEN: string;
	VERSION: WorkerVersionMetadata;
	"empty obj": {};
	"weird-key": "x";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import(${JSON.stringify(specifier)});
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
`;
}

test("maps every configured Env binding and omits unconfigured products", async t => {
  const { directory, filename } = await fixture(t, config);
  const project = await loadProject(filename);
  const output = join(directory, "worker-configuration.d.ts");
  const generated = generateEnvTypes(project, output);
  assert.equal(generated, expectedTypes());
  assert.doesNotMatch(generated, /ABSENT_PROJECT_SECRET|kv-id|r2-id|d1-id|do-id|q-id|wf-id|release-1|\[method: string\]: unknown/);
  const minimalPath = join(directory, "minimal.json");
  await writeFile(minimalPath, JSON.stringify({ name: "hello", main: "src/index.ts" }));
  const minimal = generateEnvTypes(await loadProject(minimalPath), output);
  for (const name of ["KVNamespace", "R2Bucket", "D1Database", "DurableObjectNamespace", "Queue", "Workflow", "ImagesBinding", "WorkerVersionMetadata", "Fetcher", "Service"]) {
    assert.doesNotMatch(minimal, new RegExp(`: ${name}\\b`));
  }
  assert.match(minimal, /mainModule: typeof import\("\.\/src\/index"\)/);
});

test("self-service uses local RPC composition and external services stay unparameterized", async t => {
  const { directory, filename } = await fixture(t, {
    name: "hello",
    main: "src/index.ts",
    
    services: [
      { binding: "SELF", service: "hello" },
      { binding: "ADMIN", service: "hello", entrypoint: "Admin" },
      { binding: "CATALOG", service: "catalog", entrypoint: "CatalogApi" },
      { binding: "OTHER", service: "other" },
    ],
  });
  const generated = generateEnvTypes(await loadProject(filename), join(directory, "worker-configuration.d.ts"));
  assert.match(generated, /SELF: Service<typeof import\("\.\/src\/index"\)\.default>;/);
  assert.match(generated, /ADMIN: Service<typeof import\("\.\/src\/index"\)\.Admin>;/);
  assert.match(generated, /CATALOG: Service \/\* entrypoint CatalogApi from catalog \*\//);
  assert.match(generated, /OTHER: Fetcher \/\* other \*\//);
  const frameworkPath = join(directory, "framework.json");
  await writeFile(frameworkPath, JSON.stringify({
    name: "framework", 
    frameworkOutput: ".wrangler/deploy/config.json",
    services: [{ binding: "SELF", service: "framework", entrypoint: "Admin" }],
  }));
  const framework = generateEnvTypes(await loadProject(frameworkPath), join(directory, "worker-configuration.d.ts"));
  assert.match(framework, /SELF: Service \/\* entrypoint Admin from framework \*\//);
  assert.doesNotMatch(framework, /GlobalProps|mainModule/);
});

test("repeat generation is byte-identical and replaces a prior generated file", async t => {
  const { directory, filename } = await fixture(t, config);
  const project = await loadProject(filename);
  const output = join(directory, "worker-configuration.d.ts");
  const first = generateEnvTypes(project, output);
  const second = generateEnvTypes(await loadProject(filename), output);
  assert.equal(first, second);
  await writeGeneratedTypes(output, first);
  await writeGeneratedTypes(output, second);
  assert.equal(await readFile(output, "utf8"), first);
});

test("refuses symlinks, directories, and non-generated destinations", async t => {
  const { directory } = await fixture(t, { name: "hello", main: "src/index.ts" });
  const content = generateEnvTypes(await loadProject(join(directory, "open-compute.json")), join(directory, "worker-configuration.d.ts"));
  const linked = join(directory, "linked.d.ts");
  await symlink(join(directory, "src/index.ts"), linked);
  await writeFile(join(directory, "src/index.ts"), "export default {};");
  await assert.rejects(writeGeneratedTypes(linked, content), /symbolic link/);
  await assert.rejects(writeGeneratedTypes(directory, content), /regular file/);
  const handmade = join(directory, "handmade.d.ts");
  await writeFile(handmade, "interface Env {}\n");
  await assert.rejects(writeGeneratedTypes(handmade, content), /not generated by oc types/);
  const spoofed = join(directory, "spoofed.d.ts");
  await writeFile(spoofed, `interface Env {}\n${content}`);
  await assert.rejects(writeGeneratedTypes(spoofed, content), /not generated by oc types/);
});

test("fails closed on duplicate Env sources including quoted keys", async t => {
  const { directory, filename } = await fixture(t, { name: "hello", main: "src/index.ts" });
  const base = await loadProject(filename);
  const output = join(directory, "worker-configuration.d.ts");
  const assets = {
    directory: "dist", binding: "ASSETS", runWorkerFirst: false,
    htmlHandling: "auto-trailing-slash", notFoundHandling: "none", publishSourceMaps: false,
  };
  const collisions = [
    { ...base, vars: { TOKEN: "visible-secret-value" }, secrets: { TOKEN: { env: "ABSENT_PROJECT_SECRET" } } },
    { ...base, vars: { KV: "x" }, bindings: { KV: { type: "kv_namespace", id: "kv-id" } } },
    { ...base, secrets: { KV: { env: "ABSENT_PROJECT_SECRET" } }, bindings: { KV: { type: "kv_namespace", id: "kv-id" } } },
    { ...base, vars: { SELF: "x" }, services: { SELF: { service: "hello" } } },
    { ...base, vars: { ASSETS: "x" }, assets },
    { ...base, vars: { IMAGES: true }, runtimeFeatures: { ...base.runtimeFeatures, images: { binding: "IMAGES" } } },
    { ...base, vars: { VERSION: true }, runtimeFeatures: { ...base.runtimeFeatures, versionMetadata: { binding: "VERSION" } } },
    { ...base, vars: { "weird-key": "x" }, secrets: { "weird-key": { env: "ABSENT_PROJECT_SECRET" } } },
  ];
  for (const project of collisions) {
    assert.throws(() => generateEnvTypes(project, output), error => {
      assert.match(error.message, /duplicate Env property/);
      assert.doesNotMatch(error.message, /visible-secret-value|ABSENT_PROJECT_SECRET/);
      return true;
    });
  }
});

test("cli types uses imported framework Env without claiming a TypeScript main module", async t => {
  const lock = await loadFormalRuntimeLock();
  const { directory, filename } = await fixture(t, {
    name: "framework",
    
    frameworkOutput: ".wrangler/deploy/config.json",
    vars: { MODE: "prod" },
    services: [
      { binding: "SELF", service: "framework" },
      { binding: "ADMIN", service: "framework", entrypoint: "Admin" },
      { binding: "CATALOG", service: "catalog", entrypoint: "CatalogApi" },
    ],
  });
  await mkdir(join(directory, ".wrangler", "deploy"), { recursive: true });
  await mkdir(join(directory, "dist", "server", "chunks"), { recursive: true });
  await mkdir(join(directory, "dist", "client", "assets"), { recursive: true });
  await writeFile(join(directory, ".wrangler", "deploy", "config.json"), JSON.stringify({
    configPath: "../../dist/server/wrangler.json",
    auxiliaryWorkers: [],
  }));
  await writeFile(join(directory, "dist", "server", "wrangler.json"), JSON.stringify({
    name: "framework", main: "index.js", compatibility_date: lock.effectiveCompatibilityDate,
    rules: [{ type: "ESModule", globs: ["**/*.js"] }],
    no_bundle: true,
    vars: { MODE: "prod" },
    assets: {
      directory: "../client", binding: "ASSETS", run_worker_first: ["/api/*"],
      html_handling: "auto-trailing-slash", not_found_handling: "none",
    },
    services: [
      { binding: "SELF", service: "framework" },
      { binding: "ADMIN", service: "framework", entrypoint: "Admin" },
      { binding: "CATALOG", service: "catalog", entrypoint: "CatalogApi" },
    ],
    images: { binding: "IMAGES" },
    version_metadata: { binding: "VERSION", tag: "release-1" },
  }));
  await writeFile(join(directory, "dist", "server", "index.js"), "import('./chunks/page-abc.js'); export default {};");
  await writeFile(join(directory, "dist", "server", "chunks", "page-abc.js"), "export const page = 1;");
  await writeFile(join(directory, "dist", "client", "index.html"), "<main>app</main>");
  await writeFile(join(directory, "dist", "client", "assets", "app-abc.js"), "globalThis.client = true;");
  const env = { ...process.env, OPEN_COMPUTE_OCD: "/missing/ocd" };
  const { stdout } = await execFileAsync(process.execPath, [bin, "types", "--config", filename], { env });
  const output = join(directory, "worker-configuration.d.ts");
  assert.equal(stdout, `Wrote ${output}\n`);
  const generated = await readFile(output, "utf8");
  assert.match(generated, /ASSETS: Fetcher;/);
  assert.match(generated, /IMAGES: ImagesBinding;/);
  assert.match(generated, /MODE: "prod";/);
  assert.match(generated, /SELF: Fetcher \/\* framework \*\//);
  assert.match(generated, /ADMIN: Service \/\* entrypoint Admin from framework \*\//);
  assert.match(generated, /CATALOG: Service \/\* entrypoint CatalogApi from catalog \*\//);
  assert.match(generated, /VERSION: WorkerVersionMetadata;/);
  assert.doesNotMatch(generated, /GlobalProps|mainModule|index\.js|typeof import/);
  assert.doesNotMatch(generated, /ABSENT_PROJECT_SECRET|release-1/);
});

test("cli types writes default and explicit outputs without ocd", async t => {
  const { directory, filename } = await fixture(t, {
    name: "hello", main: "src/index.ts", 
    vars: { GREETING: "Hello from TypeScript" },
  });
  const env = { ...process.env, OPEN_COMPUTE_OCD: "/missing/ocd" };
  const { stdout } = await execFileAsync(process.execPath, [bin, "types", "--config", filename], { env });
  const defaultOutput = join(directory, "worker-configuration.d.ts");
  assert.equal(stdout, `Wrote ${defaultOutput}\n`);
  assert.match(await readFile(defaultOutput, "utf8"), /GREETING: "Hello from TypeScript"/);
  const explicit = join(directory, "custom", "env.d.ts");
  const explicitRun = await execFileAsync(process.execPath, [bin, "types", "--config", filename, "--out", explicit], { env });
  assert.equal(explicitRun.stdout, `Wrote ${explicit}\n`);
  assert.match(await readFile(explicit, "utf8"), /mainModule: typeof import\("\.\.\/src\/index"\)/);
  await assert.rejects(runCli(["types", "src/index.ts", "--config", filename]), /entry argument/);
  await assert.rejects(runCli(["types", "--config", filename, "--ocd", "/missing/ocd"]), /--ocd/);
  await assert.rejects(runCli(["types", "--config", filename, "--json"]), /--json/);
});

test("cli build accepts the ocd option and environment variable", async t => {
  const { directory, filename } = await fixture(t, { name: "hello", main: "src/index.ts" });
  await writeFile(join(directory, "src", "index.ts"), "export default { fetch: () => new Response('ok') };\n");
  await writeFile(join(directory, "tsconfig.json"), JSON.stringify({
    compilerOptions: {
      target: "ES2024", module: "Preserve", moduleResolution: "Bundler",
      lib: ["ES2024", "DOM"], types: [], strict: true, noEmit: true,
    },
    include: ["src/**/*.ts"],
  }));
  const ocd = join(directory, "ocd");
  await writeFile(ocd, "#!/bin/sh\ntest \"$1\" = worker || exit 31\ntest \"$2\" = bundle || exit 32\ncat >/dev/null\nprintf bundle-v1\n");
  await chmod(ocd, 0o700);

  const optionOutput = join(directory, "option.bundle");
  await execFileAsync(process.execPath, [bin, "build", "--config", filename, "--ocd", ocd, "--out", optionOutput]);
  assert.equal(await readFile(optionOutput, "utf8"), "bundle-v1");

  const environmentOutput = join(directory, "environment.bundle");
  await execFileAsync(process.execPath, [bin, "build", "--config", filename, "--out", environmentOutput], {
    env: { ...process.env, OPEN_COMPUTE_OCD: ocd },
  });
  assert.equal(await readFile(environmentOutput, "utf8"), "bundle-v1");
});

test("generated declarations compile against pinned Workers types", async t => {
  const { directory, filename } = await fixture(t, config);
  await writeFile(join(directory, "src/index.ts"), `import { WorkerEntrypoint } from "cloudflare:workers";
export class Admin extends WorkerEntrypoint {
  fetch(): Response { return new Response("admin"); }
}
export default {
  fetch(_request: Request, env: Env): Response {
    const greeting: string = env.GREETING;
    void env.KV.get;
    void env.BUCKET.get;
    void env.DB.prepare;
    void env.DO.idFromName;
    void env.QUEUE.send;
    void env.FLOW.create;
    void env.ASSETS.fetch;
    void env.IMAGES.info;
    void env.VERSION.id;
    void env.SELF.fetch;
    void env.ADMIN.fetch;
    void env.CATALOG.fetch;
    void env.OTHER.fetch;
    const token: string = env.TOKEN;
    return new Response(greeting + token);
  },
} satisfies ExportedHandler<Env>;
`);
  const output = join(directory, "worker-configuration.d.ts");
  await writeGeneratedTypes(output, generateEnvTypes(await loadProject(filename), output));
  await writeFile(join(directory, "tsconfig.json"), JSON.stringify({
    compilerOptions: {
      target: "ES2024", module: "Preserve", moduleResolution: "Bundler",
      lib: ["ES2024"], types: ["@open-compute/workers-types"], strict: true, noEmit: true, skipLibCheck: false,
    },
    include: ["worker-configuration.d.ts", "src/**/*.ts"],
  }));
  await mkdir(join(directory, "node_modules/@open-compute"), { recursive: true });
  await mkdir(join(directory, "node_modules/@cloudflare"), { recursive: true });
  await symlink(typesPackage, join(directory, "node_modules/@open-compute/workers-types"));
  await symlink(cloudflareTypes, join(directory, "node_modules/@cloudflare/workers-types"));
  await execFileAsync(process.execPath, [compiler, "--project", "tsconfig.json", "--pretty", "false"], { cwd: directory });
});
